### ISSUE TITLE
Context menu in StandardUICommand sample is broken

### ISSUE THREAD

**Issue by YuliKl** [microsoft/Xaml-Controls-Gallery#106]
**Describe the bug**

Right-clicking an item to delete doesn't work. The item gets desected on right-click and choosing the Delete menu option does nothing.

**Steps to reproduce the bug**

1. Go to StandardUICommand page
2. Right-click on "List item 2"
3. Click Delete in the open context menu

**Expected behavior**

List item 2 is removed from the list of items.

**Actual behavior**

List item 2 loses its hovered/pressed backplate as the context menu opens, so the context menu doesn't appear connected to any list item. The Delete menu option has no effect.

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/59801394-32b8bf80-929d-11e9-8110-a6722c52100c.png)

**Version Info**

Gallery version (found on Settings page): 

1.2.8.0

**Comment by marb2000** [comment]
@YuliKl , I believe that this is the bug on the app. The behavior is not the expected one in this scenario. For example in Outlook: Right click over an email in the list that is not selected. Select delete on the context menu. You will observe that it deletes the email regardless of the selected email.  

My recommendation is to modify the sample deleting the element under the mouse pointer.
