### ISSUE TITLE
Styles > Acrylic page still crashes in 1.2.9.0

### ISSUE THREAD

**Issue by stmoy** [microsoft/Xaml-Controls-Gallery#107]
**Describe the bug**

Since updating the Xaml Controls Gallery app in the store to version 1.2.8 (which includes 19H1 and WinUI2.2 preview), the app has become unstable per reports in the dev center.

One known issue is that the Acrylic Luminosity Opacity slider causes a crash. Is that the only issue?

**Version Info**

Gallery version (found on Settings page): 

1.2.8

**Additional context**

**Comment by jevansaks** [comment]
Debugged some of the crashes, it happens when dragging the "Tint Luminosity Opacity" slider. Back to you, @stmoy to figure out where this bug should go.

**Comment by ndcooke** [comment]
Attempting to open the Acrylic control in general crashes the application on 1803.
![image](https://user-images.githubusercontent.com/14249205/61886734-d9f4cc00-aec5-11e9-8967-58f35ee2cc64.png)

**Comment by stmoy** [comment]
It looks like the acrylic page is still crashing. @kikisaints can you please fully remove the sample?

**Comment by YuliKl** [comment]
@chingucoding, just wanted to bring your attention to this issue, in case you have time or interest in taking a look. 😎

**Comment by chingucoding** [comment]
@YuliKl Thank you for pointing this issue out. I will look into this!
