### ISSUE TITLE
A MenuFlyout with ToggleMenuFlyoutItems and MenuFlyoutSeparator has padding for icons/glyphs

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/Xaml-Controls-Gallery#112]
**Describe the bug**

A MenuFlyout with ToggleMenuflyoutItems and MenuFlyoutSeparator has padding for icons/glyphs

**Steps to reproduce the bug**

1. Go to MenuFlyout
2. Click on "Options" under "A MenuFlyout with ToggleMenuflyoutItems and MenuFlyoutSeparator has padding for icons/glyphs"

**Expected behavior**

![image](https://user-images.githubusercontent.com/51363864/60506687-bb0d7a80-9d09-11e9-82c6-48db267d03bd.png)

**Actual behavior**

![image](https://user-images.githubusercontent.com/51363864/60506698-c1035b80-9d09-11e9-9a83-84e447b63d10.png)

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 
1.2.8.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by stmoy** [comment]
The reason for the space is that the Repeat and Shuffle options can be toggled on. It looks strange when they are both toggled off, but here's what it looks like when one of them is toggled on: 
![image](https://user-images.githubusercontent.com/25991996/60533327-36444180-9cb4-11e9-9556-ab866ec814c4.png)

This could be made clearer if the app had one of the items checked by default. This should be a quick fix so I'll keep this issue open to track that work.

**Comment by stmoy** [comment]
I've updated the sample to have the items checked by default, which should hopefully make the reason for the "gap" more apparent. Thank you for reporting this @Poopooracoocoo

**Comment by Poopooracoocoo** [comment]
Thanks! :D
