### ISSUE TITLE
Suggestion: Add link to this GitHub issues page directly from Controls Gallery app

### ISSUE THREAD

**Issue by chigy** [microsoft/Xaml-Controls-Gallery#118]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] New sample
- [ ] Addition to existing sample
- [x] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**
All of them

The suggestion is to make the link to GitHub issues page available directly from the controls' pages just like guidance doc having it on the bottom of each pages.

**Describe the sample**

**Is your sample request related to a problem? Please describe it**

**Additional context**

**Comment by YuliKl** [comment]
@chigy, to confirm, is this the link you'd like to see added to the Gallery? https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose

**Comment by chigy** [comment]
@YuliKl , no I was thinking to the Controls Gallery issue since it is about it.
https://github.com/microsoft/Xaml-Controls-Gallery/issues/new/choose

**Comment by YuliKl** [comment]
Got it. Thank you for clarifying.

**Comment by YuliKl** [comment]
PR with fix is merged.
