### ISSUE TITLE
Code snippet for Luminosity in-App Acrylic is wrong

### ISSUE THREAD

**Issue by pratikone** [microsoft/Xaml-Controls-Gallery#119]
The bug is that the code snippet in Acrylic section for Luminosity In-App Acrylic refers to a resource by a different non-existing name than what it is. Custom resource is created with key CustomAcrylicBrush but the code tries to refer CustomAcrylicInAppLuminosity which doesn't exist.

**Comment by chingucoding** [comment]
I think this issue should be closed now since it was fixed with PR #123

**Comment by stmoy** [comment]
Good catch, thanks.
