### ISSUE TITLE
Should Hub be removed from gallery or marked as not recommended for use?

### ISSUE THREAD

**Issue by chigy** [microsoft/Xaml-Controls-Gallery#120]
**Describe the bug**

Since we de-prioritized hub control in documents, should we do the same for controls gallery sample?

**Steps to reproduce the bug**

**Expected behavior**

**Actual behavior**

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [ ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by YuliKl** [comment]
I would like to remove Hub's sample page.

**Comment by stmoy** [comment]
After internal conversation, we agree that removing the Hub page from the Gallery is the right thing to do. 

(Other options considered: mark/tag it as deprecated, or hiding it from the table of contents but still allow it to be found via search.)
