### ISSUE TITLE
The NavigationView menu is not acrylic anymore

### ISSUE THREAD

**Issue by LoriBru** [microsoft/Xaml-Controls-Gallery#122]
The NavigationView menu is not acrylic anymore in the latest version, on Windows 10 May 2019 Update (18362). 
It used to be acrylic before, now it is just solid color.
Why this step back?

Also the back navigation arrow was moved from the title bar. I think the UI looked more compact before.

![Annotation 2019-07-24 141202](https://user-images.githubusercontent.com/22811725/61792444-0bfe2380-ae1d-11e9-9f7b-ba9dcca75305.png)

**Comment by YuliKl** [comment]
@LoriBru, thank you for your feedback. We updated our guidelines for when to use acrylic. NavigationView's pane in Expanded mode no longer aligns with that guidance, so its acrylic has been removed. For much more about the rationale and discussion on this topic, please see https://github.com/microsoft/microsoft-ui-xaml/issues/761
