### ISSUE TITLE
Dark Theme for ContentDialog

### ISSUE THREAD

**Issue by moshegutman** [microsoft/Xaml-Controls-Gallery#126]
**Describe the bug**
The ContentDialog shows up in Light Theme when Dark Theme is selected

**Steps to reproduce the bug**
1. Go to 'Settings'
2. Click on 'Dark' under the 'Theme Mode' options
3. Navigate to the 'Dialogs and Flyouts' section
4. Select 'ContentDialog'
5. Click 'Show Dialog'

**Expected behavior**
If the Theme of the application is in Dark Theme, the Content Dialog should also be in Dark Theme.

**Actual behavior**
The Content Dialog appears with a Light Theme 

**Screenshots**

![dark-1](https://user-images.githubusercontent.com/3697619/61910240-b186c500-aef9-11e9-86c9-d1d5dd8adb9c.PNG)
![dark-2](https://user-images.githubusercontent.com/3697619/61910241-b186c500-aef9-11e9-96e9-ff879a8ce065.PNG)

**Version Info**

Gallery version (found on Settings page): 
1.2.8.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by moshegutman** [comment]
I believe this is an issue with UWP itself, not the sample. Is there a better place to report this?

**Comment by YuliKl** [comment]
Thanks @moshegutman. There are actually two issues here. 
1. The dialog in the Gallery doesn't query the current theme of the app before opening.
2. ContentDialog's smoke layer doesn't respect the control's ElementTheme.

The second issue should be reported in https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose.

**Comment by moshegutman** [comment]
Thanks! I think I found this issue already opened here: https://github.com/microsoft/microsoft-ui-xaml/issues/840

**Comment by YuliKl** [comment]
Rather then making a partial fix in the Controls Gallery, we're going to wait for the ContentDialog control to be updated. Closing this issue for now.
