### ISSUE TITLE
Protocol activation does not work when app is already open

### ISSUE THREAD

**Issue by chingucoding** [microsoft/Xaml-Controls-Gallery#134]
**Describe the bug**

The protocol activation does not work when the application is running. Instead of navigating to the item page, the app opens the "New item" page.

**Steps to reproduce the bug**

1. Open XAML Controls Gallery
2. Hit Win+R and enter `xamlcontrolsgallery:///item/ProgressRing`

**Expected behavior**

The app continues to the ProgressRing page.

**Actual behavior**

The app opens the "New item" page.

**Screenshots**

![starting-with-app-started](https://user-images.githubusercontent.com/16122379/62765886-68a24500-ba91-11e9-8f24-07cc7bcf546a.gif)

**Version Info**

Gallery version (found on Settings page): 

1.2.8
Windows 10 version:
- [x] Insider Build (18950)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

See this issue: #19 for additional context.

**Comment by chingucoding** [comment]
So apparently under Windows Insider Build 18956 this issue seems to be revolved:

![starting-with-app-started](https://user-images.githubusercontent.com/16122379/62858480-b968a680-bcfa-11e9-9855-1fbb584a9c11.gif)

Under the new Insider Build protocol activation works no matter if the app is already running.
Tested using the release available from Microsoft Store and building the project myself.

On older Windows Builds (tested 17763) the issue is still existent.

**Comment by stmoy** [comment]
The gif above looks like it is starting on the What's New page and then protocol activating. Agreed that this works.

However, if you start on a specific control page and then protocol activate, the issue shows up for me (even on latest builds of Windows).

Am I misunderstanding the gif?

**Comment by chingucoding** [comment]
Tested out the scenario and it turns out that when a control page is already open, the protocol activation does not work. I'll look further into this!

**Comment by chingucoding** [comment]
On the most latest build this issue seems to be resolved for me completely.
The following scenarios have worked succesfully (meaning it navigates succesfully to the item page):
- App not running
- App running, What's New page open
- App running item page open (e.g. Button page)

I was testing this on Insider Preview 18956 with OS build 18956.1000

@stmoy Can you confirm?

If this is the case, I would suggest closing this issue as the app than behaves as expected (on the latest version of the Insider Preview)

**Comment by stmoy** [comment]
+1, thank you for following up. I'm seeing the same behavior that you are - it looks like the three scenarios are fixed. 

Why though? It's a mystery 🤷‍♂️
