### ISSUE TITLE
Colors in SplitButton sample don't always work as expected

### ISSUE THREAD

**Issue by YuliKl** [microsoft/Xaml-Controls-Gallery#139]
**Describe the bug**

**Steps to reproduce the bug**

1. Go to SplitButton page
2. Type some text (e.g. "This text is black.")
3. Select a subset of the text (e.g. the word "text") and choose red from the SplitButton flyout
4. Click at the end of the text and type a few more characters

**Expected behavior**

The new characters will be red

**Actual behavior**

The new characters are still black like the older text
**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/63059223-a6dda100-bea3-11e9-8dd5-2d1aad359dbb.png)

**Version Info**

Gallery version (found on Settings page): 
1.2.8.0

Windows 10 version:
- [x] Insider Build (xxxxx)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by chingucoding** [comment]
This behavior also applies to the RichEditBox custom editor sample where the color is not applied when we click anywhere in the text and type.
