### ISSUE TITLE
XAML Controls Gallery (aka XamlUiBasics) Code Snippets Contain Incorrect Syntax

### ISSUE THREAD

**Issue by bolyb** [Microsoft/Xaml-Controls-Gallery#14]
**Describe the bug**

I've run into this a few different places across the XAML Controls Gallery sample app. If you try to copy and paste many of the code snippets from the app, the XAML tags are formatted incorrectly and therefore the sample code taken directly does not actually compile. Take one of the snippets from the TreeView Page as an example:

```csharp
<controls:TreeView ItemsSource="{x:Bind DataSource}"/>
   <TreeView.ItemTemplate/>
      <DataTemplate x:DataType="local:ExplorerItem"/>
         <TreeViewItem ItemsSource="{x:Bind Children}" Content="{x:Bind Name}"/>
      <DataTemplate/>
   <TreeView.ItemTemplate/>
<controls:TreeView/>

// Note the position of the / characters, the correct code snippet should look like this:

<controls:TreeView ItemsSource="{x:Bind DataSource}">
    <TreeView.ItemTemplate>
        <DataTemplate x:DataType="local:ExplorerItem">
            <TreeViewItem ItemsSource="{x:Bind Children}" Content="{x:Bind Name}"/>
        </DataTemplate>
    </TreeView.ItemTemplate>
</controls:TreeView>
```

**Steps to reproduce the bug**

1. Go to the TreeView Page
2. Copy the code snippet
3. Paste the snippet into a new UWP project's MainPage.xaml

**Expected behavior**

The example snippet code should compile.

**Actual behavior**

The example snippet code does not compile. 

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 

1.2.4.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by stmoy** [comment]
Thank you for reporting this! 

There are actually two fixes needed for this particular sample: one is the closed brackets that were originally mentioned, but we also need to prefix the TreeView and TreeViewItem classes with the Microsoft.UI.Xaml.Controls xmlns reference as well.

We strive to make sure our samples are up-to-date and compile'able - if you find other instances with typos, please let us know so we can fix them.

**Comment by bolyb** [comment]
Hi Steven,

Thank you for the quick reply and fix! Just doing a quick scan of other control pages with snippets containing this style typo, the only other places I noticed it were in Compact Sizing, ListView, and ToolTip.

Overall I've found the XAML Controls Gallery to be really useful while developing UWP apps, keep up the great work!

**Comment by stmoy** [comment]
Closing this issue as fixed. Thanks again for bringing it to our attention!

**Comment by dombogetto** [comment]
Hi,
(I'm unfamiliar with GitHub so not sure if I should be posting this in #18 but anyway)
The ComboBox "Colors" also has incorrect closing tags for each color string.

**Comment by YuliKl** [comment]
@dombogetto - thank you for the report, although I'm not seeing the problem with the latest app version. The page I'm looking at specifies
```
<ComboBox SelectionChanged="ColorComboBox_SelectionChanged" Header="Colors" PlaceholderText="Pick a color" Width="200">
    <x:String>Blue</x:String>
    <x:String>Green</x:String>
    <x:String>Red</x:String>
    <x:String>Yellow</x:String>
</ComboBox>
```
Does this still look incorrect to you?

**Comment by dombogetto** [comment]
I have version 1.2.4.0 freshly installed from the store and while what you posted is the correct syntax, I'm still seeing `<x:String>Blue<x:String>`, etc. in my app.
If it matters, I'm running Windows 10 18334.

**Comment by stmoy** [comment]
Thanks for reporting this. The version in the Store hasn't yet been updated with recent fixes which is why it still looks incorrect. We'll be pushing a new version into the Store once we have some other features/fixes implemented.
