### ISSUE TITLE
Fix appearance of the top of the Gallery

### ISSUE THREAD

**Issue by YuliKl** [microsoft/Xaml-Controls-Gallery#141]
**Describe the bug**

There's an unwanted stripe at the top of the app above the hero image. When the fix for [Ability to turn off "TopPadding" in NavigationView](https://github.com/microsoft/microsoft-ui-xaml/issues/47) becomes available in the NuGet package used by the gallery, we should remove this extra whitespace.

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/63060442-23be4a00-bea7-11e9-9023-2574d112744b.png)

**Comment by chingucoding** [comment]
For clarification: We will wait for the fix to be available in the nuget package and we will not try a workaround until then? Or can/should I try finding a bug fix till then?

**Comment by YuliKl** [comment]
@chingucoding, please hold off on doing anything with this issue. I'm actually working on a fix as part of validating the new WinUI feature. I'd love for you to review my PR once it's ready.

**Comment by chingucoding** [comment]
@YuliKl Ah I see! I will be happy to do that :)
