### ISSUE TITLE
Color of text missing after RichEditBox loses focus in dark theme

### ISSUE THREAD

**Issue by chingucoding** [microsoft/Xaml-Controls-Gallery#144]
**Describe the bug**

**This only applies to dark theme**
When the text has been colored using the SplitButton, and the user leaves the RichEditBox (by clicking outside) the text color changes to white (since we are using dark theme). After clicking the box again the color does not change back to the original one (the color chosen using the SplitButton) but instead the text is color black.

**Steps to reproduce the bug**

1. Open SplitButton page (while using dark mode for the whole app or the sample)
2. Select text and color it in any color except black
3. Click outside of RichEditBox
4. Click inside the RichEditBox

**Expected behavior**

The text returns to the previously applied colors

**Actual behavior**

The text is colored black.

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 
1.2.8.0

Windows 10 version:
- [x] Insider Build (18956)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

This applies to the SplitButton page and the RichEditBox page.

**Comment by YuliKl** [comment]
Related: https://github.com/microsoft/microsoft-ui-xaml/issues/142

**Comment by chingucoding** [comment]
@YuliKl Thanks for mentioning that issue. I assume that this behavior is a bug in WinUI and I provided a bug fix in the XCG. 
Should I create an issue over at the main repo or would this bug be a likely "won't fix" ?
