### ISSUE TITLE
Reveal sample on other pages

### ISSUE THREAD

**Issue by chingucoding** [microsoft/Xaml-Controls-Gallery#155]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] New sample
- [x] Addition to existing sample
- [x] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**
Buttonpage, other components with RevealStyle.

**Describe the sample**
Currently the button reveal style/border is only shown on the reveal page. Maybe we should also show the reveal style on the button page so developers who are new to UWP notice the reveal style more easily (since they they might not know that there is a reveal page).

**Is your sample request related to a problem? Please describe it**
While I was trying to fix an issue regarding the ButtonRevealStyle, I wanted to look at how the default button reveal style and did not find it as I forgot there was a separate Reveal page.

**Additional context**

**Comment by kikisaints** [comment]
I like this! I think this could also benefit from having the ButtonAccentStyle also in there/part of that page. Since both the ButtonRevealStyle and ButtonAccentStyles are shipped styles in generic.xaml, it would be nice to call them out specifically.

@chingucoding would you be interested in helping us add this to the gallery?

**Comment by chingucoding** [comment]
> @chingucoding would you be interested in helping us add this to the gallery?

@kikisaints Sure, I would love to help adding this to the gallery!

> I like this! I think this could also benefit from having the ButtonAccentStyle also in there/part of that page. Since both the ButtonRevealStyle and ButtonAccentStyles are shipped styles in generic.xaml, it would be nice to call them out specifically.

I agree that the ButtonAccentStyle could be added too. I have compiled the following list of "new" styles that we should add to the respective sample page:
- AppBarButton
  - AppBarButtonRevealStyle
- AppBarToggleButton
  - AppBarToggleButtonRevealStyle
- Button
  - ButtonRevealStyle
  - ButtonAccentStyle
- DropDownButton
  - DropDownButtonRevealStyle (when available WinUI Nuget package)
- RepeatButton
  - RepeatButtonRevealStyle
- SplitButton
  - SplitButtonRevealStyle (when available in WinUI Nuget package)
- ToggleButton
  - ToggleButtonRevealStyle

@kikisaints Are there any components/styles missing?
