### ISSUE TITLE
Split button isn't getting activated with caps+enter.

### ISSUE THREAD

**Issue by YuliKl** [microsoft/Xaml-Controls-Gallery#164]
**Describe the bug**

**Steps to reproduce the bug**

1. Launch XAML Controls Gallery.
2. Activate Split button from All controls page.
3. Navigate to "Font color" split button present in the page and press caps+enter to activate it.

**Expected behavior**

The primary activation command with the narrator to activate a button is caps+enter. Hence a split button should get activated with caps+enter.

**Actual behavior**

The split button isn't getting activated with caps+enter.

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/63800345-c670c280-c8c2-11e9-95ff-0abfdc9437e8.png)

Observation: Toggle split button gets activated with caps+enter successfully.

User Impact: Visually impaired users will be affected as a basic command to activate split button isn't working

**Version Info**

Gallery version (found on Settings page): 

App Version: 1.2.9.0

Windows 10 version:
- [x] Insider Build (xxxxx)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

Copied from [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/23304229/)

**Comment by chingucoding** [comment]
Using narrator, hitting caps+enter does trigger the click method of the button. 

However there seems to be now way to open the flyout of a (Toggle)SplitButton using keyboard shortcuts (at least not without adding one). 
I think this is a spec-issue as there also is an [issue](https://github.com/microsoft/microsoft-ui-xaml/issues/1207) over at WinUI regarding the buttons behaviour with touch.

**Comment by chingucoding** [comment]
Upon further investigation, I noticed that the SplitButton does trigger the correct events, the "Clicked" effect is just not visually present.

I noticed that the SplitButton is not really intuitive to use (user has to select text before pressing the button makes a difference). 
@YuliKl Should we modify the example to be a bit more intuitive to use?

**Comment by YuliKl** [comment]
While I'm definitely open to ideas about how to change this sample, this may just be a bug that we need to resolve as "Won't Fix".

**Comment by YuliKl** [comment]
Closing as I don't think we have any ideas for how to correct this problem.
