### ISSUE TITLE
Nested UI is present in GridView.

### ISSUE THREAD

**Issue by YuliKl** [microsoft/Xaml-Controls-Gallery#168]
**Describe the bug**

**Pre-requisite:** 
Turn on Narrator
Set Narrator in Item Mode.

**Steps to reproduce the bug**

1. Launch XAML Controls Gallery.
2. Navigate to GridView in all controls and activate it.
3. Navigate to "Content inside of a GridView" and observe narrator focus.

**Expected behavior**

Narrator's focus should directly go to the item1 to item2.

**Actual behavior**

Nested UI element is present and it takes more than 1 step to go to item1 to item2.

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/63801259-b954d300-c8c4-11e9-81e8-8e36dda2d60b.png)

**Version Info**

Gallery version (found on Settings page): 

Version Info : 1.2.6.0

Windows 10 version:
- [x] Insider Build (xxxxx)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

Copied from [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/20919543)

**Comment by chingucoding** [comment]
This behavior is only present when setting the "AutomationProperties.Name" property on the items. I think this is a problem with the way AutomationProperties works.
I've tried listening to focus events but those do not get triggered in that scenario. 
@YuliKl Could this be an external bug?

**Comment by chingucoding** [comment]
I have looked into it again and thanks to your input (forgot that AutomationProperties.AccessibilityView could help) I found a workaround.
