### ISSUE TITLE
Compact Sizing example doesn't work

### ISSUE THREAD

**Issue by deanchalk** [microsoft/Xaml-Controls-Gallery#20]
**Describe the bug**

In the 'styles' part of the sample app, there is a 'Compact Sizing' page to demonstrate the much awaited desktop-density UI promised by Microsoft in May this year. However, it doesn't work. Text is clipped in the boxes and everything looks wrong. When you look at the resource dictionary there's nothing really of value there, so this hasn't really been done in any meaningful way. Is this something that Microsoft is working on? or is this something that the community is expected to pick up? If it is the latter, then I might be tempted to have a go. Just looking for clarification.

**Steps to reproduce the bug**

**Expected behavior**

**Actual behavior**

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [ ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by licanhua** [comment]
@deanchalk, What's your windows version when you reproduce the problem? I guess it's below 17763

**Comment by deanchalk** [comment]
Nope. Version 17763.195
But that's beside the point, this feature has not been implemented. Is Microsoft doing this? or are they waiting for the community to pick this up?

**Comment by licanhua** [comment]
I'm using 17763.195 too, but I didn't see your problem. Have you try to install Xaml Controls Gallery from store?

If you want to play with 'Compact', I suggest you to integrate [microsoft.ui.xaml](https://github.com/Microsoft/microsoft-ui-xaml) to your project.

I have to say not all of 'compact size' are delivered on 17763. You can think we have three phases for this:
1. 'Compact Size' for RS5 and late os.
2. Flexible 'compact'(eg: half size) and 'Compact Size' downlevel, for example, to 15063. This job is done by [microsoft.ui.xaml](https://github.com/Microsoft/microsoft-ui-xaml). You need to use MUX and you can see examples like [CommonStylesPage](https://github.com/Microsoft/microsoft-ui-xaml/blob/master/dev/CommonStyles/TestUI/CommonStylesPage.xaml) 
3. Some leftover like fontsize change and Simple way to apply 'Compact Size' on your project.

phase1 is delivered on 17763 os. You buy it for free. If you create a app and run on both 17763 and old os, you may see the difference. 
phase2 is delivered on microsoft-ui-xaml, you may need to  use MUX
Both phase1 and phase2 require you to implement your own dictionary if you want to customize the 'compact' level. just like [CompactDictionary](https://github.com/Microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/ControlPages/CompactDictionary.xaml) and things defined in <Grid.Resources> in [CommonStylesPage](https://github.com/Microsoft/microsoft-ui-xaml/blob/master/dev/CommonStyles/TestUI/CommonStylesPage.xaml). You need to manually redefine some keys to achieve the any compact size.

phase2 and phase3 requires you to use Microsoft.UI.XAML.
phase3 is not in scope yet, you may/may not see proposal on [issue page](https://github.com/Microsoft/microsoft-ui-xaml/issues) in the future.

**Comment by stmoy** [comment]
Hi Dean, thank you for reaching out!

As CanHua mentions, this feature is still in active development which is why the page is marked as "Preview" in the Gallery. As more of the feature comes online, we plan on expanding the Compact Sizing page and pulling it out of the "Preview" stage. To that end, both the feature and the sample are in development by the team at Microsoft. 

If there are any particular controls that you're interested in seeing the compact size for, please let us know so we can include them in the sample!

For now, we will use this issue to track updating the sample page in the Gallery.

**Comment by deanchalk** [comment]
@stmoy thanks for the update. Can you clarify something - is this 'Compact' sizing feature only going to be delivered via a ResourceDictionary? Or will there be other 'deeper' changes in the platform to support this?
Thanks

**Comment by stmoy** [comment]
@deanchalk - There has been some discussion about the best way to expose Compact sizing to apps. Right now it is exposed as a ResourceDictionary, but the exact mechanism/API is being discussed over on the main WinUI repo here: https://github.com/Microsoft/microsoft-ui-xaml/issues/98

**Comment by LucasHaines** [comment]
@deanchalk not sure if your question was answered directly. We are planning to create the resource dictionary and share via the WinUI repo.

**Comment by deanchalk** [comment]
@LucasHaines - thanks, thats perfect :)

**Comment by chingucoding** [comment]
Is this issue still up to date? The issue linked by @stmoy at microsoft/microsoft-ui-xaml has been closed. So is there anything that should be done over at Xaml Controls Gallery ? Otherwise I suggest closing this issue ^^

**Comment by LucasHaines** [comment]
This should be resolved or closed now we shipped compact spacing in WinUI2.1 and the sample has been updated and working as expected. I'll wait a few days before I close this issue to see if anyone else has a repro for the bug.

**Comment by chingucoding** [comment]
@LucasHaines Reminder to close this 😅

**Comment by LucasHaines** [comment]
this has been resolved and forgot to close this :)
