### ISSUE TITLE
MediaPlayerElement page crashes 

### ISSUE THREAD

**Issue by stmoy** [microsoft/Xaml-Controls-Gallery#211]
**Describe the bug**

Choosing the MediaPlayerElement page crashes

**Steps to reproduce the bug**

1. Launch the Gallery
1. Go to Media category
1. Click on MediaPlayerElement

**Expected behavior**

Crash :(

**Actual behavior**

No crash :)

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 

Windows 10 version:
- [x] Insider Build (xxxxx)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

It looks like the crash occurs in the ImageLoader class. 

Why is ImageLoader looking for the animations.png in the first place? 
![image](https://user-images.githubusercontent.com/25991996/65627396-258a2b80-df84-11e9-81b1-a1553633259c.png)

**Comment by YuliKl** [comment]
This appears to be a very recent break. I had to pull master to repro, so this issue was introduced in the last week (at the most).
