### ISSUE TITLE
Update Media UITest to point to MediaPlayerElement

### ISSUE THREAD

**Issue by stmoy** [microsoft/Xaml-Controls-Gallery#212]
**Describe the bug**

We "docprecated" (removed) the MediaElement page. The Media test is therefore failing. We need to update the UI test to point at the MediaPlayerElement page instead. 

~~Note that this is blocked on #211~~ (Fixed)

**Version Info**

Gallery version (found on Settings page): 

WinUI 2.2, Gallery version 1.2.9+

**Additional context**

**Comment by chingucoding** [comment]
@hassanuz #211 is fixed now :)

**Comment by stmoy** [comment]
Thanks @chingucoding - updated the bug text above.

**Comment by chingucoding** [comment]
I think this issue was addressed with #224 and can be closed now. 😅

**Comment by stmoy** [comment]
Good catch, thanks @chingucoding !
