### ISSUE TITLE
NavigationView width-based pane orientation sample behavior is bugged.

### ISSUE THREAD

**Issue by kmgallahan** [microsoft/Xaml-Controls-Gallery#218]
**Describe the bug**
When the initial window width is great enough that the sample view area stops expanding, the NavigationView displays at the top with an empty left panel.

**Steps to reproduce the bug**
1. Open the XAML Controls Gallery
2. Navigate to the NavigationView samples
3. Increase the window width until the sample area stops expanding
4. Navigate away and back again
5. Observe the "NavigationView that switches pane orientations based on window width" sample

**Expected behavior**
The NavigationView menu should appear expanded on the left only.

**Actual behavior**
The NavigationView displays at the top with an empty left panel.

**Screenshots**
![Annotation 2019-10-05 143721](https://user-images.githubusercontent.com/5379488/66259324-a95ec780-e77d-11e9-827a-8df14f1472c4.png)

**Version Info**

Gallery version (found on Settings page): 
1.2.10.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [X] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by YuliKl** [comment]
@kmgallahan, thank you for the bug report!
