### ISSUE TITLE
Markup sample for "A MenuFlyout with options" doesn't match control

### ISSUE THREAD

**Issue by YuliKl** [microsoft/Xaml-Controls-Gallery#226]
**Describe the bug**

The markup sample
![image](https://user-images.githubusercontent.com/13142665/66951957-6d92f000-f010-11e9-8035-47cba5803857.png)

doesn't actually match the menu
![image](https://user-images.githubusercontent.com/13142665/66952003-86030a80-f010-11e9-875f-77398a80499b.png)

The Copy and Delete menu items have icons not represented in the sample code. 

**Steps to reproduce the bug**

1. Go to MenuFlyout page
2. Scroll down to A MenuFlyout with Icons

**Comment by chingucoding** [comment]
This is also the case for the sample "A MenuFlyout with Icons and Keyboard Accelerators".
