### ISSUE TITLE
ToggleSplitButton, SplitButton, and DropDownButton controls should have shadow applied consistently

### ISSUE THREAD

**Issue by chigy** [microsoft/Xaml-Controls-Gallery#23]
**Describe the bug**
ToggleSplitButton, SplitButtion, and DropDownButton all behaves and looks very similar. However if you go to XCL, only DropDownButton gets shadow treatment.

**Steps to reproduce the bug**
1. Go to 'DropDownButton' control
2. Click on the button
3. Do the same for ToggleSplitButton and SplitButton

**Expected behavior**
All 3 controls (ToggleSplitButton, SplitButtion, and DropDownButton) gets shadow on the flyout UI element.

**Actual behavior**
Only DropDownButton flyout UI element gets shadow

**Version Info**
I've installed gallery from Store (RS5 version). Insider build 18309.rs_prelelease.181220-1256

**Additional context**
This is by design of the shadow implementation. Due to the complexity of supporting flyout, flyout does not turn on shadow on older builds (so shadow will work on 19H1 version).

Suggested fix are two folds:
1. Use MenuFlyout instead of Flyout for the flyout UI element of the buttons here if the design allows it.
2. Apply IsShadowEnabled property that we added to enable just this into the control gallery sample code.

**Comment by adambarlow** [comment]
@chigy 
Is it true then, that this works correctly on 19H1+? If that is the case then would we be okay with a won't fix here?

If we do #2 that would fix it in the sample gallery but all RS5 Splitbuttons wouldn't get correct shadows out of the box, correct?

**Comment by chigy** [comment]
@adambarlow , no I'd like the sample to provide the right guidance for everyone, especially non 19H1 customers which will be our main audience. If we do option 2, it should be no-op for 19H1 (so doing #2 should fix for all versions).

**Comment by stmoy** [comment]
@chigy - just to verify, the guidance for non-19H1 customers is to not see shadows? If so, this should be a fairly straightforward fix using conditional XAML or doing an API contract check in codebehind.

**Comment by chigy** [comment]
@stmoy - apologies if I confused you all. We want shadow on all versions. Flyout defaults to not have shadow on older SDK to avoid bugs caused by custom visuals that are not rectangular (think of beaks). By setting the API to have shadow ON for all versions, the issue should be fixed for all versions.

**Comment by chingucoding** [comment]
> 1. Use MenuFlyout instead of Flyout for the flyout UI element of the buttons here if the design allows it.

I've tried using the MenuFlyout instead of Flyout and it did not draw a shadow on machine running Windows Version 17763 (last version before 19H1 I believe). Is this expected ?
> 2. Apply IsShadowEnabled property that we added to enable just this into the control gallery sample code.

I tried doing this, but I could not find a "IsShadowEnabled" property. The only thing related I could find was the "IsDefaultShadowEnabled" (see [this file](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/CalendarDatePicker/CalendarDatePicker_themeresources.xaml#L187)), however that flag did not work on Windows build version 17763. 
In addition to this, the flag required the UniversalApiContract Version 8, which is for [Windows build version 18362](https://docs.microsoft.com/en-us/uwp/extension-sdks/windows-universal-sdk#version-100183620) (19H1+). 
Am I missing something or is it not possible to enable shadows for (Menu)Flyouts on Windows build version 17763?

**Comment by chigy** [comment]
> > 1. Use MenuFlyout instead of Flyout for the flyout UI element of the buttons here if the design allows it.
> 
> I've tried using the MenuFlyout instead of Flyout and it did not draw a shadow on machine running Windows Version 17763 (last version before 19H1 I believe). Is this expected ?
> 

Yes, shadows will only appear when the app is ran on an OS that supports shadow which is 19H1 and newer.

> > 2. Apply IsShadowEnabled property that we added to enable just this into the control gallery sample code.
> 
> I tried doing this, but I could not find a "IsShadowEnabled" property. The only thing related I could find was the "IsDefaultShadowEnabled" 

Yes, that was typo. 

> however that flag did not work on Windows build version 17763.

Yes, it is expected as per above answer.

> In addition to this, the flag required the UniversalApiContract Version 8, which is for [Windows build version 18362](https://docs.microsoft.com/en-us/uwp/extension-sdks/windows-universal-sdk#version-100183620) (19H1+).
> Am I missing something or is it not possible to enable shadows for (Menu)Flyouts on Windows build version 17763?

That is correct.

**Comment by chingucoding** [comment]
Ah okay , I see. I'll create a PR today to add the flag to components. Are there any other components except those three that Need this flag?

**Comment by chigy** [comment]
No, these should be it. Thanks, @chingucoding !

**Comment by YuliKl** [comment]
We had an internal discussion and concluded that this issue is no longer relevant. Fixing this issue would have been helpful when the Gallery was targeting Windows version 17763. Because the app is now targeting a later SDK, this temporary fix is not needed.

Closing the issue.

**Comment by chigy** [comment]
@chingucoding , thank you so much for your contribution! This was a lesson at least for me to keep the issues list up-to-date in case a great contributor like yourself help us out. I really appreciate and sorry we couldn't take your change...

**Comment by chingucoding** [comment]
@chigy No problem. Happy to help and I am glad that this issue was resolved :)
