### ISSUE TITLE
The vertical slider sample looks too short

### ISSUE THREAD

**Issue by YuliKl** [microsoft/Xaml-Controls-Gallery#232]
**Describe the bug**

That's a rather unimpressive vertical slider.
![image](https://user-images.githubusercontent.com/13142665/67737232-a2675580-f9c7-11e9-9420-b79d5af49073.png)

**Expected behavior**

This slider should be taller.

**Version Info**

Gallery version (found on Settings page): 

1.2.10.0

**Comment by stmoy** [comment]
Please do not slider shame. That lil guy gets the job done.

(I wonder if this is a regression?)

**Comment by mdtauk** [comment]
> Please do not slider shame. That lil guy gets the job done.
> 
> (I wonder if this is a regression?)

More likely it looks even shorter now the Thumb is a circle, and not a lozenge.

**Comment by salmanmkc** [comment]
Fixed the issue with that PR
