### ISSUE TITLE
MenuBar sample should show what was invoked

### ISSUE THREAD

**Issue by MikeHillberg** [microsoft/Xaml-Controls-Gallery#258]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] New sample
- [x] Addition to existing sample
- [ ] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**
MenuBar

**Describe the sample**

Some of the samples, like MenuFlyout and AppBarButton, show you when you invoke a button. For example in CommandBarFlyout when you invoke Resize the sample updates to say "You clicked: Resize".

It would help for the MenuBar sample to do this too, especially the sample with keyboard accelerators, so ex you could see that Control+S does something.

**Is your sample request related to a problem? Please describe it**

**Additional context**

**Comment by salmanmkc** [comment]
I'm handling this

**Comment by salmanmkc** [comment]
That fixes it for you, would you like to test and see if that's what you want?

**Comment by salmanmkc** [comment]
https://github.com/microsoft/Xaml-Controls-Gallery/pull/305 and https://github.com/microsoft/Xaml-Controls-Gallery/pull/306 done to address the issue above.
