### ISSUE TITLE
App Sidebar flickering

### ISSUE THREAD

**Issue by DJDaemonix** [microsoft/Xaml-Controls-Gallery#261]
**Describe the bug**
The Sidebar is flickering, when mouse hovers over its elements. Any kind of UI refresh on the sidebar will cause it to flicker in erratic patterns.

**Steps to reproduce the bug**
1. Launch the App
2. Hover mouse over / Use Sidebar

**Expected behavior**
UI working as intended.

**Actual behavior**
Sidebar flickers.

**Screenshots**
A screenshot cannot do it justice. Here is a video demonstrating the problem : https://photos.app.goo.gl/Xq2ERTpy8aK5Dcg38

**Version Info**
Gallery version (found on Settings page): 
1.2.10

Windows 10 version:
- [x] Insider Build (xxxxx)
- [x] May 2019 Update (18363)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**
Problem has also been sighted on my Surface Book 2 (running a different, Insider version), on same app version.

**Comment by stmoy** [comment]
Hi @DJDaemonix - thank you for reporting this issue and for including a video. We haven't seen this issue before in the Gallery, so we will need your help to get to the bottom of it. To help diagnose the issue, can you please try the following?

- Does this issue happen on other pages? Specifically, I'm curious if the issue happens on the ListView, GridView, TreeView, and/or Reveal pages.
- Can you try grabbing a video with the Game Bar? To do so, press Win+G to bring up the Game Bar and press the Record button. (You might also be able to hit Win+Alt+R to immediately start a recording)
- When the Xaml Controls Gallery is in this erratic state, do you see the issue manifest anywhere else on your system? Specifically I'm curious if it happens in the Calculator app.

My guess is that this has something to do with the Reveal Highlight effect, but hopefully we'll be able to know a bit more with the answers to the above questions.

**Comment by DJDaemonix** [comment]
> Hi @DJDaemonix - thank you for reporting this issue and for including a video. We haven't seen this issue before in the Gallery, so we will need your help to get to the bottom of it. To help diagnose the issue, can you please try the following?

I can shed some light into the matter :

 - Issue happens on all pages indiscriminately. Tested all 3 pages, and got same results.
 - Where things get weirder, I cannot video this issue through the Game Bar or even OBS, as the issue does not seem to show over the recordings. Discord Screencap is also ignorant of the issue (tried that out of desperation).
 - Issue does not manifest on Calculator app, nor any other UWP app. Where it does get interesting is when the focus is taken off the XAML CG app. The issue simply goes away, and no more flickering occurs on the Sidebar. That is, of course, until you go back to XAML GC, where the issue comes back once more. Rinse and repeat.

Thanks for your help, and prompt reply.

**Comment by salmanmkc** [comment]
Hi, I believe this was an issue with the Insider Build, I was having many visual issues with my computer when on the Insider Build and completely reinstalled Windows using the Media Creation Tool, and most of the issues seem to be gone. By any chance @DJDaemonix are you running an AMD GPU? Because the latest slow ring Insider Builds that I tried on this computer had no AMD Drivers that were supported, which I assume lead to the flickering.

**Comment by DJDaemonix** [comment]
@salmanmkc Good assumption. However, while one of the PCs tested is indeed on Insider builds, my main PC is running on v1909, which I believe is a Release build. Do correct me if i'm wrong.

As far as the AMG GPU path goes, the only thing in my system coming from AMD is my proud Ryzen 1700X processor. As these have no iGPU whatsoever (very fun (NOT!) to diagnose when it black-screens), my GPU is a 1080 Ti. Therefore, I believe we've exhausted the Bad Driver path.

**Comment by salmanmkc** [comment]
> @salmanmkc Good assumption. However, while one of the PCs tested is indeed on Insider builds, my main PC is running on v1909, which I believe is a Release build. Do correct me if i'm wrong.
> 
> As far as the AMG GPU path goes, the only thing in my system coming from AMD is my proud Ryzen 1700X processor. As these have no iGPU whatsoever (very fun (NOT!) to diagnose when it black-screens), my GPU is a 1080 Ti. Therefore, I believe we've exhausted the Bad Driver path.

Actually the issue has come back for me, not sure if I remember it happening on a normal build instead of a debug build, some other visual glitches as well.

**Comment by DJDaemonix** [comment]
Time for more news. Aside from the eye-watering lack of change on the problem (good thing i'm not epileptic), it seems the issue has proliferated to the W10 Phone Companion app, which, 3 days ago, worked just fine, without any issue in sight. Same problem, sidebar flickers.

I'm beginning to think the issue is beyond the scope of this app, and more to do with W10 itself.

**Comment by stmoy** [comment]
@DJDaemonix - thank you for the updates. Based on the details you provided (namely that this doesn't repro using the Gamebar and that it is happening in other apps) leads me to believe that this is an underlying rendering issue. 

I'm routing this to the correct team internally. Please sit tight - I haven't forgotten about this issue 😅

**Comment by DJDaemonix** [comment]
> @DJDaemonix - thank you for the updates. Based on the details you provided (namely that this doesn't repro using the Gamebar and that it is happening in other apps) leads me to believe that this is an underlying rendering issue.
> 
> I'm routing this to the correct team internally. Please sit tight - I haven't forgotten about this issue 😅

Glad I could help ! Probably one of the few times I report bugs instead of creating some myself, so I hope it went smooth enough ^^||
Do keep me/us updated with the bugfixing progress if possible :)

**Comment by stmoy** [comment]
Hi @DJDaemonix, thanks again for filing this issue. We're tracking this bug internally. One of our partner teams (working on the underlying W10 rendering stack) are taking a look at this issue. Since we're tracking the bug internally and since this isn't an issue with the Gallery itself, I'm going to close the issue. 

Double checking: are you still seeing this issue?

We will be sure to reach out if we need more information (such as a DxDiag trace).

**Comment by DJDaemonix** [comment]
One of my two computers (running on latest Insider) seems to no longer be affected by the issue. I suspect a fix is to be deployed soon for general availability...

I'd like to thank each and every one of you for your prompt reaction, and implication, on this issue.
