### ISSUE TITLE
WinUI 3 alpha - Gallery App - What's New header issue

### ISSUE THREAD

**Issue by mdtauk** [microsoft/Xaml-Controls-Gallery#268]
**Describe the bug**
On the home page of the Gallery App, when you scroll down, the "What's New" text is rendered on top of elements once the header is scrolled off screen

**Steps to reproduce the bug**
- Open XAML Controls Gallery (WinUI 3 Alpha)
- Scroll down

**Expected behavior**
The "What's New" header text should be contained within the Header as it scrolls out of view.  Or the heading should be "stickied" to the top of the screen, and it's foreground colour changed to be readable on the background colour.

**Screenshots**
![image](https://user-images.githubusercontent.com/7389110/68862880-274fb000-06e6-11ea-9e4d-b0492058d6bd.png)

![image](https://user-images.githubusercontent.com/7389110/68862868-228afc00-06e6-11ea-95b4-06461268778e.png)

**Version Info**
1.2.16.0

NuGet package version: 
WinUI 3 Alpha

**Comment by mdtauk** [comment]
I see the header has been fixed, in that it shrinks down and remains sticky at the top when scrolling.

However the alignment of the left margin is now incorrect.

![image](https://user-images.githubusercontent.com/7389110/70846769-94c13e80-1e54-11ea-9d5a-e11885d52e20.png)

**Comment by gregwoo-microsoft** [comment]
This has been fixed. Closing it now. Thanks @mdtauk for filing this :)
