### ISSUE TITLE
Disable TabView tearout sample on Win10 versions < 18362

### ISSUE THREAD

**Issue by nCastle1** [microsoft/Xaml-Controls-Gallery#282]
In the tab view sample with a second window, dragging and dropping a tab onto the title bar area crashes the entire app. Also, dragging and dropping a tab outside the window crashes the entire app. 

1. Launch the tab view sample
2. Scroll to the bottom and launch the full sample.
3. Try dragging a tab onto the title bar area or try to create a new window

**Expected behavior**

The app shouldn't crash; a new window should be created.

**Actual behavior**

The app crashes.

**Screenshots**

![XxWHO2dmEW](https://user-images.githubusercontent.com/29742178/70167015-b105f400-167a-11ea-9e9a-54ebb2fe117c.gif)

**Version Info**
Gallery version (found on Settings page): 1.2.11.0

Windows 10 version:
- [x] October 2018 Update (17763)

Device form factor:
- [x] Desktop

**Comment by stmoy** [comment]
Thank you for reporting this issue. I'm not able to reproduce the issue (on Win10 version 19035), so we'll need to do a little bit of debugging. 

Is this version of the Gallery the one found on the Store? Or is a version that you've built and run locally in Visual Studio? 

CC: @teaP for FYI

**Comment by nCastle1** [comment]
I got it through the store

**Comment by stmoy** [comment]
Since I'm not able to reproduce the issue locally, we will need your help gathering more information. 

The most expedient way to gather this information is likely to attach a debugger. Do you have Visual Studio installed? If you clone the repo and run the sample under a debugger, do you still see the crash?

I know installing VS/cloning/building/running/debugging can take up a bunch of time so if you're unable to do these steps, I understand. Another option might be finding the crash dump through Store telemetry, though I've had limited success with this method.

**Comment by nCastle1** [comment]
@stmoy 

Exception details:

```
System.TypeLoadException
  HResult=0x80131522
  Message=Requested Windows Runtime type 'Windows.UI.WindowManagement.AppWindow' is not registered.
  Source=System.Private.CoreLib
  StackTrace:
   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at Windows.UI.WindowManagement.AppWindow.TryCreateAsync()
   at AppUIBasics.TabViewPages.TabViewWindowingSamplePage.<Tabs_TabDroppedOutside>d__8.MoveNext() in C:\Users\nath9278\Documents\Dev\Xaml-Controls-Gallery\XamlControlsGallery\TabViewPages\TabViewWindowingSamplePage.xaml.cs:line 125

Inner Exception 1:
COMException: Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))

**Comment by stmoy** [comment]
@nCastle1 - you rock. Thank you for providing this info. I had a suspicion that it was related to AppWindow. Let me sync with some folks internally to see if they have any insight. 

My guess is that AppWindow might not be present on Win10 version 17763.

**Comment by stmoy** [comment]
After a bit more digging, it looks like AppWindow isn't supported on 17763. [AppWindow API Docs](https://docs.microsoft.com/en-us/uwp/api/windows.ui.windowmanagement.appwindow)

It looks like it was introduced in 18362. I've updated the title of this bug to reflect that we should disable the "tear out" behavior on Win10 versions < 18362.
