### ISSUE TITLE
App crashes on activating "Paste" from the context menu in SplitButton

### ISSUE THREAD

**Issue by YuliKl** [microsoft/Xaml-Controls-Gallery#286]
**Describe the bug**

**Steps to reproduce the bug**

1. Launch XAML Control Gallery app.
2. Navigate to "SplitButton" in All controls and activate it.
3. In the textbox, select the text written and right click to invoke the context menu and select "Cut" menu item.
4. Again invoke the context menu and activate "Paste" menu item and observe.

**Expected behavior**

On activating "Cut" menu item, the texts should be cleared and again on activating Paste menu item the texts should get pasted in the textbox.

**Actual behavior**

On activating "Cut" menu item, the texts are not getting cleared and on activating Paste menu item, the App crashes.

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/70364795-e8270180-1842-11ea-896a-98f5f8f364ad.png)

**Version Info**

Gallery version (found on Settings page): 

1.2.11.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

Copied from [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/24258107)

A brief dev investigation showed that the crash is occurring in SplitButtonPage.MyRichEditBox_GotFocus.

**Comment by chingucoding** [comment]
Hmm ...  I think this is related to the fact that upon focus change we do some text manipulation to combat the RichEditBox removing the colors on dark theme when changing focus.

I will look into this if its fine.
