### ISSUE TITLE
This code block text may be confusing for beginners

### ISSUE THREAD

**Issue by HikariXu** [microsoft/Xaml-Controls-Gallery#287]
**Describe the bug**

the text block should be put into a Grid. If just paste code block, the items will be at the left side of the app window, but it placed at the top. I couldn't figure it out until I checked the XAML Controls Gallery source code of the page. Then I found it must be put inside a Grid, or it won't function properly. The code block given in the attached screenshoot is confusing.
By the way, XAML Controls Gallery is really nice for beginners like me. Thanks!

**Steps to reproduce the bug**

**Expected behavior**

**Actual behavior**

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [ ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

![image](https://user-images.githubusercontent.com/45059926/70374768-8396a000-1931-11ea-9ddd-abc65190f6aa.png)

**Comment by chingucoding** [comment]
What exactly do you mean by "the items will be at the left side of the app window" ? 😅

I tested this in a local project, by just pasting the snippet into an empty page (without a grid) and the NavigationView displayed the navigation at the top of the window, which I would expect to happen.

**Comment by HikariXu** [comment]
> What exactly do you mean by "the items will be at the left side of the app window" ? 😅
> 
> I tested this in a local project, by just pasting the snippet into an empty page (without a grid) and the NavigationView displayed the navigation at the top of the window, which I would expect to happen.
Ops, sorry. I gave the wrong picture. It's the third one, I just mixed them up. Here is the screenshoots:
No Grid:
![image](https://user-images.githubusercontent.com/45059926/70399907-b2606380-1a62-11ea-8308-24060e23414e.png)
In a Grid:
![image](https://user-images.githubusercontent.com/45059926/70399952-f5223b80-1a62-11ea-9f84-323b2874d85c.png)

**Comment by HikariXu** [comment]
> What exactly do you mean by "the items will be at the left side of the app window" ? 😅
> 
> I tested this in a local project, by just pasting the snippet into an empty page (without a grid) and the NavigationView displayed the navigation at the top of the window, which I would expect to happen.

Ops, sorry. I gave the wrong picture. It's the third one, I just mixed them up. Here is the screenshoots:
No Grid:
![image](https://user-images.githubusercontent.com/45059926/70399907-b2606380-1a62-11ea-8308-24060e23414e.png)
In a Grid:
![image](https://user-images.githubusercontent.com/45059926/70399952-f5223b80-1a62-11ea-9f84-323b2874d85c.png)
