### ISSUE TITLE
CopyWin32Resources failed with exit code 300

### ISSUE THREAD

**Issue by LeftTwixWand** [microsoft/Xaml-Controls-Gallery#289]
CopyWin32Resources failed with exit code 300
I have last license version of windows and download last version of controls gallery.

**Comment by stmoy** [comment]
Thank you for reopening this issue using the bug template.

**Comment by LeftTwixWand** [comment]
> Thank you for reopening this issue using the bug template.
Hi, Steven. Can i chat with you?

**Comment by stmoy** [comment]
Happy to chat, but lets chat over on #290.
