### ISSUE TITLE
CopyWin32Resources failed with exit code 300

### ISSUE THREAD

**Issue by LeftTwixWand** [microsoft/Xaml-Controls-Gallery#290]
**Describe the bug**
Debug crashes with error "CopyWin32Resources failed with exit code 300"

**Steps to reproduce the bug**
1. Go to Project -> Maneger NuGet packages
2. Update all installed packages
3. Clear solution
4. Build 
5. If it not working, try to change debug configuration to x86 or x64 
6. Clear solution again 
7. Start 

**Expected behavior**
Debugging crash

**Actual behavior**
Debugging crash

**Screenshots**

**Version Info**
Windows 10 Version 1903 for x64 (KB4522741)

**Gallery version**  
Version 1.2.9.0] 

Windows 10 version:
- [X] Insider Build (1903)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by LeftTwixWand** [comment]
Last week I started my first project at UWP - the messenger. There are no problems with C # code, but before that I had not worked with XAML markup. What can you recommend for understanding this?

**Comment by YuliKl** [comment]
@LeftTwixWand have you looked through the resources available at https://docs.microsoft.com/windows/uwp/get-started/?

**Comment by LeftTwixWand** [comment]
> @LeftTwixWand have you looked through the resources available at https://docs.microsoft.com/windows/uwp/get-started/?

Yes, I saw that, but there are many questions. Maybe there are any courses, with show how to work with XAML on practice. Or some book.

**Comment by YuliKl** [comment]
Perhaps https://channel9.msdn.com/Series/Windows-10-development-for-absolute-beginners/UWP-001-Series-Introduction will be helpful.

**Comment by LeftTwixWand** [comment]
Oh thanks, this is what I was looking for.

**Comment by diana200** [comment]
You must mark the application to install from scratch, not to copy only what was modified. And it will build and run with no errors.
