### ISSUE TITLE
Add InkToolbar Sample

### ISSUE THREAD

**Issue by stmoy** [microsoft/Xaml-Controls-Gallery#297]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [x] New sample
- [ ] Addition to existing sample
- [ ] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**

**Describe the sample**

InkToolbar is a control that contains a customizable and extensible collection of buttons that activate ink-related features relative to an InkCanvas. We have an InkCanvas sample, but no associated InkToolbar sample

**Is your sample request related to a problem? Please describe it**

Referenced by #296 

**Additional context**

**Comment by yaichenbaum** [comment]
I don't know of any content I would like to see in particular, I remember that a year or two ago this page was there so I would imagine something similar.

**Comment by yaichenbaum** [comment]
Thank you so much! I really appreciate the swift action to resolve this issue!
