### ISSUE TITLE
CommandBar sample Settings button should have a command

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/Xaml-Controls-Gallery#301]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [x] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**
CommandBar, similar request to #258 

**Is your sample request related to a problem? Please describe it**
The example shows a keyboard accelerator for the Settings command (which is hidden in the secondary commands).  However, if you hit 'Ctrl+S' on the sample page, you don't know if it worked, as the button doesn't do anything.

The button should have an action associated to it to show the user that it's been enacted and how the keyboard accelerator code works. 

**Additional context**
Maybe the short-cut for 'Settings' shouldn't be Ctrl+S in the example as that's usually 'Save' in most applications? Opening the Settings app is 'Win+I', so maybe we use 'Ctrl+I' in the sample?

**Comment by salmanmkc** [comment]
I just changed the keyboard accelerator, I agree with what you mentioned where you would use CTRL+S for saving and Win+I for settings.

As for the functionality, I'm not sure for this example but it doesn't seem like there needs to be an indicator that the button was pressed, but I can build that in as a separate PR.

**Comment by salmanmkc** [comment]
There, that addresses the main issue you mentioned.
