### ISSUE TITLE
Cannot create instance of type 'Microsoft.UI.Xaml.Controls.XamlControlsResources' [Line: 22 Position: 40] in App.g.i.cs

### ISSUE THREAD

**Issue by vlad-gregor** [microsoft/Xaml-Controls-Gallery#308]
**Bug Description:**
After downloading the sample, I try to run it with VS 2017 v. 15.9.18 in debug mode on x64 platform (Local machine). The debugger breaks in App.g.i.cs on line 53:

`if (global::System.Diagnostics.Debugger.IsAttached) global::System.Diagnostics.Debugger.Break();`

From the debugger watch I see, that this is  Windows.UI.Xaml.Markup.XamlParseException. The exception message says:
Cannot create instance of type 'Microsoft.UI.Xaml.Controls.XamlControlsResources' [Line: 22 Position: 40]

Exception sender is AppUIBasics.App. After taking a look at the XAML code of this code module on line 22, I see that this line of code:
`<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls"/>`
tries to instantiate "XamlControlsResources" which cannot be found. 

However, when I go to NuGet Package manager, I see, that I do have Microsoft.UI.Xaml installed - version 2.3.191211002.

**Steps to reproduce the bug**
Just downloaded the source, opened in VS 2017 and hit F5 with "Debug" build configuration, "x64" platform (Local machine).

**Expected behavior**
Do not throw an exception.

**Actual behavior**
An exception is thrown.

**Screenshots**

**Version Info**

I run Win 10 Pro, v. 1909

Gallery version (found on Settings page): 
I'm not sure what a gallery is.

Windows 10 version:
I keep OS updated.

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Does anyone have any idea how to resolve this?
Thank you.

**Comment by stmoy** [comment]
Hi @vlad-gregor - this sounds like an issue with the installed SDK. Can you confirm which version of the SDK the Xaml Gallery is targeting? 

![image](https://user-images.githubusercontent.com/25991996/71855033-c82e6c00-3094-11ea-83a2-e38df71b0653.png)

**Comment by vlad-gregor** [comment]
Hello @stmoy,

thank you for your quick response. I do see the exact same output in my Visual Studio 2017 as the one you posted here. In fact, I decided to create a video which you can view at this link:
https://drive.google.com/drive/folders/1xObUW8MqTZo-5Siwg-0A1EpMukByzvno?usp=sharing

Any further ideas?

Thank you.

**Comment by chingucoding** [comment]
Maybe this is a problem with WinUI or the package dependency resolvement itsself, there is also an ongoing issue over at WinUI regarding apps crashing for the same reason.

See the following issues on the WinUI repo for context:

https://github.com/microsoft/microsoft-ui-xaml/issues/999
https://github.com/microsoft/microsoft-ui-xaml/issues/616

Does the app also crash for you when running in Release and not in Debug? Maybe this is also an issue with VS as indicated [by this comment](https://github.com/microsoft/microsoft-ui-xaml/issues/616#issuecomment-526775421) by @jevansaks .

**Comment by vlad-gregor** [comment]
Just a quick update and response to @chingucoding - thank you for pointing those issues out.
If I build the application in Release mode, then it runs OK.

Based on the advice in
https://github.com/microsoft/microsoft-ui-xaml/issues/616
I added ensure, that the "Dependencies" section of my Package.appxmanifest looks like this:
`<Dependencies>
    <TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.14393.0" MaxVersionTested="10.0.17763.0" />
    <PackageDependency Name="Microsoft.UI.Xaml.2.1" MinVersion="2.11904.5004.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />
  </Dependencies>`

The exception is still there. I'm currently clueless.

**Comment by chingucoding** [comment]
It's really weird that it only breaks in debug, but works ok in release. The only thing that I can think of would be test if that issue is also present in VS 2019 to check if this issue is related to Visual Studio or WinUI / package dependency resolvement.

**Comment by jevansaks** [comment]
@vlad-gregor, are you able to share out a repro app or compiled appx that we could side-load? We would need to debug to help figure out what the crash exactly is.

**Comment by vlad-gregor** [comment]
@jevansaks - yes I will gladly share whatever is need. Please specify more clearly what I should share. What is "repro app" and where can I find it? Where do I find "compiled appx" ?

Thank you.

**Comment by vlad-gregor** [comment]
I have another update. I created a new project now in which I started experimenting with UWP MenuBar. For that to work I had to add the "Microsoft.UI.Xaml" NuGet package. All worked fine. 

I was experimenting with different styles and with the resource dictionary of my application. The truth is, I do not know exactly what I did (what a pity!), but the issue started appearing again in this 2nd project. That is, if I run the app in Debug mode, the debugger breaks on line 53 (see my first post).

This time though, the exception message reads:
`Cannot create instance of type 'Microsoft.UI.Xaml.Controls.XamlControlsResources' [Line: 9 Position: 40]`

The sender of the exception again is the application itself - that is in my case "LTOS.Prototype.App", my App.xaml looks like this:
`<Application
    x:Class="LTOS.Prototype.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:LTOS.Prototype">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls"/>
                <ResourceDictionary Source="GUI/LtosGuiDictionary.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>`

and (surprise!), the line 9 position 40 is the reference to "Microsoft.UI.Xaml.Controls" which cannot be resolved. So obviously I am having issues resolving the package as correctly pointed out by @chingucoding .

I'll keep digging. If you have any ideas, please let me know. Thank you very much.

**Comment by jevansaks** [comment]
"Repro app" would be right click your project and Publish -> "Create App Packages...". Then choose the option to make them for sideloading and attach them to your comment.

**Comment by vlad-gregor** [comment]
Gentlemen, I am very sorry, but I had to move on with the project. I therefore uninstalled Visual Studio 2017 and installed Visual Studio 2019. With VS 2019 I do not experience the issue anymore.
I cannot provide any further feedback therefore.
Maybe somebody else will experience this issue and provide more information.

Thank you very much for your help anyway.

**Comment by stmoy** [comment]
Hi @vlad-gregor - thank you for following up. On one hand, it's unfortunate that we're unable to get to the bottom of the issue, but on the other hand, VS2019 is the current version so I'm glad the issue no longer occurs. Closing this issue.

**Comment by jingkecn** [comment]
FYI, another workaround for those who doesn't want to upgrade from VS2017 to VS2019:
Install VS2019 then uninstall it, then it will work again in your VS2017 😂

**Comment by enescglyn** [comment]
I have installed Visual Studio 2019(When I have 2022 version already installed) and Windows 10 SDK 10.0.18362.0, but I still can't get WinUI 2 to work. My error list is filled with these;
![resim](https://user-images.githubusercontent.com/68184538/142738013-be5ec106-1ad8-415d-a87e-7b6cbc66ca8e.png)
Please help me

**Comment by chingucoding** [comment]
@enescglyn Is this issue occurring with the XAML Controls Gallery or with your own app? Can you send the build output of your app?

**Comment by dfmacom** [comment]
> Maybe this is a problem with WinUI or the package dependency resolvement itsself, there is also an ongoing issue over at WinUI regarding apps crashing for the same reason.
> 
> See the following issues on the WinUI repo for context:
> 
> [microsoft/microsoft-ui-xaml#999](https://github.com/microsoft/microsoft-ui-xaml/issues/999) [microsoft/microsoft-ui-xaml#616](https://github.com/microsoft/microsoft-ui-xaml/issues/616)
> 
> Does the app also crash for you when running in Release and not in Debug? Maybe this is also an issue with VS as indicated [by this comment](https://github.com/microsoft/microsoft-ui-xaml/issues/616#issuecomment-526775421) by @jevansaks .

Hi @chingucoding I am having a similar issue in #9208 except in my situation the same crash happens in release mode. I have been trying the various fixes and changes outlined here as well as in #8920 and #616 with no luck. Would you be able to provide any perspective?

**Comment by marcelwgn** [comment]
Hi, sorry for the delayed response. Would you be able to show the event viewer error that relates to the crash? To clarify, we are talking about UWP and WinUI 2 right?
