### ISSUE TITLE
ListView Messaging sample has unreadable outgoing messages

### ISSUE THREAD

**Issue by stmoy** [microsoft/Xaml-Controls-Gallery#320]
**Describe the bug**

In dark theme, the ListView sample titled "ListView for messaging or data logging" has unreadable outgoing messages. (See screenshot below)

**Steps to reproduce the bug**

1. Navigate to the ListView sample
2. Scroll down to "ListView for messaging or data logging"
3. Press "Send Message" 

**Expected behavior**

Outgoing messages have adequate contrast. 

**Actual behavior**

Message bubbles are dark gray on black, with black text. 

**Screenshots**

![image](https://user-images.githubusercontent.com/25991996/72396889-0231ea80-36f3-11ea-845b-a62b63e1035e.png)

**Version Info**

Gallery version (found on Settings page): 

1.2.12.0 (latest version on the Store)

Windows 10 version:
- [x] Insider Build (19541)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by anawishnoff** [comment]
I currently have a PR open (#317) that should fix this issue! Was there something that I forgot to address in that PR?

**Comment by stmoy** [comment]
Whoops, my bad. I thought #317 was already in so I thought this was a potential regression. Closing this issue. 😅
