### ISSUE TITLE
Flip View navigation by arrow key adds a border.

### ISSUE THREAD

**Issue by vidya091209** [Microsoft/Xaml-Controls-Gallery#33]
Flip View navigation by arrow key adds a border.

**Steps to reproduce the bug**
Install the the xaml control gallery  app. go to flip view sample.
when navigate with iocn it works .
but if we navigate by arrow key it it add highlighted border. how i can control this border.

**Comment by YuliKl** [comment]
@vidya091209 - are you referring to the black outline around the FlipView?
![flipview_focus](https://user-images.githubusercontent.com/13142665/51206557-2d55e400-18bd-11e9-8f20-178d8984c738.png)

If so, this is the keyboard focus rectangle. This helps users see where their keyboard input (like arrow keys) is going. While you are able to customize the appearance of the focus rect, I don't recommend doing so. All Xaml controls have some sort of visual indicator of keyboard focus, usually the same focus rect you're seeing around FlipView. Users expect to see the focus rect appear when they're interacting using their keyboard, so its lack, or a different appearance, may be confusing.

**Comment by vidya091209** [comment]
Hi @YuliKl  you are correct. this is the same behavior i am talking about. earlier  this behaviour was not their. we have upgraded out toolkit and upw framework and started seeing this behaviour.
let me know how i can switch it off. thanks.

**Comment by YuliKl** [comment]
There's information about how to customize the focus visuals in this article: https://docs.microsoft.com/en-us/windows/uwp/design/input/guidelines-for-visualfeedback

**Comment by YuliKl** [comment]
@vidya091209 - Please consider not removing the focus visuals entirely. Here's why: https://youtu.be/REaMDacgWUE
