### ISSUE TITLE
Application crashes when Pencil tip is changed on InkToolbar page from circle to rectangle or vice versa.

### ISSUE THREAD

**Issue by YuliKl** [microsoft/Xaml-Controls-Gallery#333]
**Describe the bug**

**Steps to reproduce the bug**

1. Launch XAML Controls Gallery.
2. Activate InkToolbar from All Controls Page.
3. Click On Pencil button and draw something in drawing area.
4. Click on Rectangle radio button.

**Expected behavior**

Selection should change to respective choice.

**Actual behavior**

Application crashes.

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 

1.2.12.0

**Additional context**

Copied from [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/24662725)

**Comment by chingucoding** [comment]
Forgot to write "Fixes #333" in #337 . This issue was fixed with #337
