### ISSUE TITLE
Despite 'Animate controls and elements inside windows' being off, there is an animation after opening a page

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/Xaml-Controls-Gallery#339]
**Describe the bug**

Despite 'Animate controls and elements inside windows' being off, there is an animation after opening a page

**Steps to reproduce the bug**

1. Adjust the appearance and performance of Windows (control panel)
2. Disable 'Animate controls and elements inside windows'
3. Open XAML Controls Gallery
4. Open a page

**Expected behavior**

There would be no animation that fades in the page content to the top left

**Actual behavior**

There is an animation that fades in the page content to the top left

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 

1.2.12.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] 1909 (whatever build that is)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by chingucoding** [comment]
I am wondering if preventing page animations is the job of the app or if it something the framework should do for the developers.

**Comment by Poopooracoocoo** [comment]
@chingucoding How does it work for other apps? Chrome and most UWP apps such as Settings respect that setting.

**Comment by chingucoding** [comment]
Interesting that most apps support it. From what I know is that a lot of controls respect that setting out of the box (e.g. NavigationView or ProgressRing/Bar). Thats why I thought that it would make sense to also do that for page transitions.

**Comment by Poopooracoocoo** [comment]
@chingucoding btw do you know what happened to the feedback I sent through the FBH? I think it was about the shadow options being separate from transparency effects and being moved to Settings. Has Microsoft given up on migrating options from Control Panel to Settings? I think the last time that happened was 2017. I'm mentioning it now as the setting in this issue is in control panel.

**Comment by MikeHillberg** [comment]
The built in controls (and anything else that uses [VisualStateManager](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.VisualStateManager)) should all be responding already to the [UISettings.AnimationsEnabled](https://docs.microsoft.com/uwp/api/Windows.UI.ViewManagement.UISettings.AnimationsEnabled) API, which exposes that user setting. 

But in the Xaml Controls Gallery, ControlExample.xaml has enter/leave animations that are triggered by the Interactivity library, which I don't believe has that check.

**Comment by chingucoding** [comment]
@poopooracooocoo Unfortunately I don't know what happened to that feedback. Since a lot of settings still haven't been transferred from control panel to the settings app, I doubt that there will be much change in the next time.

Regarding the animation, I find it a bit weird that the Windows.UI.XAML.Media.Animations APIs do not have the check for that and just animate regardless of users choice.

**Comment by MikeHillberg** [comment]
The intent of the setting is to turn off transient animations. So animations are still possible, but state change animations in [VisualStateManager](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.VisualStateManager) jump straight to the final state, and I believe all the *Transitions (like [PopupThemeTransition](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Media.Animation.PopupThemeTransition)) jump to their final state as well. But in the Gallery, the ControlExample.xaml control has [PopInThemeAnimation](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Media.Animation.PopInThemeAnimation) and [PopOutThemeAnimation](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Media.Animation.PopOutThemeAnimation), which I think do not but should.

**Comment by chingucoding** [comment]
Hmm I see. Yeah that makes sense. Should this be a framework fix or only in XCG @MikeHillberg , @stmoy  ?

**Comment by stmoy** [comment]
Agreed with @MikeHillberg that the *ThemeAnimations should respect the setting (meaning I think this is a framework bug).

FWIW, I think the page transitions are a bit excessive in any case, and don't actually follow our guidance. Maybe we should remove the PopIn/PopOut storyboards and replace them with the default page transitions (which hopefully respect the animation setting)?

**Comment by chingucoding** [comment]
When we remove them, we have the problem that the source code "jumps" into the page, as the syntax highlighting might not be finished when we navigate to the page, and thus changes after the page is visible.

Regarding Microsoft.XAML.Interactivity not respecting the animations disabled, I have filled an [issue](https://github.com/microsoft/XamlBehaviors/issues/169) in the respective repo.

**Comment by Poopooracoocoo** [comment]
Also see:
https://github.com/microsoft/microsoft-ui-xaml/issues/3669
https://github.com/microsoft/microsoft-ui-xaml/issues/816

**Comment by gregwoo-microsoft** [comment]
Thanks for filing this issue in this XAML Interactivity repo. I'll close this since it is a framework fix and not a XAML fix.

**Comment by Poopooracoocoo** [comment]
@gregwoo-microsoft The point of filing this was so that those issues would receive attention. Those issues were closed because they said that it's on the Windows team to implement. What should someone outside of Microsoft like me do?

**Comment by gregwoo-microsoft** [comment]
I understand your frustration. My advice would be to follow up on the XAML Behavior repo where your issue was filed (https://github.com/microsoft/XamlBehaviors/issues/169). I hope that this helps

**Comment by Poopooracoocoo** [comment]
> I understand your frustration. My advice would be to follow up on the XAML Behavior repo where your issue was filed ([microsoft/XamlBehaviors#169](https://github.com/microsoft/XamlBehaviors/issues/169)). I hope that this helps

Zero progress after two years. Wow! I made more than a few issues hoping they'd be fixed by creating them here such as #612. Wasted effort by me. It's like screaming into the void and talking to a wall or whatever idiom. Neither animations or shadows respect system settings to this day.
