### ISSUE TITLE
Update ProgressBar UI test to reference the NumberBox 

### ISSUE THREAD

**Issue by stmoy** [microsoft/Xaml-Controls-Gallery#346]
**Describe the bug**

The ProgressBar test is failing during CI. 

The bug was likely introduced with this change: #274

The specific failing line is: https://github.com/microsoft/Xaml-Controls-Gallery/blob/0268cff1a367471c4d478031f346a326daa54c65/UITests/ProgressBar.cs#L40

**Steps to reproduce the bug**

To fix this bug, we need to update the ProgressBar.cs test to look instead for the NumberBox and click on the increment button. (Note that the Text() test might also need to be updated)

Error message
Class Initialization method UITests.ProgressBar.ClassInitialize threw exception. System.InvalidOperationException: System.InvalidOperationException: An element could not be located on the page using the given search parameters..

Stack trace
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByName(String name)
   at UITests.ProgressBar.ClassInitialize(TestContext context) in \UITests\ProgressBar.cs:line 40

**Expected behavior**

No test failures!

**Actual behavior**

Test failures :( 

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [ ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by chingucoding** [comment]
Yes, this is an issue caused by the switch to NumberBox. When I tried to improve the WinUI testapp, I also avoided switching to NumberBox since the InteractionTests didn't deal well with that.

I will look into this and hopefully turn `Test failures :(` into `No test failures :)`
