### ISSUE TITLE
ProgressBar Page Broken

### ISSUE THREAD

**Issue by camccar** [microsoft/Xaml-Controls-Gallery#357]
**Describe the bug**
Clicking ProgressBar from the Status and Info page results in a frozen app

**Steps to reproduce the bug**
1. Go to Status and Info from Menu
2. Click on ProgressBar

**Expected behavior**
ProgressBar page loads

**Actual behavior**
XAML Controlls Gallery Freezes, sometimes closes

**Screenshots**
![frozen](https://user-images.githubusercontent.com/3002273/74606488-651df500-5096-11ea-8165-18e9de6abb1e.JPG)

**Version Info**
Version: 1.2.12.0

Gallery version (found on Settings page): 
Version: 1.2.12.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**
N/A

**Comment by ranjeshj** [comment]
@camccar  Does this happen only when you are running under the debugger ?  Can you share a callstack of the crash ?

**Comment by camccar** [comment]
> @camccar Does this happen only when you are running under the debugger ? Can you share a callstack of the crash ?

This is happening on the official app from the app store. I am not running it in visual studio. Looking through the open pull request, it looks like it has been fixed and waiting merge. However I have not tested it.

https://github.com/microsoft/Xaml-Controls-Gallery/pull/355

**Comment by YuliKl** [comment]
@camccar the repro steps in #353, which the PR you mentioned is fixing, are a little different from the repro steps you described above. Does the app crash for you even when you don't change the value of the Progress NumberBox?

![image](https://user-images.githubusercontent.com/13142665/74781890-461a9100-5257-11ea-9cac-acc19094e9e9.png)

**Comment by camccar** [comment]
> 
> 
> @camccar the repro steps in #353, which the PR you mentioned is fixing, are a little different from the repro steps you described above. Does the app crash for you even when you don't change the value of the Progress NumberBox?
> 
> ![image](https://user-images.githubusercontent.com/13142665/74781890-461a9100-5257-11ea-9cac-acc19094e9e9.png)

The app won't even allow me to get to the progress bar page. It just crashes when I click it. 

![bugreport](https://user-images.githubusercontent.com/3002273/74788784-57c06080-5278-11ea-9021-f82b106f7fd9.gif)

**Comment by JohnnyWestlake** [comment]
+1 here

**Comment by ranjeshj** [comment]
@YuliKl @stmoy I don't see this crash in the latest controls gallery built from github. Perhaps we need to push a new one to the store ?

**Comment by YuliKl** [comment]
@JohnnyWestlake what version of Windows are you using?

I'm on an insider Windows build and have not been able to repro the crash with a Store version of the Gallery.

**Comment by YuliKl** [comment]
@camccar, @JohnnyWestlake, we just pushed a new update of the app to the Store. Can you check whether this page still crashes in version 1.2.13.0?

**Comment by JohnnyWestlake** [comment]
@YuliKl Can confirm it no longer crashes for me

**Comment by camccar** [comment]
Also works for me now. Gonna go ahead and close this issue.
