### ISSUE TITLE
Unable to build the XAMLControlsGallery project in VS2017

### ISSUE THREAD

**Issue by saf-itpro** [Microsoft/Xaml-Controls-Gallery#36]
Downloaded the zip file of the project from [GitHub](https://github.com/Microsoft/Xaml-Controls-Gallery). After unzipping and opening the solution in `VS2017` on `Windows 10 pro ver 1809`, I built the project successfully but when I run the project using either `ctrl+F5` or `F5`, I get the message shown in image below. Then, from VS2017 top toolbar menu, I tried `Build-->Deploy XAMLControlsGallery` but it says `Deploy failed` giving no reason. Please help as there are no instructions on the above GitGub link on how to build the project in `VA2017`.

**NOTE**: I'm interesting only in source code build and NOT the prebuilt version of the app available online.

**Error**:

![untitled](https://user-images.githubusercontent.com/10931726/51497736-0d796100-1d92-11e9-888d-157de29867dd.png)

**Comment by stmoy** [comment]
Hi @saf-itpro - we haven't seen this issue before. If you're able to build but not deploy, can you verify that your computer is in Developer Mode (in Settings), and that you're building the correct architecture that matches your computer (x86 or x64, not ARM)? 

More info can be found here: [Deploying and debugging UWP apps](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/deploying-and-debugging-uwp-apps)

**Comment by YuliKl** [comment]
@saf-itpro - I just ran into this problem as well. As @stmoy suggested, my computer was not in developer mode. I was able to currect the problem using the Windows Settings app: Update & Security > For developers.

**Comment by cderi** [comment]
Sorry to post it here, but after a long search I could not find how (and instructions on how) to build the solution in VS2019. 
I am trying to build to the correct architecture, and for target 1903.
VS don't find the System and Microsoft namespaces (!) but I can't find how to correct/update the references ...

**Comment by chingucoding** [comment]
@cderi Have you tried "Restore Nuget Packages" and then tried "Rebuild solution"?

**Comment by cderi** [comment]
@chingucoding Thanks Marcel. After a looonnng Nuget Packages Restoration then Rebuild it worked out. I am glad you gave me this advice, many thanks !

**Comment by chingucoding** [comment]
Happy that I could help @cderi !
