### ISSUE TITLE
ItemsRepeater sample unreadable in dark mode

### ISSUE THREAD

**Issue by stmoy** [microsoft/Xaml-Controls-Gallery#360]
**Describe the bug**

![image](https://user-images.githubusercontent.com/25991996/75197360-ec144280-5712-11ea-95bc-9631bb4159e0.png)

**Steps to reproduce the bug**

1. Go to ItemsRepeater
2. Scroll to "Animated Scrolling and Content Display"

**Expected behavior**

Text is readable. 

**Actual behavior**

Text is white on light color.

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 

Latest pull from master

Windows 10 version:
- [x] Insider Build (xxxxx)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by anawishnoff** [comment]
Thanks! Fixed [here](https://github.com/microsoft/Xaml-Controls-Gallery/pull/361).
