### ISSUE TITLE
ItemsRepeater page should link to layout docs as well

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/Xaml-Controls-Gallery#369]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] New sample
- [x] Addition to existing sample
- [ ] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**
ItemsRepeater

**Is your sample request related to a problem? Please describe it**
The Documentation section should also link to `StackLayout` and `UniformGridLayout` documentation pages as well.

**Comment by anawishnoff** [comment]
Thanks for finding this. Addressed in #370.
