### ISSUE TITLE
SplitButton Page TextBox adds New Lines

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/Xaml-Controls-Gallery#372]
**Describe the bug**
Focusing on the text box for the SplitButton page adds a new line

**Steps to reproduce the bug**

1. Go to 'SplitButton' page
2. Click on the text box
3. Click on the code under the text box
4. repeat steps 2+3 as desired

**Expected behavior**
No newlines added

**Actual behavior**
Newlines get added on focus

**Screenshots**
![XamlControlsGalleryBug](https://user-images.githubusercontent.com/11050425/75914140-177ce880-5e09-11ea-96cd-f792de5a6f35.gif)

**Version Info**
Windows Version 2004 19577.1002

Gallery version (found on Settings page): 
1.2.13.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by stmoy** [comment]
![image](https://media.giphy.com/media/fMvvwdTWamlA4/giphy.gif)

@chingucoding - I think this might be related to #294, can you take a look?

**Comment by chingucoding** [comment]
That was actually introduced with #144 . However this is an issue with the underlying RichEditBox, which is currently tracked here: https://github.com/microsoft/microsoft-ui-xaml/issues/1941

To restore the color of the text upon focus, we call `SetText` which adds a new line. Once the behavior of the RichEditBox and TextBox changes, we probably can get rid of that code and the newly added lines shouldn't be an issue anymore.

**Comment by chingucoding** [comment]
Given that we removed that code that caused this with #524 , this issue can be closed now.
