### ISSUE TITLE
Narrator is silent and focus lands to "Aqua" on pressing "Home" Key in the colors list in ItemsRepeater.

### ISSUE THREAD

**Issue by YuliKl** [microsoft/Xaml-Controls-Gallery#377]
**Describe the bug**

Home and End keys are not handled in the repeater sample. 

**Steps to reproduce the bug**

1. Turn on Narrator.
2. Launch XAML Controls Gallery.
3. Activate ItemsRepeater from home page, navigate to header "Animated Scrolling and Content Display" and press  "Home" Key and observe.

**Expected behavior**

1. Focus should go to the first item in the list i.e "AliceBlue" 
2. Narrator should describe about the item.

**Actual behavior**

Focus does not land on the first list on pressing Home key but it's focus goes to  "Aqua" . Also, Narrator is silent.

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/76571422-aecee500-6474-11ea-840f-2fb6180ee786.png)

**Version Info**

Gallery version (found on Settings page): 

1.2.13.0

**Additional context**

Copied from [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/25469213)

**Comment by YuliKl** [comment]
@anawishnoff FYI

**Comment by anawishnoff** [comment]
@YuliKl 

Hmm, this is interesting. I think my comment on #376 would apply here as well - if the list was infinitely scrollable, would it then make sense to have focus on Aqua after pressing Home key?

I see there is definitely also a lot of work to be done with making sure that Narrator is guiding the user through the samples correctly. I can look into how this is done.
