### ISSUE TITLE
sample is too complex...

### ISSUE THREAD

**Issue by dadufeiyu** [microsoft/Xaml-Controls-Gallery#387]
I tried to setup a really simple project with treeview, but failed.

the sample here is too complex. could you add some basic samples?

my steps are:
1: new project by UWP
2: add Microsoft.UI.Xaml by NuGet
3: drag treeview from toolbox
4: run..and exception "Cannot find a Resource with the Name/Key TabViewItemHeaderBackground [Line: 18 Position: 74]”

try again...add "    <Page.Resources>
                                    <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
                             </Page.Resources>"
but exception also

**Comment by stmoy** [comment]
Hi @dadufeiyu - it sounds like you're having trouble getting a simple project up and running. 

The [Getting Started with WinUI](https://docs.microsoft.com/en-us/uwp/toolkits/winui/getting-started) guide might be able to help.

I think you might be missing a step between 2 and 3 above, which is to add the Windows UI (WinUI) Theme Resources to your App.xaml resources. 

```
<Application>
    <Application.Resources>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" /> 
    </Application.Resources>
</Application>
```

Closing this issue as it is not related to the Xaml Controls Gallery. If the problem persists after the above step, please file an issue on the main WinUI repo here: https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose
