### ISSUE TITLE
Application crashes after activating "Error" radio button in high contrast.

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/Xaml-Controls-Gallery#389]
Copied from internal [issue](https://microsoft.visualstudio.com/OS/_queries/query/b10a6c6c-8692-4d8e-8f7f-c978e523e904/).

**Steps to reproduce the bug**
Turn on High contrast Mode.
Launch "XAML controls gallery" application.
Navigate to  "Progressbar" control.
Click on "Error" radio button under "an indeterminate progress bar" and observe.

**Expected behavior**
"Error" radio button should get selected.

**Actual behavior**
On clicking "Error" radio button application crashes.

**Comment by chingucoding** [comment]
The issues seems to be coming from kernelbase.dll. Seeing that opening the ProgressBar in the MUXControlsTestApp with High Contrast enabled also crashes, this might be an issue in WinUI.

**Comment by chigy** [comment]
This bug no longer repros.
