### ISSUE TITLE
Sample pages should include link to sample code

### ISSUE THREAD

**Issue by MikeHillberg** [microsoft/Xaml-Controls-Gallery#391]
The sample pages have markup, and have a link to the documentation. But some of the the samples include code that's not shown on the page nor linked to. It would be useful if the page also had a link to the sample page implementation in this repo.

For example the AutoSuggestBox page has a SuggestionChosen event handler that's not shown, but the page could have a link directly to the [markup](https://github.com/microsoft/Xaml-Controls-Gallery/blob/98e09620cd4182ef5e865c091788fb6ea3ba85d0/XamlControlsGallery/ControlPages/AppBarToggleButtonPage.xaml) and [code](https://github.com/microsoft/Xaml-Controls-Gallery/blob/98e09620cd4182ef5e865c091788fb6ea3ba85d0/XamlControlsGallery/ControlPages/AutoSuggestBoxPage.xaml.cs).

**Comment by chingucoding** [comment]
Hmm indeed that is a problem. 
Maybe adding more code to the samples would be a good idea. though the samples would explode in some cases.

Regardless of that, I think we should definitely add a link to the markup and code. This should be pretty easy to do for every page.
