### ISSUE TITLE
Winappdriver JS sample missing

### ISSUE THREAD

**Issue by venkatrao-rgare** [microsoft/Xaml-Controls-Gallery#393]
I found the link for this repo here, 
https://github.com/microsoft/WinAppDriver/blob/master/Samples/JavaScript/README.md

but as stated in the page I couldn't find the JS example in this repo.

**Comment by chingucoding** [comment]
Since both the XAML Controls Gallery and the UI tests are entirely written in C#, this seems to be an issue with the documentation. If you are looking for C# examples for Winappdriver in this repository, you can find them under "UITests".

**Comment by stmoy** [comment]
+1 - this is an issue with WinAppDriver documentation and not with the Gallery. Please file an issue there: https://github.com/microsoft/WinAppDriver/issues/new
