### ISSUE TITLE
Add indexing of controls to windows search

### ISSUE THREAD

**Issue by chingucoding** [microsoft/Xaml-Controls-Gallery#395]
UWP apps can add indexing of content to the Windows search. A way the XAML controls gallery could utilize that is by adding every control name to the index That would enabling searching for e.g. "TreeView" and the Windows search listing the XAML Controls Gallery, and upon clicking, would open the TreeView page.

**Comment by chingucoding** [comment]
@stmoy If this is an idea you like, I would be more than happy to implement this.

**Comment by stmoy** [comment]
Love this idea! If you have an idea about how to implement it, please feel free to submit a PR.

**Comment by chingucoding** [comment]
So it turns out the [ContentIndex class](https://docs.microsoft.com/en-us/uwp/api/windows.storage.search.contentindexer) does enable adding content to the system index, however it apparently does not make that content available to the Windows 10 search.

One **very** hacky workaround we could do is add a file for every control page, which uses a propriotary file extension which the XCG registers for as file opener. So you could type "TreeView", the search would return `TreeView.xcgpage` for example and it would open the XCG with the TreeView page. But that is very hacky and I am not sure if that would be a good workflow.

**Comment by stmoy** [comment]
Hmm, that does seem like a hacky workaround. 

I took a quick look through the ContentIndex class docs, and I don't understand what it is supposed to do if it doesn't make that content available to Win10 search. I wonder what it means to "Enables UWP apps to make private content searchable by using the system index" if it doesn't help with Win10 searching...

CC: @mikehillberg - do you have any ideas?

**Comment by MikeHillberg** [comment]
You can use the ContentIndexer to store and index content, and then use its query APIs to search the index. But the search UI would still be in the XCG app itself.

**Comment by chingucoding** [comment]
So the wording for ContentIndexer is a bit misleading? Because I think most people expect the system index to be usable by the Windows 10 search.

**Comment by MikeHillberg** [comment]
Yes, I don't think the ContentIndexer page is making things clear. I think it's worth opening an issue on the page (you're welcome to or I can).

**Comment by chingucoding** [comment]
Okay, thanks for clarification. I will open an issue soon.
