### ISSUE TITLE
Hierarchical NavigationView

### ISSUE THREAD

**Issue by stmoy** [microsoft/Xaml-Controls-Gallery#405]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] New sample
- [x] Addition to existing sample
- [ ] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**
NavigationView

**Describe the sample**

PR #402 added hierarchical navigation to the XCG, but didn't include a sample of hierarchical navigation view on the NavigationView page. This issue tracks adding a sample specifically for this feature. 

**Is your sample request related to a problem? Please describe it**

**Additional context**

**Comment by anawishnoff** [comment]
I'll be trying to put together a sample before the 2.4 release.
