### ISSUE TITLE
ToggleSplitButton "IsChecked" property not working with two-way binding on simple property

### ISSUE THREAD

**Issue by LucaLindholm** [microsoft/Xaml-Controls-Gallery#407]
**Describe the bug**
ToggleSplitBUtton's "IsChecked" property is not allowing to two-way bind to a simple property, like I do with all the other xaml controls.
I suspect that Microsoft hasn't added the support to do it yet.
The error message says that it must be a Dependency Property!

The strange behaviour was founded both in `windows.ui.xaml.controls.ToggleSplitButton` and in `microsoft.ui.xaml.controls.ToggleSplitButton`.

This is the code I used in my app, it is nearly the same as the sample one used in XAML Controls Gallery, so it should work.

Here it's the XAML code:
`<ToggleSplitButton VerticalAlignment="Top" IsChecked="{x:Bind ThemeViewModel.IsLeftPaneTransparent, Mode=TwoWay}">
           <StackPanel Orientation="Horizontal">
           <Grid/>
      </StackPanel>
      <ToggleSplitButton.Flyout>
        <Flyout Placement="Bottom">
            <Grid/>
        </Flyout>
    </ToggleSplitButton.Flyout>
</ToggleSplitButton>`

Here it's the property to which it is linked, in my ThemeViewModel:

`private bool isLeftPaneTransparent;
 public Boolean IsLeftPaneTransparent
 {
       get { return isLeftPaneTransparent; }
       set { SetProperty(ref isLeftPaneTransparent, value); 
       OnPropertyChanged(nameof(IsNOTLeftPaneTransparent)); }
 }`

**Steps to reproduce the bug**
Just run the debug and it will display the error.

**Expected behavior**
The two-way binding should work just stright away.

**Actual behavior**
The error message 

> TwoWay binding target 'IsChecked' must be a dependency property

**Version Info**
Win 10 1903

Gallery version (found on Settings page): 
2.2

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] November 2019 Update (18363)
- [x] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Best regards

**Comment by chingucoding** [comment]
Thank you for your feedback @LucaLindholm . As you correctly pointed out this was an issue with the property not being defined properly. This issue was fixed in WinUI a few days ago and hopefully will be released soon. See [this issue at the WinUI repo](https://github.com/microsoft/microsoft-ui-xaml/issues/2218) for more context and information.

Also, if you find an issue with WinUI, filing the issue over at the [WinUI GitHub repository](https://github.com/microsoft/microsoft-ui-xaml) would be better as the XAML Controls Gallery is just a showcase app of WinUI controls, while WinUI is being developed in it's own repository.

**Comment by chingucoding** [comment]
@LucaLindholm Quick update: The fix for this issue has been released and is available in the latest stable release (WinUI 2.4.2) and the latest prerelease (WinUI 2.5.0-prerelease.20060900).

**Comment by stmoy** [comment]
Closing as this was fixed per @chingucoding's note.
