### ISSUE TITLE
Page navigation from search should expand TreeView and select page

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/Xaml-Controls-Gallery#420]
**Describe the bug**
When you search for a page like `ItemsRepeater` in the sample app you're taken directly to the page, but you have no idea where that page exists in the navigation tree. It would help with the discovery of similar controls if they page is brought forth as the selected/opened page in the NavigationView.

**Steps to reproduce the bug**
1. Go to Sample App
2. Search for a control in the search box
3. Select a choice to navigate to that page from the dropdown

**Expected behavior**
Page selected in NavigationView.

**Actual behavior**
No indication of which page I'm viewing in hierarchy.

**Screenshots**

![image](https://user-images.githubusercontent.com/24302614/81225044-7859a600-8f9d-11ea-9fe5-53192a9941ec.png)

![image](https://user-images.githubusercontent.com/24302614/81225069-7f80b400-8f9d-11ea-965e-75a15836f42f.png)

**Version Info**

Gallery version (found on Settings page): 
1.2.15.0

Windows 10 version:
- [x] Insider Build (19624)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by gregwoo-microsoft** [comment]
@chingucoding do you know if your solution (PR #478) can be applied to the two issues mentioned above?

**Comment by chingucoding** [comment]
#613 is partially fixed (the selection indicator is missing), #726 is not fixed.
