### ISSUE TITLE
XAML Controls gallery typo in RadioButtons Page.

### ISSUE THREAD

**Issue by edfullest** [microsoft/Xaml-Controls-Gallery#428]
**Describe the bug**
In the RadioButton page, there's a typo in the example, since the <muxc:RadioButtons is closed with a </StackPanel>

**Steps to reproduce the bug**
1. Go to the RadioButton page by searching for it.
2. Look at the first example.

**Expected behavior**>
It should be </muxc:RadioButtons>

**Actual behavior**
It's </StackPanel>

**Screenshots**
![typo_radiobuttons](https://user-images.githubusercontent.com/11062927/81876221-fe926100-9536-11ea-9d95-2e7999c0f23b.PNG)

**Version Info**
2.3,2.4

Gallery version (found on Settings page): 
1.2.9.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [X] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by chingucoding** [comment]
That typo was fixed with #401. The typo is also not visible in the latest store version of the XAML Controls Gallery (1.2.15.0) 😄
