### ISSUE TITLE
"inbox controls" typo?

### ISSUE THREAD

**Issue by rgwood** [microsoft/Xaml-Controls-Gallery#433]
**Describe the bug**

The StandardUICommand and XamlUICommand descriptions both mention "inbox controls." I'm not sure what an inbox could be outside of an email client, and I can't find any relevant documentation. Is this a typo?

[StandardUICommand](https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/DataModel/ControlInfoData.json#L56):
> StandardUICommands are a set of built-in XamlUICommands represeting commonly used commands. Including the look and feel of a given command, which can be reused across your app, and which is understood natively **my the inbox controls**. E.g. Save, Open, Copy, Paste, etc.

[XamlUICommand](https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/DataModel/ControlInfoData.json#L31):      
> An object which is used to define the look and feel of a given command, which can be reused across your app, and which is understood natively **my the inbox controls**.

Gallery version (found on Settings page): 
1.2.15.0

**Comment by mdtauk** [comment]
I think they mean the "Out of the Box" controls, or the WinUI/UWP controls.

"Inbox apps", is a term used for those applications that come with Windows - so I assume it is being used in the same context
