### ISSUE TITLE
Back button is large and square unlike the system buttons

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/Xaml-Controls-Gallery#435]
**Describe the bug**

The back button is large and square unlike the system buttons.

**Steps to reproduce the bug**

1. Open XAML Controls Gallery

**Expected behavior**

back button would look like the one in settings: 
![image](https://user-images.githubusercontent.com/51363864/82356203-a089e000-9a46-11ea-9ad3-84fff5bbbb0a.png)

**Actual behavior**

back button is large:
![image](https://user-images.githubusercontent.com/51363864/82356512-05453a80-9a47-11ea-842d-20cb2d85d239.png)

**Screenshots**

provided above

**Version Info**

Gallery version (found on Settings page): 

1.2.15.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] May 2020 Update (19041)
- [x] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by mdtauk** [comment]
The one in settings is trying to match the previous practice of letting the system put a back button in the title bar.  The Xaml Controls Gallery is using the newer practice of the in-app Back Button which is designed to match the Hamburger Button being square.  It is also how the NavigationView handles it's back button implementation.

**Comment by gregwoo-microsoft** [comment]
It seems like this is no longer an issue. Thanks for the feedback though!

![Screenshot 2022-01-06 100933](https://user-images.githubusercontent.com/90726278/148430114-15ca5779-91bd-4050-8bde-494a145bf178.png)
