### ISSUE TITLE
the hierarchal NavigationView's chevrons aren't coloured on hover

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/Xaml-Controls-Gallery#438]
**Describe the bug**

the hierarchal NavigationView's chevrons aren't coloured on hover

**Steps to reproduce the bug**

1. Open XAML Controls Gallery
2. Hover over a chevron in the NavigationView

**Expected behavior**

Chevron would be accent coloured or even a separate button.

**Actual behavior**

The chevron isn't separate.

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 

1.2.15.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] May 2020 Update
- [x] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by Poopooracoocoo** [comment]
Actually I've already made this: https://github.com/microsoft/microsoft-ui-xaml/issues/983

**Comment by chingucoding** [comment]
I think this is an issue with the NavigationView control, not something specifically related to the XCG. It should probably be moved to the WinUI repo, your thoughts @stmoy ?

**Comment by Poopooracoocoo** [comment]
@chingucoding @stmoy I've already filed this over at WinUI. See the above link. Forgot to click on close and comment.
