### ISSUE TITLE
AnimatedVisualPlayer improvements

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/Xaml-Controls-Gallery#441]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] New sample
- [ ] Addition to existing sample
- [x] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**
AnimatedVisualPlayer

**Describe the sample**

the player controls should be improved by merging play and pause buttons, by using the previous symbol for the "stop" button, and by using the rewind symbol for the reverse button.

**Is your sample request related to a problem? Please describe it**

The player feels alien compared to players across the web and Windows.

**Additional context**

Current: 
![image](https://user-images.githubusercontent.com/51363864/85913438-37cd2900-b878-11ea-910c-6b5c63db2199.png)
Concept:
![image](https://user-images.githubusercontent.com/51363864/85913884-11a98800-b87c-11ea-8b12-1dda00984e18.jpg)

and as always, tooltips or labels would really help. Play/pause, back to start and play in reverse.

**Comment by chingucoding** [comment]
Those are great ideas, they would make the sample "more natural" in my opinion. @stmoy Would you be fine with those changes? If so, I'll gladly implement those.

**Comment by mdtauk** [comment]
Will this sample page include the ability to use XAML colour resources for the animations?

**Comment by chingucoding** [comment]
It currently does not, but maybe this is something that the XCG should also have. Would you like to create a sample request @mdtauk ?

**Comment by mdtauk** [comment]
> It currently does not, but maybe this is something that the XCG should also have. Would you like to create a sample request @mdtauk ?

I think the WinUI team may consider looking into including the process of using XAML Colours in Lottie Animations, so when it is detailed how this works, and I understand how it works, then I will know if it is something that can be done from Xaml or Script - and then can be included in the XCG.

I think it is a modification or feature of the control, so just wondered if the example/sample page would be the place for it @chingucoding

**Comment by chingucoding** [comment]
> I think the WinUI team may consider looking into including the process of using XAML Colours in Lottie Animations, so when it is detailed how this works, and I understand how it works, then I will know if it is something that can be done from Xaml or Script - and then can be included in the XCG.

> I think it is a modification or feature of the control, so just wondered if the example/sample page would be the place for it @chingucoding

That's a really good question, I am not entirely sure where to discuss this, maybe WinUI as they own the control? Maybe @ranjeshj or @stmoy knows more?

**Comment by ranjeshj** [comment]
@simeoncran @ajbennet @karenbtlai Is the information on how to expose custom colors/properties in Lottie animations documented ?

**Comment by simeoncran** [comment]
The best way to learn about theming properties is via the Lottie-Windows samples app: https://github.com/windows-toolkit/Lottie-Windows/tree/master/samples/LottieSamples/Scenarios.

**Comment by stmoy** [comment]
@chingucoding asked:

> Those are great ideas, they would make the sample "more natural" in my opinion. @stmoy Would you be fine with those changes? If so, I'll gladly implement those.

Agreed, these look like great changes. 

@mdtauk asked: 

> Will this sample page include the ability to use XAML colour resources for the animations?

This seems like a good idea to me. That said, this sample/improvement is separate from the work tracked in this issue - my recommendation would be to open another issue to track this work. (Plus, I know that the color conversation is a particularly active one right now, and I don't want to derail the specific improvement described in this issue.)

**Comment by simeoncran** [comment]
The sample is a copy of what's in the LottieSamples app. https://github.com/windows-toolkit/Lottie-Windows/tree/master/samples
If we're going to change one, we should change both.
@chingucoding - are you interested in tackling that too?

**Comment by chingucoding** [comment]
Sure thing! Is there a tracking issue for that already or would you like me to create it? Based on the fact that #480 isn't working 100% perfect yet, I am not sure how long it might take until I can change that in there too.

**Comment by simeoncran** [comment]
If you don't mind creating an issue for it, then I'd be so happy for you to do it, so I can go out and enjoy the sun. :-) Please do!

**Comment by chingucoding** [comment]
Done! Enjoy the sun :)
