### ISSUE TITLE
reveal is stuck on left on menus

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/Xaml-Controls-Gallery#446]
**Describe the bug**

menuflyout reveal effect is stuck on left

**Steps to reproduce the bug**

1. Go to MenuFlyout

**Expected behavior**

reveal would be normal

**Actual behavior**

reveal is stuck on left

**Screenshots**

![Screenshot (4)](https://user-images.githubusercontent.com/51363864/82562975-96d4b980-9bb9-11ea-9abd-2f5b8ab9736f.png)
(my cursor is on the right)

**Version Info**

Gallery version (found on Settings page): 

1.2.15.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by chingucoding** [comment]
I can't seem to repro this on Windows Insider Build 19635. @Poopooracoocoo Does this issue also happen in other apps using reveal with MenuFlyouts?

Since we don't use a modified MenuFlyout, this might be a WinUI issue.

**Comment by Poopooracoocoo** [comment]
@chingucoding oh wow they finally fixed it. only took an entire year (and a half)

>Does this issue also happen in other apps using reveal with MenuFlyouts?

yes

it's actually a system xaml issue. i didn't think it'd affect winui. :/

**Comment by Poopooracoocoo** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/995

**Comment by Poopooracoocoo** [comment]
Reveal ain't a thing no more. Officially at least. It's still in plenty of places...
