### ISSUE TITLE
Update RadioButton icon

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/Xaml-Controls-Gallery#449]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] New sample
- [ ] Addition to existing sample
- [x] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**

**Describe the sample**

The RadioButton icon uses the old design

**Is your sample request related to a problem? Please describe it**

**Additional context**

Current icon/design: 
![image](https://user-images.githubusercontent.com/51363864/82751908-db509700-9dfd-11ea-90aa-61e6e4a1ad3a.png)

New radio button: 
![image](https://user-images.githubusercontent.com/51363864/82751916-e99eb300-9dfd-11ea-9bc5-6ac031b0f2bc.png)

**Comment by stmoy** [comment]
This would be fixed as part of https://github.com/microsoft/Xaml-Controls-Gallery/issues/504 - closing this bug in lieu of that more holistic tracking issue.
