### ISSUE TITLE
Related Controls elements are overlapping with Feedback section elements in few controls.

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/Xaml-Controls-Gallery#456]
Ported from internal [issue](https://microsoft.visualstudio.com/OS/_queries/query/b10a6c6c-8692-4d8e-8f7f-c978e523e904/)

![Overlapping](https://user-images.githubusercontent.com/7758786/83191960-b142f180-a0e9-11ea-90d1-64547f21fb42.png)

**Comment by stmoy** [comment]
Dupe of #451, fixed with #453
