### ISSUE TITLE
The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))

### ISSUE THREAD

**Issue by myblindy** [microsoft/Xaml-Controls-Gallery#459]
**Describe the bug**
The application crashes on start up with the following exception:

```
System.Runtime.InteropServices.COMException: 'The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))'
```

And the following stack trace:
```
onecoreuap\shell\coreapplication\application\lib\ApartmentHelpers.h(22)\twinapi.appcore.dll!00007FFF465061D1: (caller: 00007FFEDF01D06B) ReturnHr(1) tid(5414) 8001010E The application called an interface that was marshalled for a different thread.
    CallContext:[\AppRunOrActivateView] 
onecoreuap\shell\coreapplication\application\lib\coreapplication.cpp(75)\twinapi.appcore.dll!00007FFF465061EC: (caller: 00007FFEDF01D06B) ReturnHr(2) tid(5414) 8001010E The application called an interface that was marshalled for a different thread.
    CallContext:[\AppRunOrActivateView] 
onecoreuap\shell\coreapplication\application\lib\coreapplicationfactory.cpp(147)\twinapi.appcore.dll!00007FFF46506214: (caller: 00007FFEDF01D06B) ReturnHr(3) tid(5414) 8001010E The application called an interface that was marshalled for a different thread.
```
**Steps to reproduce the bug**
Run the application.

**Expected behavior**
I would expect it not to crash.

**Actual behavior**
It crashes.

**Screenshots**
Nothing on screen yet to screen shot.

**Version Info**
Gallery commit: https://github.com/microsoft/Xaml-Controls-Gallery/commit/0f0b39072f6703face2cc6fb89e3a18850193b16
Net Core SDK 5.0.100-preview.4

Gallery version (found on Settings page): 
It doesn't start to see it, it's the version from the commit above, latest on the winui3preview branch as of writing this.

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [X] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**
N/A

**Comment by RealTommyKlein** [comment]
Are you trying to run XamlControlsGallery.Desktop from a Visual Studio older than 16.7 Preview 1?  I believe that's what causes this error.

**Comment by myblindy** [comment]
Oh, is that the requirement? Yeah, it's the latest 16.6, if that's the case then you can close this issue.

**Comment by RealTommyKlein** [comment]
Yup, upgrading to 16.7 Preview 1 should fix this.  I'll close this issue for now, feel free to reopen if you still see it 👍
