### ISSUE TITLE
Feedback label isn't show properly

### ISSUE THREAD

**Issue by Torebor** [microsoft/Xaml-Controls-Gallery#462]
**Describe the bug**

Feedback label isn't show properly in the ContentDialog page.

**Steps to reproduce the bug**

1. Go to Dialogs and Flyouts
2. Click on ContentDialog

**Expected behavior**

Access to the Related control list and click on 'Tooltip'

**Actual behavior**

The Feedback text is on the Tooltip hyperlink and is not clickable

**Screenshots**

![image](https://user-images.githubusercontent.com/7685925/83903796-013e3b80-a71c-11ea-9574-5ed11d23690a.png)

**Version Info**

Gallery version (found on Settings page): 

1.2.15.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [X] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by stmoy** [comment]
Thank you for reporting this issue - it was fixed with PR #453 but the change hasn't made it into the Store version of the app yet. Please reopen this issue if you're building from master.
