### ISSUE TITLE
Global issue with the XAML Controls Gallery

### ISSUE THREAD

**Issue by Torebor** [microsoft/Xaml-Controls-Gallery#463]
**Describe the bug**

Recently I submitted an issue https://github.com/microsoft/Xaml-Controls-Gallery/issues/462 where the Feedback text isn't show properly, but I noted this issue turned globally in the app.
 
**Steps to reproduce the bug**

1. Navigate throughout all the pages in the app and look for the Feedback text, you'll notice that is over the hyperlinks.

**Expected behavior**

Align the Feedback text.

**Actual behavior**

The Feedback text is over the hyperlinks

**Version Info**

Gallery version (found on Settings page): 

1.2.15.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [X] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by stmoy** [comment]
Thank you for reporting this issue - it was fixed with PR #453 but the change hasn't made it into the Store version of the app yet. Please reopen this issue if you're building from master.
