### ISSUE TITLE
Not working and not updating.

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/Xaml-Controls-Gallery#465]
I can't run the app, nor can I update it in the store. It errors out with Code: 0x80073CFB.

**Comment by Gavin-Williams** [comment]
I tried running the app again tonight, and same, nothing happens. Other store apps are updating OK.

Could this be related to the fact that Xaml doesn't render in Visual Studio at the moment? Waiting for Windows 20 to roll out for that to be fixed.

**Comment by Gavin-Williams** [comment]
Uninstalled and reinstalled. It's working now.

**Comment by stmoy** [comment]
@Gavin-Williams - how strange! Thank you for following up.

![gif](https://media.giphy.com/media/DUtVdGeIU8lmo/giphy.gif)

**Comment by Symbai** [comment]
How did you uninstalled it? I have the same issue, when I try to debug it says its already installed but I dont see it under Windows Settings / Apps. And I get the same store error result
