### ISSUE TITLE
Question: Is there an icon for the TwoPaneView?

### ISSUE THREAD

**Issue by mrlacey** [microsoft/Xaml-Controls-Gallery#466]
I can't find an icon for the TwoPaneView.
Is there one?

I also can't find an issue tracking this (and other controls) missing icons? Is there one? Or is this not something that's going to be done? (I'd expect it to be part of a checklist for [new] controls)

**Comment by stmoy** [comment]
The answer to @mrlacey's original question is "no, there is no icon". I've internally escalated fixing #358 to add a TwoPaneView sample to the Gallery so I'm closing this issue. 

In the short term, I would recommend using the SplitView icon which is what I expect the TwoPaneView icon to look like. 

![image](https://user-images.githubusercontent.com/25991996/84078134-3dc49e00-a98d-11ea-97f4-b561b2da0fa1.png)
