### ISSUE TITLE
use blue instead of default accent colour for tile and splash screen

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/Xaml-Controls-Gallery#474]
**Describe the bug**

so according to @grochoki Windows Calculator using blue instead of the default accent colour for the tile is by design. I don't know why. In unrelated news, The shell team will be dropping tile backplates in a year. My start menu looks messy right now and waiting for more than a year for a solution doesn't sound fun.

**Steps to reproduce the bug**

N/A

**Expected behavior**

tbh i'd expect it to use the default accent colour like it does right now

**Actual behavior**

uses accent colour

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 

1.2.15.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] May 2020 Update
- [x] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

p.s. please update the template to include the may 2020 update
and yes this whole issue is just out of spite lol

**Comment by stmoy** [comment]
Double checking: what would you like the behavior to be @poopooracoocoo? With the start menu updates, would you expect that the tile has a background or not? (I'm inclined to think that it wouldn't; or rather, it'd do whatever the default is.)

**Comment by Poopooracoocoo** [comment]
@stmoy Thanks for understanding my sarcasm lol. That was what I hoped you guys would understand. 
I'd expect XAML Controls Gallery to use the **default** colour: my accent colour. The shell update that will remove tiles is rather separate. It affects both custom and default coloured tiles. And it's in another year anyway. Right now, apps should use my accent colour. 
It's ridiculous that Microsoft just says "We're removing tiles anyway" without caring about right now. You have to actually try to change the colour, right? And what about splash screens?
This issue is mostly to let you know that Calculator isn't using the default and uses blue. Whoever thought of that has evidently only used the default accent colour and/or default wallpaper. The start menu is really messy when the default blue isn't your accent colour.
It's interesting that Microsoft is moving to shapeless icons at this time. Apple just made macOS icons shaped. 

To answer your question, I would expect tiles backplates/backgrounds to be gone. I'd expect apps that have changed the colour of their tile to use that colour for their icons. That way the Xbox icon would be green if that makes sense. Other apps could use the accent colour or be black/white. That sounds like a good transition for apps that haven't made new, shapeless icons. There are some apps that use the tile to its fullest. The Adobe suite could've done that.

**Comment by Poopooracoocoo** [comment]
if you want to feel confused, the peeps working on Calculator say that it's because of the new icon. https://github.com/microsoft/calculator/issues/1360 like have they not checked out macos 

And now that 20H2 is rolling out (three months after just this issue), I've noticed that the way tiles were removed was quite bad and that it doesn't affect Settings either.

**Comment by gregwoo-microsoft** [comment]
For now, the XCG already uses your accent color within the app. However, we don't plan on changing the icon to use the accent color.

**Comment by Poopooracoocoo** [comment]
@gregwoo-microsoft You mean that XCG was updated to use the accent colour for the splash screen and thus should be closed.

**Comment by gregwoo-microsoft** [comment]
Yes @Poopooracoocoo that too. Thanks for pointing it out. Although I'd like to point out that this accent color splash screen can only be seen in Windows 10 (not in Windows 11).
