### ISSUE TITLE
[CRASH] Motion > Implicit Transition > Empty Opacity field

### ISSUE THREAD

**Issue by TCLNA** [microsoft/Xaml-Controls-Gallery#475]
**Describe the bug**
I tried to click on the cross to empty the field and see what happens when clicking the button... welp, it crashes !

**Steps to reproduce the bug**
1. Go to Motion > Implicit Transitions
2. Empty the Opacity field
3. Click on `Set Opacity` button

**Expected behavior**
Setting opacity to 0.

**Actual behavior**
App crashes.

**Screenshots**
![image](https://user-images.githubusercontent.com/32589981/84957767-2eb3bd80-b0fc-11ea-9724-d4c9e985483a.png)
![image](https://user-images.githubusercontent.com/32589981/84957772-34a99e80-b0fc-11ea-81bb-231c68067b12.png)
I cannot show the app crashing...

**Version Info**

Gallery version (found on Settings page): 
Latest (1.2.15.0)

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [X] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Question**
Is it done in purpose ?

**Comment by stmoy** [comment]
Note I'll need to push a new version of the Gallery before this fix will show up in the Store version of the app.
