### ISSUE TITLE
Feedback at the end of a control page is overlapping

### ISSUE THREAD

**Issue by MarcAnt01** [microsoft/Xaml-Controls-Gallery#483]
**Describe the bug**

Feedback at the end of a control page is overlapping

**Steps to reproduce the bug**

1. Go to Button
2. Scroll down

**Expected behavior**
No overlapping xD

**Actual behavior**

Overlapping

**Screenshots**

![image](https://user-images.githubusercontent.com/43090263/86390743-ec13e880-bc98-11ea-9edb-264481f5632e.png)

**Version Info**

Gallery version (found on Settings page): 

1.2.15.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by chingucoding** [comment]
This was already fixed with #453 . I am not sure if that was published to the store yet.

**Comment by MarcAnt01** [comment]
Closing, then

**Comment by stmoy** [comment]
Thanks for reporting. 

> I am not sure if that was published to the store yet.

Not yet 😅 - but this is a good reminder.

**Comment by MarcAnt01** [comment]
You're welcome, also would like to let you know that I am running May 2020 update and I couldn't insert this option in the issue template

**Comment by stmoy** [comment]
Good catch, I'll update the template. Thank you!

**Comment by stmoy** [comment]
@MarcAnt01 - did the thing 😁  https://github.com/microsoft/Xaml-Controls-Gallery/commit/bc91f448bb5356bc5184193a53d8c230860cce1c
