### ISSUE TITLE
RadialGradientBrush sample feels misplaced in Motion catagory

### ISSUE THREAD

**Issue by YuliKl** [microsoft/Xaml-Controls-Gallery#484]
**Describe the bug**

I was curious what the icon for RadialGradientBrush sample page looked like, so tried to find the link to it in main nav. I first checked under Styles but the page wasn't there. Eventually found it in Motion, which feels wrong.

**Expected behavior**

I expected to find radialGradientBrush as a child of Styles.

**Actual behavior**

RadialGradientBrush is a child of Motion.

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/86413158-63378580-bc75-11ea-89a3-9f72c7a04d6c.png)

**Version Info**

Gallery version (found on Settings page): 

1.2.15.0

**Additional context**

**Comment by stmoy** [comment]
Agreed.
