### ISSUE TITLE
Ctrl + F to use search

### ISSUE THREAD

**Issue by MarcAnt01** [microsoft/Xaml-Controls-Gallery#487]
I'd like to be able to use ctrl + F shortcut to trigger search

**Comment by stmoy** [comment]
I like this idea! The easiest thing to do would probably be to put focus on the Search box if the user presses Ctrl + F. @chingucoding, what do you think?

**Comment by chingucoding** [comment]
Yes, agreed. I think moving focus to the search box is a good idea, I am slightly concerned about accessibility here. But the user would invoke the action through ctrl+f, so we are probably fine here.

Would you like me to create a PR for this?

**Comment by YuliKl** [comment]
> Yes, agreed. I think moving focus to the search box is a good idea, I am slightly concerned about accessibility here. But the user would invoke the action through ctrl+f, so we are probably fine here.

I think this is expected behavior and I don't have any accessibility concerns with this plan.
