### ISSUE TITLE
Bug: Pivot Guidelines link has changed

### ISSUE THREAD

**Issue by SavoySchuler** [microsoft/Xaml-Controls-Gallery#50]
**Describe the bug**

Pivot's Guidelines link no longer links to the correct address.

**Steps to reproduce the bug**

1. Go to 'Pivot'
2. Click on 'Guidelines'

**Expected behavior**

I expect the Guidelines link to direct to this address:
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/pivot

**Actual behavior**

The Guidelines link directs to this address:
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/windows-apps-src/design/controls-and-patterns/pivot.md

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 
Gallery version 1.1.1.0

Windows 10 version:
- [X] Insider Build (18331)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by Poopooracoocoo** [comment]
Will this be closed?

**Comment by stmoy** [comment]
@Poopooracoocoo - thanks! Yes - closing.
