### ISSUE TITLE
Text "Feedback" overlaps items of Related controls

### ISSUE THREAD

**Issue by GarbageSal** [microsoft/Xaml-Controls-Gallery#503]
**Describe the bug**

Text "Feedback" overlaps items of Related controls.

**Steps to reproduce the bug**

1. Go to any control's page
2. Scroll to the bottom

**Expected behavior**

The feedback area would be below the related controls area.

**Actual behavior**

Text "Feedback" overlaps items of Related controls.

**Screenshots**

![image](https://user-images.githubusercontent.com/30483813/87654514-97d53200-c789-11ea-825a-2965535005af.png)

**Version Info**

Gallery version (found on Settings page): 

1.2.15.0

Windows 10 version:
- [x] Insider Build (19042)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by chingucoding** [comment]
This was fixed with #453

**Comment by GarbageSal** [comment]
I just updated to the latest version (1.2.16.0) in the store. The bug is fixed.
