### ISSUE TITLE
Sample for hub

### ISSUE THREAD

**Issue by Chips1234** [microsoft/Xaml-Controls-Gallery#527]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [X] New sample
- [ ] Addition to existing sample
- [ ] Modification to existing sample

**Describe the sample**
Have a sample page for hub.

**Additional context**
[This document](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.hub?view=winrt-19041)

**Comment by YuliKl** [comment]
The Hub control is pretty much deprecated, which is the reason you won't find any design guidance about this control in https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/. I would advise against adding a sample like this to the Controls Gallery.

**Comment by Chips1234** [comment]
Ah, okay

________________________________
