### ISSUE TITLE
Is there a plan to introduce C++/WinRT code samples?

### ISSUE THREAD

**Issue by tacticalmelonfarmer** [microsoft/Xaml-Controls-Gallery#531]
If not, will you consider doing this in the future?

**Comment by stmoy** [comment]
There is no plans in the short term - most of the sample code in the Gallery are Xaml markup snippets which should be portable across languages. Additionally, we have found that C# is much more ubiquitous across our developer telemetry, so we've prioritized supporting C# in the Xaml Controls Gallery. 

That said, this is something we're discussing in the context of Project Reunion. I'm closing this issue, but please consider opening a new issue on the Project Reunion GitHub: https://github.com/microsoft/ProjectReunion/issues

Are there specific samples you are looking for or controls that you'd like to see samples for? 

CC: @kevinguo305 who has been thinking about Project Reunion samples

**Comment by kevinguo305** [comment]
C++/WinRT samples is definitely super important! We're definitely making a strong internal push as part of Project Reunion to get not only Xaml-Controls-Gallery, but all sample galleries to support at least C# and C++/WinRT. There hasn't been an established timeline yet, but I'm working on it!

**Comment by tacticalmelonfarmer** [comment]
ok thanks for the response

**Comment by MRahilly** [comment]
@kevinguo305 Great to hear this. I have the samples from the first few chapters of Petzold PW6 converted to C++/WinRT if you want them.
