### ISSUE TITLE
Rating control page source code links are incorrect

### ISSUE THREAD

**Issue by winiston2212** [microsoft/Xaml-Controls-Gallery#532]
**Describe the bug**
The XAML and C# Source code links for the RatingControl page are invalid.

**Steps to reproduce the bug**

1. Go to RatingControl
2. Click either the "XAML source code" or "C# source code" links under "View page code on GitHub"
3. Github will display error 404 page not found

**Expected behavior**
The link should be set to [https://github.com/microsoft/Xaml-Controls-Gallery/tree/master/XamlControlsGallery/ControlPages/RatingsControlPage.xaml](https://github.com/microsoft/Xaml-Controls-Gallery/tree/master/XamlControlsGallery/ControlPages/RatingsControlPage.xaml)

**Actual behavior**
The link is actually [https://github.com/microsoft/Xaml-Controls-Gallery/tree/master/XamlControlsGallery/ControlPages/RatingControlPage.xaml](https://github.com/microsoft/Xaml-Controls-Gallery/tree/master/XamlControlsGallery/ControlPages/RatingControlPage.xaml), which doesn't exist.

("RatingControlPage" needs to be changed to "RatingsControlPage")

**Screenshots**
![image](https://user-images.githubusercontent.com/59544401/90681904-038f3c80-e219-11ea-9aed-d46e95b6617a.png)

Gallery version (found on Settings page): 
1.2.16.0

Windows 10 version:
- 2004 version 20190.1000

Device form factor:
- Desktop

**Comment by chingucoding** [comment]
The issue seems to be that the source code of the page does not follow the name of class name + "page". However the link is generated through this pattern, To fix this issue, we would simply need to rename the class RatingControlPage to RatingsControlPage as you correctly pointed out.

@winiston2212 Would you like to contribute a fix for this issue? 😃

**Comment by winiston2212** [comment]
@chingucoding Sure!
