### ISSUE TITLE
Determinate Progress Bar - numberbox improvements

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/Xaml-Controls-Gallery#534]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] New sample
- [ ] Addition to existing sample
- [x] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**
ProgressBar

**Describe the sample**

The NumberBox with spin buttons could be improved by:
letting you press up even when there is no number in the box
     - this could be fixed by setting the number to 0 by default
     - note: when you type 0 in to that box, you have to un-focus on the box for it to be applied.
and by letting you press and hold on the spin buttons  

**Is your sample request related to a problem? Please describe it**

**Additional context**

![image](https://user-images.githubusercontent.com/51363864/90888166-13657700-e3f9-11ea-8899-3e010b18c8fa.png)

**Comment by chingucoding** [comment]
Regarding your second point about value not being applied when typing, this seems to be by design.
