### ISSUE TITLE
XAML Controls Gallery doesn't gracefully display in dark theme mode

### ISSUE THREAD

**Issue by SetTrend** [microsoft/Xaml-Controls-Gallery#541]
System icons (located at the upper right corner of the app) aren't displayed in dark mode:

![XAML Controls Gallery](https://user-images.githubusercontent.com/9283914/91355800-fe208c00-e7ee-11ea-8b90-2c130b9cbfbe.png)

Version: 1.2.16.0

**Comment by YuliKl** [comment]
While I've seen this problem before, I thought we had done work to address it. And I'm not able to repro on my machine.

@SetTrend, can you describe the exact steps that got you into this state?

**Comment by chingucoding** [comment]
@SetTrend Are you by any chance running an insider build of Windows 10? There was a bug where those buttons disappeared on UWP apps that was fixed with the latest Windows 10 insider build (20201).

**Comment by SetTrend** [comment]
This is sooo strange ... The XAML Controls Gallery app I installed had this issue for weeks by now. But right after I raised this issue here yesterday - today, the problem is gone all of a sudden:

![XAML Controls Gallery](https://user-images.githubusercontent.com/9283914/91418920-14f8ca00-e853-11ea-9d4f-ec61eef72bbe.png)
