### ISSUE TITLE
What's New header gets misplaced after resizing

### ISSUE THREAD

**Issue by demberto** [microsoft/Xaml-Controls-Gallery#542]
**Describe the bug**
The **What's New** header title gets stuck to the wrong position after resizing the window to minimum width and back again. No matter what you try, unless you reopen the app, it is stuck to the same wrong position. This doesn't happen with **All Controls** header title.

**Steps to reproduce the bug**

1. Go to **What's New** section.
2. Resize the window to minimum width.
3. Resize the window back to its normal width or go full screen.

**Expected behavior**
![image](https://user-images.githubusercontent.com/65948403/91631149-1f52c980-e9f5-11ea-92dc-34c377b6bfcc.png)

**Actual behavior**
Refer Screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/65948403/91631060-39d87300-e9f4-11ea-8243-7e04fc67d7e0.png)

**Version Info**
Gallery version (found on Settings page): **1.2.16.0**

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by stmoy** [comment]
I am able to reproduce this issue. My guess is that the What's New header is doing some fancy logic only on first launch, but it should be doing that fancy logic on resize as well.

**Comment by gregwoo-microsoft** [comment]
Thank you for filing this issue @demberto ! I'm closing this as it was fixed in the newest version of the Gallery.

**Comment by demberto** [comment]
Sure
