### ISSUE TITLE
Source file '...App.g.i.cs' could not be found.

### ISSUE THREAD

**Issue by JayTennant** [Microsoft/Xaml-Controls-Gallery#55]
**Describe the bug**
When trying to build for the x64 or x86 configuration, two errors appear:

    Severity Code	Description
    Error	CS2001	Source file 'C:\Users\Jay\source\repos\Xaml-Controls-Gallery\XamlControlsGallery\obj\x64\Debug\App.g.i.cs' could not be found.	File: C:\Users\Jay\source\repos\Xaml-Controls-Gallery\XamlControlsGallery\CSC	Line: 1
    Error		Cannot resolve Assembly or Windows Metadata file 'Type universe cannot resolve assembly: System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.'	File: C:\Users\Jay\source\repos\Xaml-Controls-Gallery\XamlControlsGallery\XamlControlsGallery.csproj	

**Steps to reproduce the bug**
1. Clone using Github desktop
2. Open with VS 2017 v15.9.7
3. Select x64 or x86 configuration.
4. Try to build/rebuild.

**Expected behavior**
Not getting an error. Nothing was modified on cloning.

**Actual behavior**
Getting the error.

**Screenshots**
N/A

**Version Info**
- VS version: 15.9.7 (updated tonight 2/19/2019)
- System type: x64-based PC

Gallery version (found on Settings page): 
- (just downloaded tonight 2/19/2019)

Windows 10 version:
- April 2018 Update (17134)

Device form factor:
- Desktop

**Additional context**
N/A

**Comment by YuliKl** [comment]
@JayTennant - while the errors you're seeing are different, have you tried any of the suggestions outlined in issue #36?

**Comment by JayTennant** [comment]
I've verified I'm running in developer mode, selected x64 configuration, and my OS version 17134 is within the minimum and target OS versions.

The source file App.g._**i**_.cs doesn't exist in the said directory (obj/x64/Debug), but App.g.cs does.

**Comment by JayTennant** [comment]
I discovered the problem.

I had disabled npm manager from checking for missing packages and automatically downloading them (it's terribly slow for any uwp app to build), specifically this uwp project took over 5 minutes after attempting to build for it to stop with the said errors (I didn't time it, but got tired of waiting and came back later.)

An error that appeared in the status bar was:

    Retrying 'FindPackagesByIdAsync' for source 'https://api/nuget.org/v3-flatcontainer/runtime.win10-x64.microsoft.net.native.sharedlibrary/index.json'. The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x64.microsoft.net.native.sharedlibrary/i...

Anyway, I tried re-enabling npm manager again today, let it run for a while, came back, and it successfully built.
