### ISSUE TITLE
ContentControl not properly measured while adding ContentTemplate

### ISSUE THREAD

**Issue by JagadeesanPichaimuthu** [microsoft/Xaml-Controls-Gallery#551]
**Describe the bug**
ContentControl not properly measured while adding ContentTemplate. In our application, we defined the DataTemplate for item and tried to calculate the height by assign the DataTemplate to the ContentControl in code behind. When create the ContentControl and measure the size in code behind without attach visual tree, it not properly calculated the size. It always return the height as 0, and it not calculated the height based on the ContentTemplate. Please find the sample here,

[AutoFit.zip](https://github.com/microsoft/Xaml-Controls-Gallery/files/5188351/AutoFit.zip)

<Page
    x:Class="AutoFit.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:AutoFit"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Page.Resources>
        <DataTemplate x:Key="dataTemplate">
            <Grid>
                <Grid.RowDefinitions>
                    <RowDefinition Height="Auto"/>
                    <RowDefinition Height="Auto"/>
                </Grid.RowDefinitions>
                <TextBlock
                    Margin="5" 
                    FontWeight="Bold"
                    VerticalAlignment="Center"
                    FontSize="13" Foreground="Black"
                    Text="Sanitation"
                    TextWrapping="Wrap" />
                <TextBlock
                    Margin="5,0,5,5" 
                    Grid.Row="1"
                    FontSize="12" Foreground="Black"
                    Text="Sanitation is a an important aspect of public health policy. One of its primary purposes is to treat wastewater so that any pollutants are eliminated, thereby reducing negative environmental impacts."
                    TextWrapping="Wrap" />
            </Grid>
        </DataTemplate>
    </Page.Resources>

    <Grid x:Name="grid" HorizontalAlignment="Center" VerticalAlignment="Center" Background="White">
        
    </Grid>
</Page>

public sealed partial class MainPage : Page
    {
        ContentControl contentControl = new ContentControl();
        
        public MainPage()
        {
            this.InitializeComponent();
            contentControl.Width = 250;
            contentControl.ContentTemplate = this.Resources["dataTemplate"] as DataTemplate;
            this.Loaded += MainPage_Loaded;
        }

        private void MainPage_Loaded(object sender, RoutedEventArgs e)
        {
            contentControl.Measure(new Size(contentControl.Width, double.PositiveInfinity));
            contentControl.Height = contentControl.DesiredSize.Height;
        }
    }

**Steps to reproduce the bug**
1. Run the sample.
2. Put break point in Loaded method.
3. After measure the ContentControl, check the size.
4. The measure method is not properly calculated.

**Expected behavior**
The measure method need to properly calculate when assign the ContentTemplate.

**Comment by chingucoding** [comment]
This is not an issue directly related to the XAML Controls Gallery right? In that case, this issue is better suited for [the WinUI repository](https://github.com/microsoft/microsoft-ui-xaml).
