### ISSUE TITLE
Registrations not updated, pages crash on click in Desktop app

### ISSUE THREAD

**Issue by j0shuams** [microsoft/Xaml-Controls-Gallery#558]
**Describe the bug**

XamlControlsGallery.Desktop crashes when certain pages are navigated to. 
The reported error is `ClassFactory cannot supply requested class`. 
I believe this is an issue with the registrations in 
`\Xaml-Controls-Gallery\XamlControlsGallery\build\LiftedWinRTClassRegistrations.xml` 

**Steps to reproduce the bug**

1. Use the `winui3preview` branch 
2. Open XamlControlsGallery.Desktop.sln in VS
3. Build and run the app
4. You can reproduce by navigating to any of a few different pages:
 - Basic Input > RatingControl | Slider
 - Layout > Border | Canvas | Grid | SplitView
 - Motion > Animation interop
 - Scrolling > ScrollViewer

**Expected behavior**
The pages should load. 

**Actual behavior**
The app crashes, shuts down. 

**Screenshots**
Clicking on RatingControl:

![image](https://user-images.githubusercontent.com/70237359/93126514-4a8a1980-f681-11ea-98cb-75272353b023.png)

Output window upon crash

![image](https://user-images.githubusercontent.com/70237359/93126597-655c8e00-f681-11ea-99b4-e439bcbb2d96.png)

Call Stack upon crash

![image](https://user-images.githubusercontent.com/70237359/93126552-5675db80-f681-11ea-90ec-2dcc081310fe.png)

**Version Info**
CsWinRT Version used: 0.1.0-prerelease.200629.3
WinUI Version used: 3.0.0-preview2.200713.0

Gallery version (found on Settings page): 

1.2.27.0

Windows 10 version:
- [X] Insider Build (xxxxx)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by stmoy** [comment]
CC: @MikeHillberg

**Comment by bpulliam** [comment]
The winui3 branch has been updated and should fix this issue.
