### ISSUE TITLE
CalendarView crashes app when changing languages

### ISSUE THREAD

**Issue by j0shuams** [microsoft/Xaml-Controls-Gallery#560]
**Describe the bug**
The XamlControlsGallery Desktop app crashes when you change the language several times. 

**Steps to reproduce the bug**

1. Use the `winui3preview` branch
2. Build and run the app
3. Go to 'Date and Time' > CalendarView > 'A basic calendar view.'
4. Change the language several times. No fixed number causes it, but after a few, the app will crash.

**Expected behavior**
Calendar widget updates

**Actual behavior**
App freezes and crashes 

**Screenshots**

It doesn't seem to be one particular language that causes the crash

![image](https://user-images.githubusercontent.com/70237359/93131652-4235dc80-f689-11ea-9671-6d700cdae157.png)

Call stack:

![image](https://user-images.githubusercontent.com/70237359/93131668-4a8e1780-f689-11ea-9354-aa207f021c05.png)

Output window:

![image](https://user-images.githubusercontent.com/70237359/93131677-5083f880-f689-11ea-9362-15439d7efe32.png)

**Version Info**
CsWinRT Version used: 0.1.0-prerelease.200629.3
WinUI Version used: 3.0.0-preview2.200713.0

Gallery version (found on Settings page): 
1.2.27.0

Windows 10 version:
- [X] Insider Build (xxxxx)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by stmoy** [comment]
Keep 'em coming, @j0shuams!

CC: @MikeHillberg

**Comment by bpulliam** [comment]
I'm not seeing this anymore on the winui3 branch. Please reactivate (or create a new issue) if you still see this.
