### ISSUE TITLE
Compact Sizing example XAML source code not useful

### ISSUE THREAD

**Issue by wldevries** [microsoft/Xaml-Controls-Gallery#564]
**Describe the bug**
Compact Sizing showcases how the sizing between controls can be varied using fluent styles. The XAML source code does not show how these styles are used in the input form control to set the various paddings and margins.

**Steps to reproduce the bug**

1. Open the Compact Sizing example
2. Click XAML Source code

**Expected behavior**
XAML shows the source of the compact and standard input form controls.

**Actual behavior**
It only shows the xaml of the control that hosts them

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 
1.2.16.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by wldevries** [comment]
The code for the samples is right there in the github repository, so after some searching this is a non-issue. I also misunderstood how the density styling is supposed to work. It seems to only work on controls, it does not give standard reusable margins and paddings for controls.

**Comment by chingucoding** [comment]
While the source code is on the GitHub repository, I think it would be better to not have users have to open GitHub to understand the sample. Is there anything we could add to the compact sizing samples so they are better to understand?
