### ISSUE TITLE
Incorrect header left padding in What's New and All controls pages

### ISSUE THREAD

**Issue by jolleekin** [microsoft/Xaml-Controls-Gallery#569]
**Describe the bug**
The header left padding is too small in **What's New** and **All controls** pages.

**Screenshots**

![image](https://user-images.githubusercontent.com/5405376/95559453-fab12f00-0a41-11eb-84d1-ef8d68561ac5.png)
![image](https://user-images.githubusercontent.com/5405376/95559415-ebca7c80-0a41-11eb-95c1-305b2dba0b63.png)

**Version Info**

Gallery version (found on Settings page): 
1.2.16.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] May 2020 Update (19041)
- [x] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by gregwoo-microsoft** [comment]
Thanks for filing this issue. I believe that this was fixed with the new update :)
