### ISSUE TITLE
Make all URLs language+region agnostic

### ISSUE THREAD

**Issue by sohchatt** [microsoft/Xaml-Controls-Gallery#58]
Most documentation throughout the repo uses links with "/en-us/".  Consider removing to make the links friendly to users from different regions/ languages.

**Comment by chingucoding** [comment]
#### Clarification
While it seems like the links are all using the "/en-us/" , the links specified (and which are opened in the browser) are not region/language agnostic and don't use any of these localization.

What happens is, when opening the link, you get redirected to the locale/language you chose (which apparently defaults to en-us). 

If you however set the language to use for the documentation (which you can do at the bottom of the page) opening these documentation links will result in opening the corresponding page with the correct locale in the URL. Of course this is kinda useless if for some pages there are no translation into other languages.

##### Example
You click on the documentation for example for the Button API. The link that is provided by the XAML Controls Gallery app is: 
https://docs.microsoft.com/uwp/api/windows.ui.xaml.controls.button

If you have not specified any language in the documentation at the bottom of the page, the link will open https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.button.

However if you have chosen to use another language in the documentation, for example german clicking the link in the app will result in opening this link:
https://docs.microsoft.com/de-de/uwp/api/windows.ui.xaml.controls.button

**HOWEVER** some links have the /en-us/ locale actually "hardcoded" and I'll create a PR fixing this. Thanks for reporting this!
