### ISSUE TITLE
Layout of items are not getting changed after moving focus to the radio button in ItemsRepeater pane.

### ISSUE THREAD

**Issue by YuliKl** [microsoft/Xaml-Controls-Gallery#585]
**Describe the bug**

**Steps to reproduce the bug**

1. Launch XAML Controls Gallery.
2. Navigate to "All Controls" Button and activate it.
3. Navigate to "ItemsRepeater" button and activate it.
4. Move focus to the Layout radio buttons
5. Use up/down arrow keys to move between radio buttons

**Expected behavior**

Layout should changed after activating different layout button.     

**Actual behavior**

No change observe after activating any of the radio buttons with focus moves.

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/97644715-4c792380-1a08-11eb-9562-8dc147bae91b.png)

**Version Info**

Gallery version (found on Settings page): 1.2.16.0

**Additional context**

Copied from [internal bug](https://microsoft.visualstudio.com/OS/_queries/edit/20652363)

**Comment by chigy** [comment]
@anawishnoff fixed this
