### ISSUE TITLE
There is no ARM64 configuration in the sample app

### ISSUE THREAD

**Issue by SergeyADoroshenko** [microsoft/Xaml-Controls-Gallery#593]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] New sample
- [ ] Addition to existing sample
- [.] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**

**Describe the sample**

**Is your sample request related to a problem? Please describe it**

**Additional context**

**Comment by chingucoding** [comment]
This is already being tracked by #570 . PR #587 will add the ARM64 configuration to the solution.

**Comment by stmoy** [comment]
Closing as dupe per @chingucoding's comment.
