### ISSUE TITLE
Bug: WinUI-2.5: Accessibility: [MAS4.2.1]: Narrator: For the Message length combo box, narrator says as "message" instead of "Message length"

### ISSUE THREAD

**Issue by v-amnat** [microsoft/Xaml-Controls-Gallery#597]
**Tags**
Accessibility, A11yFT,  A11yMAS, A11yLowImpact, MAS4.2.1, Narrator, Sev4, WinUI-2.5, Win32, Wipro 

**User Impact**
For the Message length combo box, narrator says as "message" instead of "Message length", so its not descriptive enough for the screen reader user.

**Steps to reproduce the bug**
Launch the WinUI_2.5_TestApp
1. Go to Info Bar-> Navigate to the Message Length Combo box-> Observe the narrator behavior for the message length combo.

**Expected behavior**
Narrator should say as "Message length" combo box, instead of "Message" combo box.

**Actual behavior**
Narrator  says as "Message" combo box, instead of "Message Length" combo box.

**Repro Video**

[Narrator- Message Length Combo Box.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5558029/Narrator-.Message.Length.Combo.Box.zip)

**Version Info**
Win32
Windows OS Version: Windows 10
App: WinUI_2.5_TestApp

**Comment by YuliKl** [comment]
This is an app issue so moving repos. @gabbybilka, something you probably want to fix as part of your XCG PR.

**Comment by stmoy** [comment]
@Yulikl - what is the expected behavior vs. actual behavior? 

> Expected behavior
> Narrator should say as "Message length" combo box, instead of "Message" combo box.
> 
> Actual behavior
> Narrator says as "Message length" combo box, instead of "Message" combo box.

I would expect that it should read as "Message length" combo box.

I would also expect that it just does this naively, as the ComboBox header says "message length". If it doesn't, wouldn't this be a bug in ComboBox?

**Comment by YuliKl** [comment]
Both the UIA name and the header are being set, so Narrator is reading the name. I left I comment about this in the PR.
