### ISSUE TITLE
[WinUI3 preview] DEP1000: DirectoryNotFoundException for nuget\microsoft.winui\3.0.0-preview NoiseAsset.png

### ISSUE THREAD

**Issue by get-flat** [microsoft/Xaml-Controls-Gallery#599]
**Error DEP1000: Cannot copy file**
"C:\Users\<username>\.nuget\packages\microsoft.winui\3.0.0-preview3.201113.0\runtimes\win10-arm64\native\Microsoft.UI.Xaml\Assets\\**NoiseAsset_256x256_PNG.png**"

to layout "C:\Users\<username>\Source\Repos\Xaml-Controls-Gallery\XamlControlsGallery\bin\XamlControlsGallery.Desktop.Package\XamlControlsGallery.Desktop.Package\AppX\XamlControlsGallery.Desktop\runtimes\win10-arm64\native\Microsoft.UI.Xaml\Assets\NoiseAsset_256x256_PNG.png". 

DirectoryNotFoundException - Could not find a part of the path
'C:\Users\<username>\Source\Repos\Xaml-Controls-Gallery\XamlControlsGallery\bin\XamlControlsGallery.Desktop.Package\XamlControlsGallery.Desktop.Package\AppX\XamlControlsGallery.Desktop\runtimes\win10-arm64\native\Microsoft.UI.Xaml\Assets\NoiseAsset_256x256_PNG.png'. [0x80070003]	XamlControlsGallery.Desktop.Package			

**Steps to reproduce the bug**
xcg: branch winui3preview
run LocalMachine: Debug/Win32 XamlControlsGallery.Desktop.Package

Visual Studio:
- [ ] 2019 16.9 preview

Windows 10 version:
- [ ] November 2019 Update (18363)

Device form factor:
- [ ] Desktop

System Type
- [ ] x64-based PC

(Is it possible to get xcg winui3preview pre-built version?)

**Comment by stmoy** [comment]
CC: @MikeHillberg @marb2000 @anawishnoff

**Comment by marb2000** [comment]
I've just tried it and it worked pretty well:
 
1. Did you clean the solution? 
2. Are you using VS 2019 16.9? Sometimes, if you have more versions of VS you start the wrong version when double click on the sln.

-M

**Comment by martinriedel** [comment]
Same problem here. Your path is too long. I copied the project to C:\w\, set the start project to the XamlControlsGallery.Desktop.Package project and everything was fine :)

**Comment by df-macom** [comment]
If anyone else lands here in 2025 and beyond, Win32 apps now can support long file paths with the simple addition of this element to your appxmanifest inside the <application> node

    <windowsSettings xmlns:ws2="http://schemas.microsoft.com/SMI/2016/WindowsSettings">
        <ws2:longPathAware>true</ws2:longPathAware>
    </windowsSettings>

See msdn: https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#application-manifest-updates-to-declare-long-path-capability

**Comment by df-macom** [comment]
Well, nevermind. 

I got my app to deploy twice after adding the app.manifest element in my comment above, but then It went right back to having the same issue

"DEP1000: Cannot copy file "filename.xbf". DirectoryNotFoundException - Could not find a part of the path [path] [0x80070003]

Dunno, but im pretty sad. Why would it work twice then stop?
