### ISSUE TITLE
Add a segment/pixel eraser to InkToolbar sample

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/Xaml-Controls-Gallery#612]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] New sample
- [x] Addition to existing sample
- [ ] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**
InkToolbar

**Describe the sample**

A segment/pixel eraser

**Is your sample request related to a problem? Please describe it**

drawing is hard and other apps could do with a reference, especially as MS Whiteboard is just a web app.

**Additional context**

**Comment by stmoy** [comment]
I _believe_ this is a limitation of the InkCanvas control. https://stackoverflow.com/questions/53632049/erasing-portion-of-a-stoke-in-uwp

**Comment by Poopooracoocoo** [comment]
I have this issue: https://github.com/microsoft/microsoft-ui-xaml/issues/1530 but I doubt it'll EVER be implemented, so I created this issue in hopes that you guys will implement it in XAML Controls Gallery.

**Comment by stmoy** [comment]
The Gallery aims to showcase the capabilities of the platform, not to supersede them; I don't think that we'll do anything special in the Gallery in this case (especially since I'm not even sure it's possible).

**Comment by gregwoo-microsoft** [comment]
I'm closing this issue as this is a feature request for WinUI.
