### ISSUE TITLE
Typo in determinate ProgressRing progress example

### ISSUE THREAD

**Issue by MarcAnt01** [microsoft/Xaml-Controls-Gallery#620]
**Describe the bug**

Please refer to the screenshot

**Steps to reproduce the bug**

Just check the determinate ProgressRing example

**Expected behavior**

See the example displayed properly

**Actual behavior**

Typo

**Screenshots**

![image](https://user-images.githubusercontent.com/43090263/103411448-4fab9f80-4b70-11eb-9efd-8b4fb2625855.png)

**Version Info**
- [x] App downloaded from Store 
    - If so, which version? (Found on the Settings page of the app.)
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3preview branch)

**Additional context**

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by chingucoding** [comment]
Would you like to create a PR for this? The file you would need to modify would be this: https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/ControlPages/ProgressRingPage.xaml

**Comment by MarcAnt01** [comment]
> Would you like to create a PR for this? The file you would need to modify would be this: https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/ControlPages/ProgressRingPage.xaml

Done 👍
