### ISSUE TITLE
Add support to samples to "copy link to this page" with appropriate protocol activation parameters

### ISSUE THREAD

**Issue by grochocki** [microsoft/Xaml-Controls-Gallery#623]
As far as I can tell, the only way to generate a deep link into a specific page is to construct the protocol activation URI manually. It would be helpful to be able to quickly generate links to specific pages within the app and add them to your clipboard. This would make it easier to reference specific samples in emails, chat, support tickets, issues, documentation, etc.

There are a number of options that come to mind (could implement one or more):
* Add context menu on NavigationViewItems
* Add button near existing "Toggle Theme" button on each page
* <kbd>Ctrl</kbd> + <kbd>C</kbd> on any page (when text is not selected) could copy URI to clipboard

**Comment by chingucoding** [comment]
That's a very good idea! When I read this, I initially thought about adding the page link next to the source code links:
![Image highlighting the source code links area of the page](https://user-images.githubusercontent.com/16122379/103630973-b7803280-4f42-11eb-9391-52b7faf61fcd.png)

Of course we would need to change the heading of that area but I think it might make sense to add this there grouping wise.
