### ISSUE TITLE
Selecting MediaPlayerElement in Xaml-Controls-Gallery app makes the app crash

### ISSUE THREAD

**Issue by BirgerNiss** [microsoft/Xaml-Controls-Gallery#628]
**Describe the bug**

Selecting MediaPlayerElement in Xaml-Controls-Gallery app makes the app crash

**Steps to reproduce the bug**

Apart from trying the Xaml-Controls-Gallery app, I've made the world's smallest UWP application using only the MediaPlayerElement on the page. Calling the InitializeComponent() method throws an exception with the message: "XAML parsing failed.". 
The stack trace reads: ""   at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)\r\n   at TestUWP.MainPage.InitializeComponent() in <folder>MainPage.g.i.cs:line 35\r\n   at TestUWP.MainPage..ctor() in <folder>\MainPage.xaml.cs:line 32"" 

This test app fails on my Windows 10, 10.0.19042.

On other PC's with the same Windows version, the test app does not fail.
Conclusion: The code is ok, something on my machine must be wrong. 
Any suggestions are highly appreciated:-)

**Comment by stmoy** [comment]
Hi @BirgerNiss - thanks for reaching out. Double checking: is the issue hitting both the Gallery app **and** the small UWP test app, or just the test app?

**Comment by BirgerNiss** [comment]
Hi Steven - Both the test UWP app AND the Gallery app crash on MediaPlayerElement.
Thanks for your prompt reaction!

**Comment by stmoy** [comment]
Gotcha. Since this issue is broader than just the Gallery, I'd recommend filing a separate issue on the Microsoft UI Xaml repo which tracks platform issues: https://github.com/microsoft/microsoft-ui-xaml

**Comment by BirgerNiss** [comment]
GOOD NEWS! After having installed the optional feature: Media Feature Pack, MediaPlayerElement now works, both in my small test app and in the gallery!

**Comment by stmoy** [comment]
🎉 - thanks for following up! Happy coding!
