### ISSUE TITLE
Caption buttons disappear in the Light mode 

### ISSUE THREAD

**Issue by pratikone** [microsoft/Xaml-Controls-Gallery#653]
On launching XCG (UWP),  caption buttons (min/max/close) don't show in active window mode.  They disappear or merge with the white background. They only show up on hover or when window is inactive.

Way to reproduce :  
1) Set windows to Light mode
2) Launch XCG

**Comment by Poopooracoocoo** [comment]
Got a screenshot?

**Comment by Poopooracoocoo** [comment]
![image](https://user-images.githubusercontent.com/51363864/124571088-d4aea300-de8a-11eb-83b9-e6c487323e66.png)
@anawishnoff

**Comment by anawishnoff** [comment]
Thanks for filing this, not sure what's causing it. @ranjeshj have we seen this before?

**Comment by ranjeshj** [comment]
@pratikone @anawishnoff No, I have not seen this issue. Does it resolve itself after restarting the app ? I'm curious if the theme change is not propagating to the caption controls.

**Comment by mdtauk** [comment]
For UWP, you usually have to update the Caption Button colours from code behind.  Are you using ThemeResources for these, or are you detecting a theme change and re-setting these colours?

**Comment by chingucoding** [comment]
XCG should do the latter, you can't actually use ThemeResources for the Caption buttons (the API expects Color objects).

**Comment by mdtauk** [comment]
> XCG should do the latter, you can't actually use ThemeResources for the Caption buttons (the API expects Color objects).

This is what my remembrance was, for when I played with it back when Windows 10 launched - had to grab the colour value

**Comment by Poopooracoocoo** [comment]
> @pratikone @anawishnoff No, I have not seen this issue. Does it resolve itself after restarting the app ? I'm curious if the theme change is not propagating to the caption controls.

nope. i didn't change the theme at all.

**Comment by gregwoo-microsoft** [comment]
I can't repro this on either my Windows 10 or 11 machines using the new version of the XCG. Closing this for now.

**Comment by Poopooracoocoo** [comment]
@gregwoo-microsoft Can you reproduce this on a version higher than WinUI 2 Gallery version 1.2.25.0 on Windows 10? If not, can you reopen this?
