### ISSUE TITLE
Accessibility: Group of radio buttons doesn't get its title spoken by Narrator

### ISSUE THREAD

**Issue by MarcoZehe** [microsoft/Xaml-Controls-Gallery#657]
**Describe the bug**

The label for a group of radio buttons is not spoken by screen readers when tabbing into it. One does not know what question is being asked.

**Steps to reproduce the bug**

1. Go to 'Radio buttons' under the What's New section.
2. Turn on Narrator and tab into the groups of color selections for "Background" and "Border".

**Expected behavior**

Narrator should speak "Background, Green Radio button checked", or "Border, Yellow Radio button checked".

**Actual behavior**

Narrator only says "Black radio button checked" or "Yellow radio button checked", but not which of the radio buttons is asking what question.

**Screenshots**

**Version Info**
- [x] App downloaded from Store 
    - If so, which version? (Found on the Settings page of the app.) Version: 1.2.17.0
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3preview branch)

**Additional context**

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] October 2020 Update (19042)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by chingucoding** [comment]
Thank you for filing this issue @MarcoZehe. This however is an issue with the WinUI control not being accessible, see https://github.com/microsoft/microsoft-ui-xaml/issues/3183 for more context.

**Comment by stmoy** [comment]
This is an issue with the control, not with the Gallery - closing this per @chingucoding's note.
