### ISSUE TITLE
Creating RadialGradientBrush in xaml brush

### ISSUE THREAD

**Issue by AghaKhan** [microsoft/Xaml-Controls-Gallery#668]
You may able to create LinearGradientBrush  in XAML file, but it is not possible to write  RadialGradientBrush in XAML file. The reason is GradientStops (IObservableVector<GradientStop>) is only get it and set is not available, so you can not assign any any GradientStop. 
But in cs file you open write code
RadialGradientBrush  radialBrush = new RadialGradientBrush
            {
                Center = new Point(152.5584, 299.6992),
                RadiusX = 11.1223,
                RadiusY = 11.1223,
            };

            radialBrush .GradientStops.Add(new GradientStop
                {Offset = 0, Color = Common.ConvertToColor("#67674F") });
            radialBrush .GradientStops.Add(new GradientStop
                { Offset = 1, Color = Common.ConvertToColor("#BDBAA1") });
            radialBrush .Transform = new MatrixTransform {Matrix = new Matrix(0, 1, -1, 0, 499.1684, -97.7408)}; 
 Please make available in XAML. Thanks

**Comment by chingucoding** [comment]
You can add gradient stops in XAML, for example the RadialGradientBrush page does this: https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/ControlPages/RadialGradientBrushPage.xaml

For issues related to WinUI 2/WinUI 3 please post an issue on the WInUI repository (https://github.com/microsoft/microsoft-ui-xaml), this GitHub repository is only for the XAML Controls Gallery :)

**Comment by stmoy** [comment]
Thank you for providing a link to the sample @chingucoding. Closing this issue. @AghaKhan - please open a new issue on the WinUI repository (https://github.com/microsoft/microsoft-ui-xaml) if you have more questions/feedback. Thank you!

**Comment by AghaKhan** [comment]
It has same problem.  It compiles but give warning The type 'RadialGradientBrush' does not support direct content.
and it should and I explained the reason above. I also see from the result it works with warnings. I am not sure when I say it works how accurate is that brush. 


`Page
    x:Class="App3.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local="using:App3"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:media="using:Microsoft.UI.Xaml.Media"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
    mc:Ignorable="d">
    <Page.Resources>
        <RadialGradientBrush x:Key="MyBrush" x:Name="RadialGradientBrushExample" Center="0.5,0.5" GradientOrigin="0.5,0.5" MappingMode="RelativeToBoundingBox" RadiusX=".5" RadiusY=".5" SpreadMethod="Pad">
            <GradientStop Offset="0.0" Color="Yellow" />
            <GradientStop Offset="1" Color="Blue" />
        </RadialGradientBrush>
    </Page.Resources>
    <StackPanel>
        <Rectangle
            x:Name="Rect"
            Width="200"
            Height="200"
            Fill="{StaticResource MyBrush}" />
    </StackPanel>

</Page>`

**Comment by AghaKhan** [comment]
` <StackPanel>
        <Rectangle
            x:Name="Rect"
            Width="200"
            Height="200"
            Fill="{StaticResource MyBrush}" />
    </StackPanel>`
