### ISSUE TITLE
Motion -> Page Transition has bad referencing to TransitionInfo class

### ISSUE THREAD

**Issue by JanRajnoha** [microsoft/Xaml-Controls-Gallery#671]
**Describe the bug**
Just a typo. Page "Page Transitions" in section "Motion" has invalid class reference to Drill transition info

![image](https://user-images.githubusercontent.com/16069721/113856561-b3fa8280-97a1-11eb-8ff3-31cf50936c1e.png)

**Steps to reproduce the bug**
1. Go to Motion -> Page transition
2. Click on Drill
3. Invalid C# code referencing to DrillNavigationTransitionInfo(), should be DrillInNavigationTransitionInfo

**Version Info**
- [x] App downloaded from Store 
    - If so, which version? (Found on the Settings page of the app.)
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3preview branch)

Windows 10 version:
- [x] Insider Build (latest)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by stmoy** [comment]
Thanks for filing this issue - it has been fixed in the main branch but needs to be ported to the WinUI 3 version of the app. Fixed with PR: https://github.com/microsoft/Xaml-Controls-Gallery/pull/351

Closing this issue since it's fixed in main - hoping to get the branches converged soon.
