### ISSUE TITLE
[XAML Controls Gallery(debug)->Text->NumberBox] : Name property is null for 'Enter an integer' drop down edit field.

### ISSUE THREAD

**Issue by v-amnat** [microsoft/Xaml-Controls-Gallery#682]
**Tags**
Accessibility, A11yCT, A11yMAS, A11yAuto, AI4D, A11yMediumImpact, MAS4.2.1, ScreenReader,
A11ySev2, XAMLControlsGallery, WinUI, Win32, Wipro

**Test Environment**

XAML Controls Gallery(debug) version - 2.0.21.0
Win 32/ OS build- 21343.rs_Prerelease.210320-1757

**Steps to reproduce the bug**

1. Launch the XAML Controls Gallery (Debug) App
2. Go to the Text-> NumberBox.
3. Run accessibility Insights for Number box tile.

**Actual behavior**
Name property is defined null for 'enter an integer' drop down edit field.

**Expected**
All components need an accessible name and role, ideally with semantic elements and attributes. In rare cases, aria-label or aria-labelled by may be needed to alter the name, or a role attribute may be needed for a component to pass essential information on to assistive technology. Learn more by reading about the accessible name property, when to use an aria role, and the html/aria role mappings.

**User Impact** 
When interactive elements have an incorrect name and role, it is difficult for people using assistive technology (like screen readers) to understand the purpose of control and its relationship to other content. Knowing the role for a control helps users know what will happen when that object has focus and is selected, as well as what keyboard shortcuts to use when interacting with the control. 

**MAS Reference**
MAS 4.2.1 – Object Information

**Attachments**
[Fast Pass.zip](https://github.com/microsoft/Xaml-Controls-Gallery/files/6311301/Fast.Pass.zip)

**Comment by v-amnat** [comment]
[Fast Pass.zip](https://github.com/microsoft/Xaml-Controls-Gallery/files/6311298/Fast.Pass.zip)

**Comment by chigy** [comment]
Tracked with WinUI 2.6 bug
