### ISSUE TITLE
[XAML Controls Gallery(debug)->Motion->Connected Animation] : Application is getting crashed when user invokes image items in connected animation pane.

### ISSUE THREAD

**Issue by v-amnat** [microsoft/Xaml-Controls-Gallery#683]
**Tags**
Accessibility, A11yCT, A11yFeature, Feature Issue, XAMLControlsGallery, WinUI, Win32, Wipro

**Test Environment**
1. XAML Controls Gallery(debug)  version - 2.0.21.0
2. Win 32/ OS build- 21343.rs_Prerelease.210320-1757

**Steps to reproduce the bug**

1. Launch the XAML Controls Gallery (Debug) App
2. Go to the Motion-> ConnectedAnimation.
3. Invoke any of the image item list and observe.

**Actual behavior**
When user invokes on any of the item image list xaml controls gallery application is getting closed.

**Note:**
This is feature issue.

**Expected**
On invoking the image items application should not get closed.

**User Impact** 
Differently abled users will find difficulty if the application is getting closed.

**Attachments**

[Crash Issue.zip](https://github.com/microsoft/Xaml-Controls-Gallery/files/6311406/Crash.Issue.zip)

**Comment by ranjeshj** [comment]
Fixed as part of this internal issue.
https://microsoft.visualstudio.com/OS/_workitems/edit/31883866
