### ISSUE TITLE
WebView2 has white borders

### ISSUE THREAD

**Issue by WelterDevelopment** [microsoft/Xaml-Controls-Gallery#694]
**Describe the bug**
The WebView2 control has white borders on the left and on the top. 

**Steps to reproduce the bug**
Go to the "WebView2" page of the Winui 3 Controls Gallery app.

**Expected behavior**
I want no borders or at least the ability to remove them by setting WebView2.BorderThickness=0.

**Screenshots**
![Screenshot 2021-05-10 101845](https://user-images.githubusercontent.com/13318246/117628196-2bdd1380-b179-11eb-9ab1-833e0223b9ae.jpg)

**Additional context**
Seems to be a general bug of either WebView2 or the WinUi 3 implementation. I also get the white borders in my own apps. Any idea where the right place to file that bug might be? I havent found information about that issue online. Am I the only one with that problem? At least I tested on 2 different devices and got the same result... 

Windows 10 version:
- [x] Insider Build (21370)
- [x] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

WebView2 Runtime:
- [x] Current version (90.0.818.56) installed by the evergreen installer

**Comment by chingucoding** [comment]
> Seems to be a general bug of either WebView2 or the WinUi 3 implementation. I also get the white borders in my own apps. Any idea where the right place to file that bug might be? I havent found information about that issue online. Am I the only one with that problem? At least I tested on 2 different devices and got the same result...

I think the WinUI repository might be the correct place for this: https://github.com/microsoft/microsoft-ui-xaml

**Comment by gregwoo-microsoft** [comment]
Thanks for filing this @WelterDevelopment ! I am no longer able to repro this so I am closing this issue. Feel free to reopen it if you encounter this bug again.
