### ISSUE TITLE
WinUI3 recommends DataGrid from Windows Community Toolkit - However is not compatible

### ISSUE THREAD

**Issue by ivberg** [microsoft/Xaml-Controls-Gallery#696]
**Describe the bug**
WinUI3 recommends DataGrid from Windows Community Toolkit - However is not compatible

**Steps to reproduce the bug**

1. Setup app with WinUI3 0 - https://docs.microsoft.com/en-us/windows/apps/winui/winui3/
2. Attempt to install the latest DataGrid and it won't be compatible

**Expected behavior**
Recommended package is compatible - Microsoft.Toolkit.Uwp.UI.Controls.DataGrid

**Actual behavior**
Project Reunion WinUI3 is not compatible

**Screenshots**
Severity	Code	Description	Project	File	Line	Suppression State
Error		Package restore failed. Rolling back package changes for 'SampleAppUI'.				
Error	NU1202	Package Microsoft.Toolkit.Uwp.UI.Controls.DataGrid 7.0.2 is not compatible with net5.0-windows10.0.19041 (.NETCoreApp,Version=v5.0) / win10-arm64. Package Microsoft.Toolkit.Uwp.UI.Controls.DataGrid 7.0.2 supports: uap10.0.17763 (UAP,Version=v10.0.17763)	SampleAppUI	C:\src\SampleApp\SampleAppUI\SampleAppUI\SampleAppUI.csproj	1	
Error	NU1202	Package Microsoft.Toolkit.Uwp.UI.Controls.DataGrid 7.0.2 is not compatible with net5.0-windows10.0.19041 (.NETCoreApp,Version=v5.0) / win10-x64. Package Microsoft.Toolkit.Uwp.UI.Controls.DataGrid 7.0.2 supports: uap10.0.17763 (UAP,Version=v10.0.17763)	SampleAppUI	C:\src\SampleApp\SampleAppUI\SampleAppUI\SampleAppUI.csproj	1	
Error	NU1202	Package Microsoft.Toolkit.Uwp.UI.Controls.DataGrid 7.0.2 is not compatible with net5.0-windows10.0.19041 (.NETCoreApp,Version=v5.0) / win10-x86. Package Microsoft.Toolkit.Uwp.UI.Controls.DataGrid 7.0.2 supports: uap10.0.17763 (UAP,Version=v10.0.17763)	SampleAppUI	C:\src\SampleApp\SampleAppUI\SampleAppUI\SampleAppUI.csproj	1	
Error	NU1202	Package Microsoft.Toolkit.Uwp.UI.Controls.DataGrid 7.0.2 is not compatible with net5.0-windows10.0.19041 (.NETCoreApp,Version=v5.0). Package Microsoft.Toolkit.Uwp.UI.Controls.DataGrid 7.0.2 supports: uap10.0.17763 (UAP,Version=v10.0.17763)	SampleAppUI	C:\src\SampleApp\SampleAppUI\SampleAppUI\SampleAppUI.csproj	1	

**Version Info**
- [ x] App downloaded from Store 
1.3.6.0

**Additional context**
Reunion csproj

    <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>

No, I cannot lower the TargetFramework to 17763 or the app will no longer compile

Windows 10 version:
- [x ] Insider Build (21388)

Device form factor:
- [ x] Desktop

**Comment by ivberg** [comment]
It actually looks like these have moved namespaces to CommunityToolkit.WinUI.UI.Controls.DataGrid 

This has more info - https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3295

**Comment by veiny** [comment]
![image](https://user-images.githubusercontent.com/9784477/165874217-a103cf5d-bb7b-4aef-873c-83d35ad9659c.png)

![image](https://user-images.githubusercontent.com/9784477/165874160-95186629-2a80-4be4-babf-cc80885be9cb.png)

**Comment by veiny** [comment]
> 

why??

**Comment by ivberg** [comment]
See above comment - this is compatible but it's a different package name - CommunityToolkit.WinUI.UI.Controls.DataGrid
