### ISSUE TITLE
Microsoft C++ exception: winrt::hresult_error at memory location 0x0337DC80.

### ISSUE THREAD

**Issue by Symbai** [microsoft/Xaml-Controls-Gallery#697]
**Describe the bug**
When I try to launch debug win32 I receive this exception `Exception thrown at 0x76ADA6E2 in XamlControlsGallery.DesktopWap.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x0337DC80.`

**Steps to reproduce the bug**
1. Download code as zip file
2. Extract, open in VS and press launch

**Screenshots**
![image](https://user-images.githubusercontent.com/14368203/119782935-0700d400-becd-11eb-8123-d21d3f1ac770.png)

**Version Info**
- [X] App built locally from source 
  - Master branch, as of now

Windows 10 version:
21H1

Device form factor:
- [X] Desktop

I've installed project reunion extension and I've got these installed in VS 2019 Community Version 16.10.0:
- .NET Desktop environment
- Development for Windows universal platform
- C++ Development
- Under components I've got Windows SDK (10.0.18362.0) and Windows SDK (10.0.19041.0) checked

**Comment by stmoy** [comment]
Thanks for filing this issue - is it possible to `Continue` past the error? I seem to remember hitting something similar, but that hresult could be ignored. Can you check if it's possible to continue past it?

**Comment by Symbai** [comment]
Oh, indeed. Hitting continue works, thanks!
