### ISSUE TITLE
Sample markup doesn't update when the sample code changes

### ISSUE THREAD

**Issue by stmoy** [Microsoft/Xaml-Controls-Gallery#7]
**Describe the bug**

All the code that dynamically updates the XAML markup doesn't work, because the syntax highlighter replaces all the child elements with a RichTextBlock, so the bindings are happily mutating elements that are no longer in the tree.

**Steps to reproduce the bug**

1. See the ListView sample page, which has the following run:
'<Run Text="{x:Bind Control2.SelectionMode, Converter={StaticResource valueToStringConverter}, Mode=OneWay}"/'>

**Expected behavior**

When the SelectionMode changes, the change should be reflected in the markup

(There are several pages that are affected, not just ListView.)

**Actual behavior**

The markup doesn't change

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 

1.2.3.0

Windows 10 version:
- [X] Insider Build (xxxxx)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by Felix-Dev** [comment]
Good to see it being worked on! I liked the Xaml markup update functionality and was disappointed to see it not working in the updated app for the October SDK.

**Comment by stmoy** [comment]
Agreed. This was a hard tradeoff between live-updating and syntax highlighting, but since most of the samples don't live update, we prioritized the syntax highlighting for now.

**Comment by stmoy** [comment]
Fixed with PR #35 - closing.
