### ISSUE TITLE
ItemsRepeater - Change layout multiple times crashes the program

### ISSUE THREAD

**Issue by KiruyaMomochi** [microsoft/Xaml-Controls-Gallery#715]
**Describe the bug**
Change layout multiple times of "Basic, non-interactive items laid out by ItemsRepeater" will crashes the program.

**Steps to reproduce the bug**

1. Go to "ItemsRepeater" page
2. Click on "StackLayout - **Horizontal**" in "Layout" of "Basic, non-interactive items laid out by ItemsRepeater"
3. Click on "StackLayout - **Vertical**" in "Layout" of "Basic, non-interactive items laid out by ItemsRepeater"

**Expected behavior**
The layout changes successfully.

**Actual behavior**
The program crush.

**Screenshots**

![image](https://user-images.githubusercontent.com/65301509/123579073-b8b35d80-d809-11eb-91a4-273521238912.png)

**Version Info**
- [x] App downloaded from Store 
    - Version **1.2.18.0**
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3preview branch)

**Additional context**

Windows 10 version:
- [x] Insider Build (21390)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by gregwoo-microsoft** [comment]
Thank for for filing this bug @KiruyaMomochi  ! I can't repro this bug using the latest version of the Gallery so I will close this bug. Feel free to reopen it if you encounter it again.
