### ISSUE TITLE
SplitButton -> RichEditBox crashes app

### ISSUE THREAD

**Issue by asklar** [microsoft/Xaml-Controls-Gallery#720]
Going to the SplitButton page and changing the color in the RichEditBox will crash the app

CC @karenbtlai

**Comment by TapeWerm** [comment]
Happens to me on Windows 11 but not Windows 10 20H1.

**Comment by gregwoo-microsoft** [comment]
Thank for for filing this bug @asklar ! I can't repro this bug using the latest version of the Gallery so I will close this bug. Feel free to reopen it if you encounter it again.
