### ISSUE TITLE
WinUI 3 Gallery - Dark mode isn't working

### ISSUE THREAD

**Issue by Symbai** [microsoft/Xaml-Controls-Gallery#722]
**Describe the bug**
I've installed WinUI 3 Controls Gallery from Windows Store on both Windows 10 and Windows 11 systems. Started it and switch to dark mode in settings but nothing happens. The app remains white.

**Steps to reproduce the bug**
1. Download gallery from Windows Store
2. Start and go to settings
3. Switch to dark

FYI: Default mode in Windows 10/11 is light mode.

**Expected behavior**
It should become dark

**Actual behavior**
It stays white

**Screenshots**
![image](https://user-images.githubusercontent.com/14368203/124098699-1095d280-da5d-11eb-84e9-a607c783edd3.png)

**Version Info**
- [X] App downloaded from Store 
    - 1.3.6.0
- [ ] App built locally from source 

Windows 10 version:
- [X] May 2020 Update (19041)

Device form factor:
- [X] Desktop

**Comment by gregwoo-microsoft** [comment]
Hi @Symbai! Thanks for filing this issue. I believe that this was fixed in the latest WinUI 3 Gallery update. I'll close this for now but feel free to reopen it if you are still having issues with it.
