### ISSUE TITLE
Question: Is WinUI3 Control Gallery available for stable PR0.8?

### ISSUE THREAD

**Issue by get-flat** [microsoft/Xaml-Controls-Gallery#724]
Question: Is WinUI3 Control Gallery available for stable PR0.8? (in store: 1.3.5.0)

**Comment by anawishnoff** [comment]
@get-flat We're working on shipping it to the store - just running into a few issues, but hopefully should be published soon. The source code is updated on this repo on the winui3 branch if you'd like to clone it and run it!

**Comment by pablojimpas** [comment]
I've just received 1.3.7 update through the store and it says "WinUI 3 Windows App SDK 0.8" in the hero image of the "What's New" page. Without the updated Windows 11 visual style though.

**Comment by anawishnoff** [comment]
@pablojimpas Yup, we just pushed the latest version to the Store. The Windows 11 visual styles that are a part of WinUI 2.6 were not included in the WinUI 3 - Windows App SDK 0.8 release. You can expect to see those visual updates in a future version of WinUI 3, though.

**Comment by pablojimpas** [comment]
> @pablojimpas Yup, we just pushed the latest version to the Store. The Windows 11 visual styles that are a part of WinUI 2.6 were not included in the WinUI 3 - Windows App SDK 0.8 release. You can expect to see those visual updates in a future version of WinUI 3, though.

Aaahh I see...do we need to wait until 1.0 to get the visual update? I've to start a new app and now I don't know if I should choose UWP + WinUI 2.6 or Desktop/Project Reunion + WinUI 3 to be future proof...

btw I assume this issue can be closed now

**Comment by anawishnoff** [comment]
@pablojimpas Yup, you can expect to see the new visual changes in 1.0. However, they may be available for you to use before that in an experimental channel - we don't have exact dates, but you may not have to wait until the official stable release to start integrating the styles into your app.
