### ISSUE TITLE
AnimatedIcon - Guidance opens a 404 page

### ISSUE THREAD

**Issue by JuanMejiaVelez** [microsoft/Xaml-Controls-Gallery#727]
**Describe the bug**
When in the AnimatedIcon page under Styles, clicking on the AnimatedIcon guidance leads to https://docs.microsoft.com/en-us/windows/uwp/design/style/animated-icon which does not exits.

**Expected behavior**
An existing page opens

**Actual behavior**
A 404 page opens

**Version Info**
- [X] App downloaded from Store 
    - If so, which version? 1.2.19.0
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3preview branch)

Windows 10 version:
- [X] Insider Build (xxxxx)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by chingucoding** [comment]
@JuanMejiaVelez Would you like to contribute a fix for this?
