### ISSUE TITLE
Generate link to page doesn't work

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/Xaml-Controls-Gallery#732]
**Describe the bug**

The option named 'generate link to page' doesn't seem to work. It says copied to clipboard but I can't see it on the clipboard, nor can I paste it in the run box.

**Steps to reproduce the bug**

1. Open Xaml Controls Gallary.
2. Go to any sample page.
3. Click on generate link to page.
4. It will say copied to clipboard but not actually.

**Expected behavior**

It should copy the link to the clipboard.

**Actual behavior**

It says 'copied to clipboard' but it doesn't actually copy it to the clipboard.

**Version Info**
- [x] App downloaded from Store 
    - Version 1.2.19.0

Windows version:
- [x] Insider Build (22000.71)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by chingucoding** [comment]
That's strange, I just tried it with the store version (1.22.0) and it copied to the clipboard. Maybe, can you try doing this again and see if it still repros on your end?

**Comment by Jaiganeshkumaran** [comment]
> That's strange, I just tried it with the store version (1.22.0) and it copied to the clipboard. Maybe, can you try doing this again and see if it still repros on your end?

Still doesn't seem to work.

**Comment by gregwoo-microsoft** [comment]
Hey @Jaiganeshkumaran! I wasn't able to repro this: it works well on my end. Make sure to use the latest version of the Controls Gallery (we pushed out a new version in December 2021). I'll close this for now but feel free to reopen it if this is still not working for you :)
