### ISSUE TITLE
Top part of scrollbar of main content hidden by header

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/Xaml-Controls-Gallery#736]
**Describe the bug**

**Steps to reproduce the bug**

**Expected behavior**

**Actual behavior**

**Screenshots**

**Version Info**
- [ ] App downloaded from Store 
    - If so, which version? (Found on the Settings page of the app.)
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3preview branch)

**Additional context**

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [ ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

![image](https://user-images.githubusercontent.com/51363864/126773514-da158d62-b416-4ecf-8fd5-22043f8daa9a.png)
top part of scrollbar is hidden

**Comment by gregwoo-microsoft** [comment]
I don't fully understand the problem here. @Poopooracoocoo could you please give more details?

**Comment by Poopooracoocoo** [comment]
@gregwoo-microsoft Scroll down on the What's New page to get something like the screenshot above. And then try to scroll up by clicking on the up arrow which is covered by the header. I must've made this issue when I was tired. I usually try to write some form of STR. mb

**Comment by gregwoo-microsoft** [comment]
Thanks for clarifying 🙂 I can't manage to repro this: I am able to click on the up arrow (see red circle) and the page scrolls up. Are you using the latest version of the XCG?

![Screenshot 2022-01-05 163630](https://user-images.githubusercontent.com/90726278/148309653-adc8ed77-c095-4b45-b410-ffb41019ec75.png)

**Comment by Poopooracoocoo** [comment]
I guess it must've been fixed! I don't keep the XCG installed on my machine and only install it and test it every few months. I'll confirm when I get home and close the issue if it is fixed.

**Comment by gregwoo-microsoft** [comment]
Sounds good! 👍 and thank you for taking the time to file an issue

**Comment by Poopooracoocoo** [comment]
Can confirm, has been fixed.

**Comment by gregwoo-microsoft** [comment]
Ok great! Thanks!
