### ISSUE TITLE
use winui 2.6.1

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/Xaml-Controls-Gallery#738]
@chingucoding @anawishnoff

**Comment by anawishnoff** [comment]
This is a good callout, I hope to get a version in the store that uses 2.6.1 in the next week or so!

**Comment by anawishnoff** [comment]
The version in the store is now using 2.6.1. The code should get merged into the master branch shortly.

**Comment by Poopooracoocoo** [comment]
@anawishnoff https://github.com/microsoft/Xaml-Controls-Gallery/releases doesn't have the newest release. mind doing that too?
