### ISSUE TITLE
Navigation events are fired when moving to a page but not from. 

### ISSUE THREAD

**Issue by SavoySchuler** [microsoft/Xaml-Controls-Gallery#74]
**Describe the bug**

OnNavigatedFrom and related navigation events do not surface when navigated from any control's sample page.

**Steps to reproduce the bug**

1. Add OnNavigatedFrom function to any control's sample page codebehind (e.g., TeachingTipPage.xaml.cs) with an attached break point.
2. Navigated to and from this page. 

**Expected behavior**

I expect the break point to be triggered.

**Actual behavior**

The break point is not triggered. 

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 

1.1.1.0

Windows 10 version:
- [X] Insider Build (18865)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

I am attempting to add a function to close open teaching tips when navigating away from the TeachingTip sample page and OnNavigatedFrom is not working.

**Comment by YuliKl** [comment]
> I am attempting to add a function to close open teaching tips when navigating away from the TeachingTip sample page

@SavoySchuler, had you by chance opened an issue to track this?
