### ISSUE TITLE
Settings looks funny - perhaps by design?

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/Xaml-Controls-Gallery#749]
**Describe the bug**

**Steps to reproduce the bug**

**Expected behavior**

**Actual behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/51363864/127433088-8dc39053-8188-4a20-84c9-58b0d60279e9.png)

**Version Info**
- [x] App downloaded from Store 
    - If so, which version? (Found on the Settings page of the app.)
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3 branch)

**Additional context**

Windows version:
- [ ] Insider Build (xxxxx)
- [x] May 2021 Update (19043)
- [ ] October 2020 Update (19042)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by myokeeh** [comment]
Are you talking about the Settings header text? If so, it's apparently by design: https://github.com/microsoft/microsoft-ui-xaml/issues/5405

**Comment by Poopooracoocoo** [comment]
@myokeeh sheeeeeeeesh

**Comment by Poopooracoocoo** [comment]
Actually its a combination of the header text and the text of each section.

**Comment by Poopooracoocoo** [comment]
@anawishnoff

**Comment by TapeWerm** [comment]
Looks like an alignment issue to me. The body is not aligned or indented with the header.

**Comment by Chips1234** [comment]
This issue seems to be resolved now...
![image](https://user-images.githubusercontent.com/47545798/147302637-43c8345b-89aa-416a-9dc8-daf758b7cf5e.png)

**Comment by Poopooracoocoo** [comment]
Jesus they never even bothered closing this themselves. Microsoft is in a sad, profit driven state...

**Comment by Chips1234** [comment]
Perhaps they are busy on another project? But, for sure, this repository seems a bit neglected…


On Dec 23, 2021, at 19:34, Poopooracoocoo ***@***.***> wrote:

﻿

Jesus they never even bothered closing this themselves. Microsoft is in a sad, profit driven state...

**Comment by Poopooracoocoo** [comment]
Nah I'd say most of Windows is neglected.

**Comment by gregwoo-microsoft** [comment]
Thank you @Chips1234 and @Poopooracoocoo for closing the issue and happy new year! There were several issues that mentioned this bug and we forgot to close this one. Thanks for catching it!

I can assure you that this repo is not being neglected. We are doing the best we can to improve the XCG and answer issues. If you have any suggestions on how we can improve things on this repo, feel free to let me know (you can also post in the Discussions tab if you want).

**Comment by Poopooracoocoo** [comment]
@gregwoo-microsoft Mate... I'm no QA tester but I racked up a few
![image](https://user-images.githubusercontent.com/51363864/148162739-cdd4d2b2-2072-4a77-8b8c-b88eccd39333.png)
And then there's all the issues that were transferred to the WinUI repo and neglected there. And there are a bunch of stale PRs that have yet to be closed or followed up on.

**Comment by gregwoo-microsoft** [comment]
I understand your frustration. I'll have a closer look at the issues you have created. Overall, thank you very much for contributing to the repo and listing issues. It's a big help.
