### ISSUE TITLE
Add support for acrylic fallback to main UI when Mica is unavailable (and of course fallback to solid colour)

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/Xaml-Controls-Gallery#750]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] New sample
- [ ] Addition to existing sample
- [ ] Modification to existing sample
N/A.

**If this is an addition/modification to an existing sample page, which one?**

**Describe the sample**

not a sample, dummy.

**Is your sample request related to a problem? Please describe it**

NOT A SAMPLE REQUEST OMG

**Additional context**

![image](https://user-images.githubusercontent.com/51363864/127433088-8dc39053-8188-4a20-84c9-58b0d60279e9.png)

**Comment by mdtauk** [comment]
Mica handles fallback itself, with WinUI AFAIU

Right now, on Windows 10, Mica displays as a solid background colour, the same as when a Mica window is inactive on Windows 11.

**Comment by Poopooracoocoo** [comment]
@mdtauk I know ;)

**Comment by fitojb** [comment]
@Poopooracoocoo Then it's not clear what you're requesting people to add. Mica (from WinUI 2.6 onwards) is already runnable on Windows 10, so there is no hypothetical situation where "Mica is unavailable"; it just looks different than on Win11. Acrylic as a main background material is deprecated, Mica being its replacement in newer designs. Acrylic's fallback to solid color in certain situations is already the same when you swap that with Mica. Acrylic is only intended to be used on _transient_ surfaces like flyouts, teaching tips with no controls, and context menus, and not in the UI's base layer, as macOS does on certain surfaces like non-floating sidebars.

(Off-topic: issue templates are not rigid and you can easily delete anything that doesn't apply. No need to call anybody a dummy.)

**Comment by gregwoo-microsoft** [comment]
Thank you for clarifying @fitojb. I'll close this issue.

**Comment by Poopooracoocoo** [comment]
@gregwoo-microsoft Can you confirm if Mica is available for Windows 10 as per the comment you cited above? That's the part that confuses me and if that's not correct makes their point moot.

**Comment by gregwoo-microsoft** [comment]
The above comment is correct, Mica is available on Windows 10 and will show a solid color: https://docs.microsoft.com/en-us/windows/apps/design/style/mica#usability-and-adaptability As Acrylic is only intended for transient surfaces and not long-lasting backgrounds due to performance and appearance considerations, we do not recommend it as a fallback color for any app backgrounds.

**Comment by Poopooracoocoo** [comment]
> and will fallback to show a solid color: https://docs.microsoft.com/en-us/windows/apps/design/style/mica#usability-and-adaptability 

That's what I meant. Mica falls back to a solid colour.
>As Acrylic is only intended for transient surfaces and not long-lasting backgrounds due to performance and appearance considerations, we do not recommend it as a fallback color for any app backgrounds.

Got it. 👍
