### ISSUE TITLE
Split button not working

### ISSUE THREAD

**Issue by GatoNaranja** [microsoft/Xaml-Controls-Gallery#753]
**Describe the bug**
Split button leads to application crash when choosing a color

**Steps to reproduce the bug**

1. Go to 'Basic Input' -> 'Split Button'
2. Click on 'the first split button'

**Expected behavior**
 No crash || block

**Actual behavior**
 crash || block

**Screenshots**

**Version Info**
- [x] App downloaded from Store 
    - If so, which version? (Found on the Settings page of the app.)
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3 branch)

**Additional context**

Windows version:
- [x] Insider Build (xxxxx)
- [ ] May 2021 Update (19043)
- [ ] October 2020 Update (19042)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by chingucoding** [comment]
I can't seem to repro this issue using the latest build on master branch. @GatorNaranja if you have the time and would like to try building from source and reproducing the issue, that would be very helpful (of course you don't have to).

**Comment by gregwoo-microsoft** [comment]
Thank for for filing this bug @GatoNaranja! I can't repro this bug using the latest version of the Gallery so I will close this bug. Feel free to reopen it if you encounter it again.
