### ISSUE TITLE
Top Banner Title Color in Light Mode

### ISSUE THREAD

**Issue by RiteshKSingh1709** [microsoft/Xaml-Controls-Gallery#764]
Top banner Title Color in Light Mode is white which gets disappeared as background is also white. Screenshot is attached with this issue.
![InkedTextColorInLightMode_LI](https://user-images.githubusercontent.com/10517315/131280461-e5364bd5-6bee-4c49-8d03-5b9a304d1b6c.jpg)

**Comment by chingucoding** [comment]
I think this is the same as #710 which will be fixed by #761.

**Comment by chingucoding** [comment]
@gregwoo-microsoft I think we can also close this now since this was fixed with #761.

**Comment by gregwoo-microsoft** [comment]
You're right. Good call :)
