### ISSUE TITLE
And the CS/VB Code?

### ISSUE THREAD

**Issue by Endermanch-Fan** [microsoft/Xaml-Controls-Gallery#767]
And the Code???

**Steps to reproduce the bug**
1. Go to any example
2. Search the code, only shows the XamL Code, but no the event (cs/vb)
3. Appears Click(event)="example_Click" but the example_Click  code??

**Screenshots**
![image](https://user-images.githubusercontent.com/88939475/132984640-32304594-fc66-4c49-a9af-85e8ac0c067f.png)

**Expected behavior**
Show the VB/CS Code

**Actual behavior**
Programming C# in XAML/WinUI 3, only shows the XAML code, but no the CS/VB Code

**Version Info**
- [ WinUI 3 Controls Gallery ] App downloaded from Store 
    - 1.3.9.0

Windows version:
- [ Windows 11 ] Insider Build (10.0.22000.176 / 21H2)

Device form factor:
- [ Windows ] Desktop

**Comment by chingucoding** [comment]
I think this was closed by #786, strange why merging that PR didn't close this issue.

**Comment by gregwoo-microsoft** [comment]
Yes that is weird. I will just manually close it now.

**Comment by gregwoo-microsoft** [comment]
Thanks for pointing this out @chingucoding
