### ISSUE TITLE
Trying to change color in the SplitButton first sample crashes the app.

### ISSUE THREAD

**Issue by JuanMejiaVelez** [microsoft/Xaml-Controls-Gallery#773]
**Describe the bug**
When navigating to the Basic Input> SplitButton and trying to change color in the first sample the app crashes.

**Steps to reproduce the bug**

1. Go to 'Basic Input> SplitColor'
2. Click on 'Color split button on first example'

**Expected behavior**
Color on text changes

**Actual behavior**
App crashes

**Version Info**
- [X] App downloaded from Store 
    - If so, which version? 1.2.21.0
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3 branch)

**Additional context**

Windows version:
- [X] Insider Build (22000.194)
- [ ] May 2021 Update (19043)
- [ ] October 2020 Update (19042)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by gregwoo-microsoft** [comment]
Thank for for filing this bug @JuanMejiaVelez ! I can't repro this bug using the latest version of the Gallery so I will close this bug. Feel free to reopen it if you encounter it again.
