### ISSUE TITLE
[Question] How can I build a desktop app instead of UMP

### ISSUE THREAD

**Issue by TENX-S** [microsoft/Xaml-Controls-Gallery#778]
I want a portable executable file, an ordinary Win32 program.

**Comment by stmoy** [comment]
Off topic. Consider taking a look at https://docs.microsoft.com/en-us/windows/apps/desktop/ for a list of options for building a Win32 app.

**Comment by movpushmov** [comment]
> I want a portable executable file, an ordinary Win32 program.

You can't build an UWP app as a portable executable file.
