### ISSUE TITLE
     DEP6957: Failed to connect to device '127.0.0.1' using Universal Authentication.

### ISSUE THREAD

**Issue by ali-h2010** [Microsoft/Xaml-Controls-Gallery#80]
**Describe the bug**

I am getting an error when trying to run the app

Error DEP6957: Failed to connect to device '127.0.0.1' using Universal Authentication. Please verify the correct remote authentication mode is specified in the project debug settings. COMException - Error HRESULT E_FAIL has been returned from a call to a COM component. [0x80004005]	XamlControlsGallery			

**Steps to reproduce the bug**

1. Download or clone the repo
2. Build and start the solution

**Expected behavior**

The app should run normally

**Actual behavior**

I am getting the error upove

**Screenshots**

**Version Info**

Windows 10
Visual Studio 2019

Gallery version (found on Settings page): 

Latest version

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [*] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [*] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by ali-h2010** [comment]
Apparently, the issue occurs when i use ARM build configuration

**Comment by jevansaks** [comment]
Are you trying to run against an ARM desktop device? If not this is just an obnoxious quirk of Visual Studio where it defaults to the ARM configuration when you first load the solution. You need to choose x64 from the platform target dropdown.

**Comment by jrahma** [comment]
I have the same problem with fresh windows 10 installation and Visual Studio 2019 an with  simple one Page UWP app

**Comment by stmoy** [comment]
Make sure that the debug target is x86 or x64. Debugging directly to ARM configuration can cause this error.

**Comment by eisenWu** [comment]
How to solve this problem? same here.

**Comment by tjfischer** [comment]
I have the same issue. I did as you suggested and switch the build over to x86 then x64 and I obtained the same results as with ARM. Is there something else I'm missing?

**Comment by PhilippFlach** [comment]
I had the same issue. Changing the  configuration to x64 really solved the problem. It is important that you update the  target platform in the property of the solution (configuration properties) - and save the changes. In the menu at the top ensure that x64 is displayed (beneath to the debug drop down). Moreover check that Output window shows ...  Configuration: Debug x64 ------ when you are rebuilding the solution.

**Comment by SetTrend** [comment]
Shouldn't this issue be reported to the VS team for them to implement something to circumvent this confusion?

When I renamed and re-added an UWP project to my solution, ARM was selected by default. I believe that VS should take care not to select a configuration that won't build.

**Comment by stmoy** [comment]
CC: @JeanRoca - I agree with @SetTrend that it'd be great if VS/tooling could be smarter here. Putting this on your radar in case you haven't seen this issue.

**Comment by ColinV2027** [comment]
I've tried changing the target to x64 and still getting the error?

**Comment by ColinV2027** [comment]
> @ColinV2027 - can you confirm if this is happening with specifically the Xaml Controls Gallery or if it affects other apps as well? I wonder if this might indicate a VS setup issue depending on what is affected. Additionally, have you attempted building x86?

I have tried it on the default windows barcode application sample they provide, and I have tried both x64 and x86 anywhere I could find it. I believe it's a vs issue since I've never built in Universal Windows Apps or whatever its called. The closest I've ever used is .NET Framework with c#

**Comment by tzuusan** [comment]
I feel it confusing that there are many places to select ARM/x64 dropdown. The correct place to fix this error was
`MENU - Build - Configuration Manager - Active solution platform`,
(keyboard `[ALT] - [B] - [O] - [Alt + P]`),
or more simply, the dropdown just AT LEFT of GREEN PLAY TRIANGLE on TOOLBAR.

MENU - Project - Properties - Build - Platform did NOT fix this problem!

**Comment by jalilmar** [comment]
Must be changed both in debug and build mode (X86 or X64).
Pb fixed for me

**Comment by AMArostegui** [comment]
In my case, Visual Studio 2022, Windows 10 21H2, MS Emulator 10.0.15254.1, I was unable to make it work.

It might have something to do with the image or emulator I have installed, being for mobile x86.

In any case, I decided to try Visual Studio 2019 and it works.

**Comment by DetermLZ** [comment]
I am using VS 2019 to deploy HoloLens 2 applications. This error is solved after installing "USB device connectivity" in the VS installer.

**Comment by royalr-22** [comment]
this isnt working for me . waste of time.

>

**Comment by sktistakis** [comment]
> I am using VS 2019 to deploy HoloLens 2 applications. This error is solved after installing "USB device connectivity" in the VS installer.

Thank you! This solved my problem when deploying via USB to Hololens 2.
