### ISSUE TITLE
SemanticZoom combined with GridView cause the GroupHeader swaying during the scrolling

### ISSUE THREAD

**Issue by OneFingerCodingWarrior** [microsoft/Xaml-Controls-Gallery#805]
**Describe the bug**
SemanticZoom combined with GridView cause the GroupHeader swaying during the scrolling

**Steps to reproduce the bug**
check out the following project (Do not use full screen mode. Try resize the window to different size. Some size will behavior normal )

https://github.com/OneFingerCodingWarrior/Swaying.git

![swaying](https://user-images.githubusercontent.com/53161726/139395956-b386a715-4d62-4989-86b4-026617bc39e3.gif)

If scroll with vertical bar, control behavior normal
![scroll with vertical bar-normal](https://user-images.githubusercontent.com/53161726/139395983-4fb008cc-fd0d-4c93-b420-772deee1d96e.gif)

Device form factor:Desktop
Windows version: 21H1 19043.1288
Microsoft Visual Studio Community 2019
Version 16.11.5

**Comment by gregwoo-microsoft** [comment]
Awesome! Glad you managed to fix it.

**Comment by OneFingerCodingWarrior** [comment]
What i really mean is  The bug is appearing again, and i can't fix it

> Awesome! Glad you managed to fix it.

**Comment by OneFingerCodingWarrior** [comment]
@gregwoo-microsoft how can i reopen this issue?

**Comment by OneFingerCodingWarrior** [comment]
If SplitView is combined with SemantiZoom and GridView, the swaying will emerging in all windows size, and that's my real problem

**Comment by chingucoding** [comment]
I think this issue is more suited for the WinUI repository: https://github.com/microsoft/microsoft-ui-xaml

**Comment by OneFingerCodingWarrior** [comment]
> I think this issue is more suited for the WinUI repository: https://github.com/microsoft/microsoft-ui-xaml

What should i do ? Fire a issue in  https://github.com/microsoft/microsoft-ui-xaml?
But my app does not use  microsoft-ui-xaml , is it appropriate to fire a issue?
What about the third gif? The XAMLControls Gallery app also has this issue!

**Comment by OneFingerCodingWarrior** [comment]
@chingucoding i have fire a new issue in https://github.com/microsoft/microsoft-ui-xaml , thanks
