### ISSUE TITLE
Compilation always end with Error: Could not find SDK "WindowsDesktop, Version=10.0.18362.0"

### ISSUE THREAD

**Issue by EricOuellet2** [microsoft/Xaml-Controls-Gallery#807]
**Describe the bug**
Although I have SDK 10.0.18362.1 installed and 10.0.22000.194 installed I always get the error: 
Could not find SDK "WindowsDesktop, Version=10.0.18362.0"
It is impossible to get the required SDK from Microsoft, only 10.0.18362.1 is available, so why do you fix this version?
I try to change the csproj without success.

**Steps to reproduce the bug**

1. Download and compile

**Expected behavior**
Works

**Actual behavior**
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not find SDK "WindowsDesktop, Version=10.0.18362.0".	XamlControlsGallery			

**Screenshots**
![Microsft sample not working](https://user-images.githubusercontent.com/10049632/139497475-05bf0ecf-74bc-40a2-b87c-9ad0168ff625.png)

**Version Info**
Most recent Visual Studio 2019 version and Windows Version.

**Additional context**

Windows version:
Most recent

Device form factor:
- [ x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by ahcxaax** [comment]
Path

**Comment by ahcxaax** [comment]
这个是路径的问题，我猜你也没有把SDK下载到C盘

**Comment by chingucoding** [comment]
Hi @EricOuellet2 , can you take a screenshot of the workloads installed in the Visual Studio Installer? While the SDK seems to be installed, it seems that VS has a different opinion of this.

**Comment by gregwoo-microsoft** [comment]
@EricOuellet2 I'll close this issue for now. Feel free to reopen it if you are still encountering this issue :)
