### ISSUE TITLE
TeachingTip is displayed in the wrong location

### ISSUE THREAD

**Issue by HHChaos** [Microsoft/Xaml-Controls-Gallery#81]
**Describe the bug**

When changing the selected item in the left navigationView of the sample application, and then entering the TeachingTip example page, TeachingTip will be displayed in the wrong location.

**Steps to reproduce the bug**

1. Navigate to the "All controls" page and back to the "What's New" page.
2. Navigate to the TeachingTip sample page and click the first "Show TeachingTip" button。

**Expected behavior**

TeachingTip should appear to the left of the "ToggleTheme" button.
**Actual behavior**

TeachingTip is displayed in the wrong location.

**Screenshots**

![teachingtipbug](https://user-images.githubusercontent.com/9880072/55857002-938d9280-5b9e-11e9-9c9f-e9d1c1d8aa03.gif)

**Version Info**

Gallery version (found on Settings page): 

1.1.1.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

I read the source code and found that `PageHeader.TeachingTip1`(and `PageHeader.TeachingTip2`、`PageHeader.TeachingTip3`) is a wrong reference when switching navigation pages. I will provide a bug fix later.

**Comment by SavoySchuler** [comment]
Resolved with @HHChaos 's [code submission](https://github.com/Microsoft/Xaml-Controls-Gallery/pull/82).

**Comment by SavoySchuler** [comment]
Thanks for your help, @HHChaos!
