### ISSUE TITLE
App crashes on Animation interop screen

### ISSUE THREAD

**Issue by plonkaadam** [microsoft/Xaml-Controls-Gallery#813]
**Describe the bug**

App crashes on Animation interop screen

**Steps to reproduce the bug**

1. Go to 'Motion'
2. Click on 'Animation interop'

**Expected behavior**

Some screen appears

**Actual behavior**

Application crashes with no info

**Screenshots**

**Version Info**
- [x] App downloaded from Store 
    - 1.3.9.0
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3 branch)

**Additional context**

Windows version:
- [x] Windows 11 21H2 (22000)
- [ ] Insider Build (xxxxx)
- [ ] May 2021 Update (19043)
- [ ] October 2020 Update (19042)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by gregwoo-microsoft** [comment]
@plonkaadam it seems like this got fixed. I can't repro this bug. Feel free to reopen this issue if you encounter this again. Thanks for filing this! :)
