### ISSUE TITLE
flip in few items

### ISSUE THREAD

**Issue by DJDQfff** [microsoft/Xaml-Controls-Gallery#818]
**Describe the bug**

When I  add item to ObservableCollection<> that is the source of FlipView,it can only changes in the front items.

**Steps to reproduce the bug**

1. ususa step of using Flipview,it is ok
2. i used x:load in the datatemplate of item,it work exceptly(not sure)

**Expected behavior**

**Actual behavior**

only change in a few items (the front of list)

**Screenshots**

**Version Info**
- [ ] Xaml Controls Gallery - Downloaded from Store
    - If so, which version? (1.2.x -- Found on the Settings page of the app.)
- [ ] WinUI 3 Controls Gallery - Downloaded from Store 
    - If so, which version? (1.3.x -- Found on the Settings page of the app.)
- [x] App built locally from source 
  - winui2,not 3

**Additional context**

Windows version:
- [ ] Insider Build (xxxxx)
- [x] May 2021 Update (19043)
- [ ] October 2020 Update (19042)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by chingucoding** [comment]
Is this is an issue with the FlipView samples or rather an issue with the FlipView control? In the later case, the [WinUI repo](https://github.com/microsoft/microsoft-ui-xaml) would be more suitable for that kind of feedback.

**Comment by gregwoo-microsoft** [comment]
@DJDQfff I am closing this for now. Feel free to reopen this if it is a XAML Controls Gallery issue or to open an issue on the WinUI repo as @chingucoding suggested if this is an issue with the FlipView control.
