### ISSUE TITLE
No PanePosition for NavigationView

### ISSUE THREAD

**Issue by Meister1867** [microsoft/Xaml-Controls-Gallery#833]
**Describe the bug**
After copying-and-pasting the code I get the following error message

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'NavigationView' does not contain a definition for 'PanePosition' and no accessible extension method 'PanePosition' accepting a first argument of type 'NavigationView' could be found (are you missing a using directive or an assembly reference?)	PFM2022_App	C:\Users\wdele\source\repos\PFM2022\PFM2022_App\MainWindow.xaml.cs	35	Active

**Version Info**
- [X] Xaml Controls Gallery - Downloaded from Store
    Version 1.2.22.0

Device form factor:
- [ X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

`<muxc:NavigationView x:Name="nvSample" PaneDisplayMode="Top"
    SelectionFollowsFocus="Enabled" IsBackButtonVisible="Collapsed">
    <muxc:NavigationView.MenuItems>
        <muxc:NavigationViewItem Icon="Play" Content="Item1" x:Name="SamplePage1Item" />
        <muxc:NavigationViewItem Icon="Save" Content="Item2" x:Name="SamplePage2Item" />
        <muxc:NavigationViewItem Icon="Refresh" Content="Item3" x:Name="SamplePage3Item" />
        <muxc:NavigationViewItem Icon="Download" Content="Item4" x:Name="SamplePage4Item" />
    </muxc:NavigationView.MenuItems>
    <Frame x:Name="contentFrame"/>
</muxc:NavigationView>`

`//C# code behind
private void NavView_ItemInvoked(NavigationView sender, NavigationViewItemInvokedEventArgs args)
{
    FrameNavigationOptions navOptions = new FrameNavigationOptions();
    navOptions.TransitionInfoOverride = args.RecommendedNavigationTransitionInfo;
    if (sender.PanePosition == NavigationViewPanePosition.Top)
    {
        navOptions.IsNavigationStackEnabled = False;
    }
    Type pageType;
    if (args.SelectedItem == SamplePage1Item)
    {
        pageType = typeof(SamplePage1);
    }
    else if (args.SelectedItem == SamplePage2Item)
    {
        pageType = typeof(SamplePage2);
    }
    else if (args.SelectedItem == SamplePage3Item)
    {
        pageType = typeof(SamplePage3);
    }
    else if (args.SelectedItem == SamplePage4Item)
    {
        pageType = typeof(SamplePage4);
    }
    ContentFrame.NavigateToType(pageType, null, navOptions);
}`

**Comment by chingucoding** [comment]
Hi @meister1867, the sample for this is indeed faulty. The C# code should be the following instead:

```c#
private void NavView_ItemInvoked(NavigationView sender, NavigationViewItemInvokedEventArgs args)
{
    FrameNavigationOptions navOptions = new FrameNavigationOptions();
    navOptions.TransitionInfoOverride = args.RecommendedNavigationTransitionInfo;
    if (sender.PaneDisplayMode == NavigationViewPaneDisplayMode.Top)
    {
        navOptions.IsNavigationStackEnabled = False;
    }
    Type pageType;
    if (args.SelectedItem == SamplePage1Item) 
    {
        pageType = typeof(SamplePage1);
    }
    else if (args.SelectedItem == SamplePage2Item) 
    {
        pageType = typeof(SamplePage2);
    }
    else if (args.SelectedItem == SamplePage3Item) 
    {
        pageType = typeof(SamplePage3);
    }
    else if (args.SelectedItem == SamplePage4Item) 
    {
        pageType = typeof(SamplePage4);
    }
    ContentFrame.NavigateToType(pageType, null, navOptions);
}
```
