### ISSUE TITLE
InfoBadge embedded in NavigationView example buggy when switching from LeftExpanded -> LeftCompact

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/Xaml-Controls-Gallery#843]
**Describe the bug**

**Steps to reproduce the bug**
1. Go to `InfoBadge` page
2. Switch the display mode on the first example to `LeftExpand`
3. Switch to `LeftCompact`

**Expected behavior**
Correctly showing compact mode

**Actual behavior**
Showing expanded mode, and no text.

**Screenshots**
![image](https://user-images.githubusercontent.com/42881734/150304324-c80deea8-8895-4de4-82bf-1a0b56f67e5a.png)

https://user-images.githubusercontent.com/42881734/150304345-9185f7e2-ce91-44df-8c16-9127535d68f2.mp4

**Version Info**
- [x] Xaml Controls Gallery - Downloaded from Store
    - If so, which version? (1.2.x -- Found on the Settings page of the app.) `1.2.22.0`
- [ ] WinUI 3 Controls Gallery - Downloaded from Store 
    - If so, which version? (1.3.x -- Found on the Settings page of the app.)
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3 branch)

Windows version:
Windows 10 21H2

Device form factor:
- [x] Desktop

**Comment by HO-COOH** [comment]
Note the video does not correctly captures the drop down of the button, but it's working correctly.

**Comment by HO-COOH** [comment]
Same behavior also occurs in Windows 11.

**Comment by gregwoo-microsoft** [comment]
Thank you @HO-COOH for filing this issue. I am able to repro this.
