### ISSUE TITLE
Is there a C + + sample? of winui3

### ISSUE THREAD

**Issue by liangboIcyice** [microsoft/Xaml-Controls-Gallery#851]

**Comment by gregwoo-microsoft** [comment]
Hey @liangboIcyice! No, we don't provide cpp samples at the moment and are mostly focused on c# samples. However, feel free to contribute to this repo by adding cpp snippets if you want! We would definitely welcome your help.

**Comment by 908317477** [comment]
> 嘿@liangboIcyice！不，我们目前不提供 cpp 示例，主要关注 c# 示例。但是，如果您愿意，可以通过添加 cpp 片段来随时为这个 repo 做出贡献！我们绝对欢迎您的帮助。
ok，  I want to know how to use XAML designer for visual UI design of C + + program?Xaml designer will greatly increase efficiency

**Comment by 908317477** [comment]
@gregwoo-microsoft 
ok， I want to know how to use XAML designer for visual UI design of C + + program?Xaml designer will greatly increase efficiency
