### ISSUE TITLE
SplitButton has a bug

### ISSUE THREAD

**Issue by kiandevelop** [microsoft/Xaml-Controls-Gallery#856]
Hi
In the basic input branch, SplitButton controller has a bug
The first button in the SplitButton page, when you select the color the program closes

**Comment by gregwoo-microsoft** [comment]
Hey @kiandevelop! Thank you for filing this issue. Are you sure that you are using the latest version that is available in the Store? This bug was fixed in the newest version.

**Comment by kiandevelop** [comment]
Yes, I'm sure
I used the latest version in debugged and released mode
But it seems that the bug has not been fixed
Please watch this video:
https://user-images.githubusercontent.com/70108361/151920556-d990f0b6-b564-4bff-b7ff-afeb7a6f147a.mp4

**Comment by gregwoo-microsoft** [comment]
You are right, I am able to repro this as well. This bug has been fixed in the WInUI 3 Controls Gallery.

**Comment by kiandevelop** [comment]
It seems to be fixed in the latest version of the bug!
