### ISSUE TITLE
An object created for no reason

### ISSUE THREAD

**Issue by kiandevelop** [microsoft/Xaml-Controls-Gallery#866]
Hello, in the SettingsPage.xaml.cs class of[ line 80](https://github.com/microsoft/Xaml-Controls-Gallery/blob/dfa35dc5a25b5c3262b544f9d4117743e4934059/XamlControlsGallery/SettingsPage.xaml.cs#L80), an object was created from the ApplicationViewTitleBar that was not used anywhere in the project. What is the reason?

**Comment by gregwoo-microsoft** [comment]
This is surely a line that we forgot to omit. Thanks for spotting this! We'll make sure to remove this line in the future.

**Comment by gregwoo-microsoft** [comment]
Reopening this until we fix it
