### ISSUE TITLE
App theme switching and saving. (Default/Dark/Light)

### ISSUE THREAD

**Issue by BobbyESP** [microsoft/Xaml-Controls-Gallery#873]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [x] New sample
- [ ] Addition to existing sample
- [ ] Modification to existing sample

**Describe the sample**
I wanted a sample about the app theme (being able to change the hole application theme between dark mode and light mode).

**Is your sample request related to a problem? Please describe it**
Not with the XAML Controls Gallery app.

**Additional context**
 I want this sample because i can't find the correct way to do it and being able to save the selected mode after reopening my app).

**Comment by chingucoding** [comment]
Hi, the [ThemeHelper](https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/Helper/ThemeHelper.cs) in this repository is probably exactly what you need. It covers the setting theme and storing the theme setting using ApplicationData.

**Comment by BobbyESP** [comment]
Ohh, nice!! Thanks a lot for your help!
