### ISSUE TITLE
Search should be more inclusive than literal

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/Xaml-Controls-Gallery#96]
**Describe the bug**
Searching is done by type but users who don't know the exact type or using a more descriptive search may get 'no results'

**Steps to reproduce the bug**

1. Open the app
2. Click on search box
3. Type 'Split Button'

**Expected behavior**
See 'SplitButton'

**Actual behavior**
no results

**Screenshots**
![image](https://user-images.githubusercontent.com/24302614/58151218-dd49ae00-7c1d-11e9-9184-aca3590b5d3b.png)

**Version Info**

Gallery version (found on Settings page): 
1.2.7.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] 18362
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by emiliano84** [comment]
If can I add a related small suggestion, without open a new issue, after I search something, for example "hub", if I go directly to the hub page from the suggestion, without passing by the results, there is no way to understand which is the Hub  category (Navigation). Would be nice to add in the header of the page some kind of breadcrumbs for example Navigation > Hub, Instead of just Hub. Thanks

**Comment by YuliKl** [comment]
@emiliano84, we're planning to update Xaml Controls Gallery to use hierarchical navigation when that [feature](https://github.com/microsoft/microsoft-ui-xaml/issues/79) comes online. When this proposed update is made, the list in the Gallery's left side will show the expanded Navigation category and all of its sub-items, with the Hub item showing as selected. Will this be a reasonable way of addressing your request?

**Comment by Poopooracoocoo** [comment]
@YuliKl While hierarchical navigation should totes be added to WinUI, I don't think it suits XAML Controls Gallery. I think it should have headers instead. 

I also like breadcrumbs though. File explorers (such as Dropbox, OneDrive, Google Drive, File Explorer and Samsung Files) use them. That should also be added to WinUI but not XAML Controls Gallery. :D

**Comment by emiliano84** [comment]
@YuliKl sounds good enough for me :)
